### ISSUE TITLE
Create landing page in React

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#10]
The landing page needs to be created in React as per the design laid out (right now just in Discord, we should add these design docs in a directory in this repo somewhere perhaps)

**Comment by tesla809** [comment]
Use the assets in /design created by @BrianHHough.

**Comment by roychowd** [comment]
Anyone working on this? Also, in React or React Native?

**Comment by SomeMoosery** [comment]
Hey Roy! I had created this issue a while back, when we were first laying the groundwork for this product. As it stands now, the landing page is going to be made up of a bunch of components we've made / are making based off of the mockups/wireframes by @BrianHHough in `/design/wireframes/corona_tracker_landing_page.png`.

It looks like we're getting close to having all the components in place to start putting together this landing page, but there's still things that have yet to be done. I've been focusing pretty heavily on getting up and running with Blockstack on the backend/database side of things, but I know @tesla809 has been doing a great job keeping track of what's being worked on / where we're at on the frontend. There's definitely work to be done, but it might be better to break out a more refined issue and get going on that.

Thoughts?

Also, feel free to join the Discord in the README if you haven't already!

**Comment by tesla809** [comment]
@roychowd check out #16 and its sub-issues. A great place to start that needs some help.

**Comment by SomeMoosery** [comment]
Closing this, as "Landing Page" is a little too vague and I think we have more issues surrounding this that make more sense.

**Comment by tesla809** [comment]
Agreed
