### ISSUE TITLE
Add `.github` directory to `.gitignore`, update commit history

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#104]
Task

I know It's generally bad practice to "rewrite history," but we should add `.github` to our `.gitignore`, and then see if there's a way to remove it from future commits and get it out of our commit history (or at least make it "invisible" publicly)

**Comment by friedger** [comment]
I don't think it is necessary to rewrite history for that. No private information in there..

**Comment by friedger** [comment]
Furthermore, I don't think it is bad if we keep a copy of our collaboration guidelines in git

**Comment by SomeMoosery** [comment]
That's fair - no private info, public guidelines... I was just modeling off of some other, larger OSS projects but there's definitely not harm in leaving our guidelines available for people to see.

Unless anyone else disagrees, I'm okay closing this issue.
