### ISSUE TITLE
Create Location Model

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#113]
## Summary

We need a way to keep track of users' location. I think this should be stored in its own MongoDB collection via Radiks associated with the user.

Implementation could be - every time the user signs in, his/her location is updated (or created if it is the user's first time logging in).

## Motivation

Down the line, we will likely add functionality to deter users from certain locations or notify them if they are in a high-risk area. Additionally, this information can be collected and analyzed.

## Describe alternatives you've considered

An alternative could be to just store the user's zip code, address, etc as a one-time database update on initial sign in, but this may not provide the level of granularity we want.

**Comment by roychowd** [comment]
I can work on this if you haven't started it yet?

**Comment by SomeMoosery** [comment]
Sounds good - I'll assign you now 👍 

There's an example in the master `App.js` as well as in a currently-open PR I wrote for more context if needed.

**Comment by friedger** [comment]
> Additionally, this information can be collected and analyzed.

Privacy law imposes quite a few restrictions on this. This issue should be focusing on the model to serve the user. How this data is shared with the general public should be discussed in a new issue.

**Comment by roychowd** [comment]
@friedger  You are right about that. I think we will have to research up on the model being HIPPA compliant. I'll create another issue regarding this.

**Comment by ngiangre** [comment]
closing and the discussion will continue in #136
