### ISSUE TITLE
Education view for V1 MVP

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#121]
## Summary
We need a design for the Education MVP view.
During meeting we discussed something like a tinder-style card that people can quiz themselves on coronavirus information.

**Overview:**
"Tinder is not around. So, swipe for your health".

A view like Tinder, instead of people its facts.
Swipe left for false
Swipe right for true

The information will come from World Health Organization and CDC. 
For each card, we can place the source under the question. 

## Motivation
**Why are we doing this?**
Based on thoughts from @akilhylton in a prior meeting, education should be byte-sized and engaging.

**What use cases does it support?** 
Supports goal of V1 education. We need engagement to have any success. We will also need metrics to see if there is any engagement going on as a KPI (key performance indicator).

**What is the expected outcome?**
High engagement and the probability that people are reading information. 
We will get score data to measure engagement and knowledge as a proxy. 
This will inform the effectiveness of our development during future sprints.

This information along with possible geolocation can be KPIs to measure "success".

## Describe alternatives you've considered
Please suggest alternatives if available.
Comment in this issue.

## Additional context
None.

**Comment by BrianHHough** [comment]
![CORONATRACKER UI - Education (Fact Mode)](https://user-images.githubusercontent.com/56947075/77218205-44b2e180-6aff-11ea-9692-a423249a1fe9.png)
![CORONATRACKER UI - Education (Quiz Mode) copy](https://user-images.githubusercontent.com/56947075/77218207-44b2e180-6aff-11ea-9125-31c4ba626146.png)
![CORONATRACKER UI - Education (Quiz Mode)](https://user-images.githubusercontent.com/56947075/77218208-454b7800-6aff-11ea-825a-edc307839836.png)

**Comment by BrianHHough** [comment]
I'll add these to github as a commit but feel free to add thoughts there or in in discord too!

**Comment by tesla809** [comment]
BEAUTIFUL! The magnificent @BrianHHough strikes again! Impressive work!

**Comment by tesla809** [comment]
please add to this folder:
https://github.com/COVID-19-electronic-health-system/Corona-tracker/tree/master/design/wireframes/v1-final-MVP
