### ISSUE TITLE
Problem with Prettier 

### ISSUE THREAD

**Issue by AdhamAH** [COVID-19-electronic-health-system/Corona-tracker#127]
After the last pull I am getting an error that there is a problem with prettier configuration `["INFO" - 7:39:20 PM] Extension Name: "prettier-vscode".
["INFO" - 7:39:20 PM] Extension Version: "3.20.0".
["INFO" - 7:39:20 PM] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 7:39:20 PM] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
["INFO" - 7:39:30 PM] Formatting /Users/adham/Work/corona/orginal/Corona-tracker/client/src/components/Table.js
["ERROR" - 7:39:30 PM] Invalid prettier configuration file detected.
["ERROR" - 7:39:30 PM] Cannot find module '@blockstack/prettier-config' from '/Users/adham/Work/corona/orginal/Corona-tracker/client'
Error: Cannot find module '@blockstack/prettier-config' from '/Users/adham/Work/corona/orginal/Corona-tracker/client'
	at Function.sync (/Users/adham/.vscode/extensions/esbenp.prettier-vscode-3.20.0/node_modules/prettier/index.js:15946:13)
	at Object.transform (/Users/adham/.vscode/extensions/esbenp.prettier-vscode-3.20.0/node_modules/prettier/index.js:22820:36)
	at /Users/adham/.vscode/extensions/esbenp.prettier-vscode-3.20.0/node_modules/prettier/third-party.js:4550:32
	at async Promise.all (index 0)
["INFO" - 7:40:19 PM] Formatting /Users/adham/Work/corona/orginal/Corona-tracker/client/src/components/Table.js
["ERROR" - 7:40:19 PM] Invalid prettier configuration file detected.
["ERROR" - 7:40:19 PM] Cannot find module '@blockstack/prettier-config' from '/Users/adham/Work/corona/orginal/Corona-tracker/client'
Error: Cannot find module '@blockstack/prettier-config' from '/Users/adham/Work/corona/orginal/Corona-tracker/client'
	at Function.sync (/Users/adham/.vscode/extensions/esbenp.prettier-vscode-3.20.0/node_modules/prettier/index.js:15946:13)
	at Object.transform (/Users/adham/.vscode/extensions/esbenp.prettier-vscode-3.20.0/node_modules/prettier/index.js:22820:36)
	at /Users/adham/.vscode/extensions/esbenp.prettier-vscode-3.20.0/node_modules/prettier/third-party.js:4550:32
	at async Promise.all (index 0)
`

**Comment by tesla809** [comment]
Did you try a `yarn install`

It seems that you are missing some packages:
Error: Cannot find module `'@blockstack/prettier-config'`'

if `yarn install` doesn't work, then try `yarn add @blockstack/prettier-config`

**Comment by friedger** [comment]
There is a duplicated `devDependency` entry, my fault, sorry!
