### ISSUE TITLE
Add hosting of QA frontend  - CI

### ISSUE THREAD

**Issue by friedger** [COVID-19-electronic-health-system/Corona-tracker#128]
The master branch should be deployed somewhere and connected to a second QA radiks server so that there is a check that thinks like #125 does not happen generally.

Note, that a radiks server can only server one domain names (localhost:3000, localhost:3001, 127.0.0.1:3000 are all different)

**Comment by SomeMoosery** [comment]
You're right, definitely a good call! I'll start implementing this in just a bit - once all the frontend components are shipped so we have a workable V1 ready to go 👍

**Comment by SomeMoosery** [comment]
Closing - we can and should open a new issue if we re-integrate Radiks
