### ISSUE TITLE
DS_Store files in main project folder and server folder

### ISSUE THREAD

**Issue by starving-geek** [COVID-19-electronic-health-system/Corona-tracker#134]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

I use a mac and in the macOS filesystem .DS_Store files are automatically generated inside a folder. 
### Steps to Reproduce
1. On a mac open a terminal application like (the default terminal or iterm) 
2. Navigate to where Corona tracker is kept in your computer in the terminal
3. Type `git status` and press enter (the DS_Store file shows up as a modified file)

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by AdhamAH** [comment]
Oh thanks! I just noticed in my pull request! sorry about that!

**Comment by friedger** [comment]
add it to .gitignore

**Comment by SomeMoosery** [comment]
We can close this, added to .gitignore in #135
