### ISSUE TITLE
[Education]: Fact / Quiz Interactive Mode 3.22.20

### ISSUE THREAD

**Issue by awu556** [COVID-19-electronic-health-system/Corona-tracker#137]
See wireframe ![Fact / Quiz Screen](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/design/wireframes/v1-final-MVP/CORONATRACKER%20UI%20-%20Education%20(Fact%20Mode).png)

- [x] Component 1: Upfront logo + text-based logo

- [x] Component 2: Two-button
Left: “Fact Mode” -- make red
Right: “Quiz Mode” -- make blank

- [x] Component 3: Instructions
Left: “Fact Mode” -- make red
Right: “Quiz Mode” -- make blank

- [x] Component 4: Flash Cards
“Flash card” like visualization with cards “stacked on top of one another (maybe make it look like there’s 3-4 with the top one being locked in place once you swipe the top one away)
The card has a few elements
https://github.com/oliviertassinari/react-swipeable-views

Main goal to gameify education

**Comment by johnemurphy1** [comment]
Adding these rough drafts here for the fact/quiz format button
https://github.com/johnemurphy1/Corona-tracker/blob/master/EducationTwoButton.css
https://github.com/johnemurphy1/Corona-tracker/blob/master/EducationTwoButton.js

**Comment by johnemurphy1** [comment]
ok, i'm not going to do a PR on the fact/quiz button. latest version that @Tanvez posted has it working...

**Comment by awu556** [comment]
Excellent work the both of you! We couldn't have reached V1 without your help.
