### ISSUE TITLE
[Homepage Dashboard]: Navbar, Layout Formatting for Diagnostic Container 3.22.20

### ISSUE THREAD

**Issue by awu556** [COVID-19-electronic-health-system/Corona-tracker#139]
Component 1: Upfront welcome

- [x] Logo to the left + text-logo to the right all on one 
- [x] Good morning, { firstName }
- [x] Today is, { dayOfWeek, month #, year 
- [x] Small black horizontal bar
- [x] Prompt that reads, either: 
         - “Let’s log your health for today” (if empty)
         - “Great job logging  your health today (if fulfilled)
         - Only shows if you have yet to log it, maybe say something like “Great job logging your health      for today!”

**Comment by AdhamAH** [comment]
I just made a pull request to the first parts and transferred them to material-ui. The prompt part might not be able to do it, will see if someone can help
