### ISSUE TITLE
Create Calendar component as per mock up in design directory

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#14]
**Task**
Use the mockup in the design directory to create a separate component for the calendar.

**What done looks like**
We have a Calendar.js component in /components.
We have a .css file to style the Calendar.js component in /css.

**Design considerations**
We have decided to use regular CSS files to keep things simple for now. This allows for more contributors and less time to upskill to contribute. 

Once MVP is done the team can discuss if we want to transition it to styled-components or something like CSS modules. 

**Folder paths**
CSS is located in /client/src/css
Components are located in /client/src/components

Style guide for CSS files:

**Naming convention:**
Component -> Calendar.js
CSS file -> Calendar.css

**To avoid naming collisions:**
prefix class names with the name of component and link with kebab case.
Class name -> .Calendar-header { ... }

**How to handle state:**
If you can use redux, use it. 
Create action and reducer with an appropriate name.

**testing**
No need to worry about testing for now. 
If you choose to add tests, please place in client/src/tests

**Comment by tesla809** [comment]
@akilhylton create Calendar.js and test using react-calendar@3.0.0. 

Will import into App.js and style up.

**Comment by pavel-ilin** [comment]
I'm currently working on this issue.
