### ISSUE TITLE
[Health Log]: Symptom Tracking Survey - Disclaimer

### ISSUE THREAD

**Issue by awu556** [COVID-19-electronic-health-system/Corona-tracker#140]
- [x] Component 1: Pop-up text box that asks you to agree that this isn’t medical advice and language modeled after the CDC app. Paraphrased below:
_CoronaTracker is designed to help you track your health status and make determinations on seeking appropriate medical care. The CoronaTracker application is not intended to be used or viewed as diagnosis or treatment of disease or other symptoms, including but not limited to COVID-19 or others.

This project was made possible through the help of 13 contributors to this open-source project and a community of 100+ volunteers. This application is enabled upon Blockstack, a decentralized computing network and app ecosystem that puts users in control of their identity and data, but this does not imply an endorsement of this, or any, particular service, product or enterprise._

CDC language for reference
![Disclaimer](https://user-images.githubusercontent.com/49773123/77258397-c2d2cd80-6c50-11ea-975d-48dade1c2588.png)

Wireframe for reference
![CTdisclaimer](https://user-images.githubusercontent.com/49773123/77364559-f7b35300-6d2a-11ea-9668-b114763b1030.png)

**Comment by SomeMoosery** [comment]
This was fixed by #185 - can add more detail in a new issue if needed
