### ISSUE TITLE
Need for project/repository rename

### ISSUE THREAD

**Issue by ngiangre** [COVID-19-electronic-health-system/Corona-tracker#143]
Based on extensive conversations and the features being built for our MVP and later versions, having the name Corona-tracker for the application is now sort of a misnomer.

We are no longer tracking but we are educating users who can log their journey through this pandemic with or without infection. 

Her's me rambling for words on discord:

so we're in a crisis
of covid infection and possible disease
it affects everyone
who are now anxious
may be sick
may not be
we're educating
we're informing
we're charting wellbeing and health
this is like a daily or longitudinal calendar
CovidAndMe?
nah
something directed towards the user
that helps the user

Any ideas for a change in the application name please post here!

**Comment by SomeMoosery** [comment]
Good point! I've been telling people the name of what I'm working on, and am almost always met with "wait... I thought you were called corona TRACKER?" after I finish the explanation lol.

I'll brainstorm some names, maybe ask some of my PR/marketing friends as well :)

**Comment by ngiangre** [comment]
you're the best! Per @tesla809 we can hold off repo renaming just because of technical implications like git commits and what not.

**Comment by ngiangre** [comment]
Nothing with "MyCovid"

**Comment by SomeMoosery** [comment]
Going to close this as we've got a record of it and it's on the action plan
