### ISSUE TITLE
Create NavBar Component

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#15]
Task
Use the mockup in the design directory to create a separate component for the NavBar.
In the design directory its called Tab Bar.

What done looks like
We have a NavBar.js component in /components.
We have a NavBar.css file to style the NavBar.js component in /css.

Design considerations
We have decided to use regular CSS files to keep things simple for now. This allows for more contributors and less time to upskill to contribute.

Once MVP is done the team can discuss if we want to transition it to styled-components or something like CSS modules.

Folder paths
CSS is located in /client/src/css
Components are located in /client/src/components

Style guide for CSS files:

Naming convention:
Component -> NavBar.js
CSS file -> NavBar.css

To avoid naming collisions:
prefix class names with the name of component and link with kebab case.
Class name -> .NavBar-header { ... }

How to handle state:
If you can use redux, use it.
Create action and reducer with an appropriate name.

testing
No need to worry about testing for now.
If you choose to add tests, please place in client/src/tests

**Comment by jchen42703** [comment]
I want to give this a go. It won't be completely done until all of the other views are made.

**Comment by tesla809** [comment]
@jchen42703 Try giving it a go. @dinadeljanin is working on it now. 

I will create an issue for creating the login component which you can create separately. Then we can import it.

**Comment by tesla809** [comment]
Wooohooo!
