### ISSUE TITLE
Store static images in S3

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#153]
## Summary

Moving forward, we need to store our images somewhere that's not in this GitHub repo.

## Motivation

A deployed app shouldn't rely on local file structure to maintain static images. Plus, the more we add, the larger this GitHub repo gets - it's already taking me nearly a minute to clone.

## Describe alternatives you've considered

No alternatives, just a next step to a functioning production application

## Additional context

N/A

**Comment by whoabuddy** [comment]
I felt this first-hand today trying to clone from a satellite internet connection where I've exceeded my cap. It's pretty much the same as dial-up at this point, and I've been at 33% for at least 10min now stuck between objects 621-660. (It also finished as I was typing up this issue... so c'est la vie.)

While this is definitely an extreme, I just wanted to vote that I support this idea, and also want to know if you have considered git-lfs storage? I have not used it but came across it while looking through the Blockstack repos at one point.

https://git-lfs.github.com/spec/v1

https://www.youtube.com/watch?v=uLR1RNqJ1Mw

**Comment by SomeMoosery** [comment]
Oh wow! I hadn't heard of Git LFS before. I'll definitely take a look at this! 

And yeah... the more we add the heavier this repo gets. I think at the very least for the short-term, we could take a lot of the wireframes out of this repo.

**Comment by SomeMoosery** [comment]
This has been finished up
