### ISSUE TITLE
Daily log

### ISSUE THREAD

**Issue by ngiangre** [COVID-19-electronic-health-system/Corona-tracker#157]
## Summary

Users will be going through a tumultuous journey with social distancing and isolation. This will have tremendous impact on our behavior and overall well-being in addition to physical health consequences of coronavirus infection. Allowing users to have a free text platform to log in when they choose, this will give them perspective and reflection on their overall physical and nonphysical wellbeing. 

## Motivation

Like in a diary, users can keep their digests on their mood, health, and wellbeing during this journey. Reflection on past entries can give them needed perspective and understanding of changes in their life and ways to cope. This can result in positive outcomes in the future.

What we can further provide them would be giving feedback to them based on their entries if they choose to share them. On the analytics side, we can use rule association and NLP techniques to analyze entries and offer sentiment analysis or population trends to give them a sense of wellbeing status and change over time as well as compared to the overall population. 

## Describe alternatives you've considered

Alternative to a diary entry could be short answer text boxes for certain entries such as for physical symptoms, stress, and others. 

## Additional context

https://twitter.com/MarkSendak/status/1241953091718729730?s=20

**Comment by tesla809** [comment]
I LOVE it! It's great that you know how to do this and know that other researchers would want this!

**Comment by SomeMoosery** [comment]
Closing as we'll write out scoped issues for this 👍
