### ISSUE TITLE
Create Diagnostic Container Component

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#16]
**Task**
Use the mockup in the design directory to create a Diagnostic container component called DiagnosticContainer.js

This is the component that is below the Calendar component in design/wireframes/CORONATRACKER UI - #1.png

**It will hold four sub-components:**
1) The chart to track temperature over time -> Chart.js
2) Average Temperature display -> Temperature.js
3) Toggle between symptoms and temperature -> ToggleInfo.js
4) Symptoms component (needs clarification) -> Symptoms.js

In the design directory, it's above the Tab Bar.

**What done looks like**
We have a Diagnostic.js component in /components.
We have a Diagnostic.css file to style the Diagnostic.js component in /css.

**Design considerations**
We have decided to use regular CSS files to keep things simple for now. This allows for more contributors and less time to upskill to contribute.

Once MVP is done the team can discuss if we want to transition it to styled-components or something like CSS modules.

**Folder paths**
CSS is located in /client/src/css
Components are located in /client/src/components

**Style guide for CSS files:**
Naming convention:
Component -> Diagnostic.js
CSS file -> Diagnostic.css

**To avoid naming collisions:**
prefix class names with the name of component and link with kebab case.
Class name -> .Diagnostic-header { ... }

**How to handle state:**
If you can use redux, use it.
Create action and reducer with an appropriate name.

**Testing**
No need to worry about testing for now.
If you choose to add tests, please place in client/src/tests

**Comment by roychowd** [comment]
@tesla809  thanks for redirecting me! I'll get on it.

**Comment by tesla809** [comment]
@pavel-ilin is working on the sub-component for this. See #54.

**Comment by johnemurphy1** [comment]
Hi, looks like Pavel has the Chart.js sub-component in hand. I'll tackle the temp.js and toggle.js sub-components.

**Comment by dinadeljanin** [comment]
For the temperature section
<img width="744" alt="Screen Shot 2020-03-18 at 18 48 23" src="https://user-images.githubusercontent.com/32048693/77014593-0c69a280-6949-11ea-9314-13e012a8fc5f.png">

I was thinking that it would be awesome to increase the width of the chart,  and we can move the "Average Temperature" to sit either above or beneath the temperature itself.

**Comment by SomeMoosery** [comment]
I'll work on simply filling the full screen with this component as well as better positioning the "sign out" button
