### ISSUE TITLE
Implement Modular Questions

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#161]
## Summary

As it stands for V1, we've done some great work in laying out the scaffolding for building a more cohesive and dynamic app. One of the key features of the symptom-tracking portion of the app are the questions. These questions should be modular, and we should be able to seamlessly remove questions within `SymptomsTracker.js` without having to hardcode questions.

As it stands now, [Pavel's PR](https://github.com/COVID-19-electronic-health-system/Corona-tracker/pull/147) does a great job introducing `SymptomsTracker.js` and [Alina's PR](https://github.com/COVID-19-electronic-health-system/Corona-tracker/pull/149) does a great job of outlining how to lay out a modular component.

## Motivation

A future state is that we have a question bank of a few dozen questions, which rotate for each user whenever they take the quiz. Therefore, we want the ability to easily render questions without having to hardcode as much as possible.

### Future State Idea
- questions are stored in some database
- when building `SymptomsTracker`, we specify which 2, 5, 10, etc questions we want to ask the user this time
- we pull these questions from the database, and create modular `CheckButtonQuestion`, `SliderQuestion`, etc components with the questions pulled from the database, adding them within `SymptomsTracker`

## Describe alternatives you've considered

I feel that this is the most elegant solution, with as minimal hardcoding as possible. The only other alternative I can imagine is creating dozens of individual components for each question, which seems a bit redundant.

**Comment by ngiangre** [comment]
#160 is similar - another component!

**Comment by ngiangre** [comment]
Add human body indication/symptom component #160


Summary
There are many reports coming out on new symptoms and conditions of viral infection and the disease. We can't hard code everything, we need to adapt and let the user tell how what and how they feel physically and nonphysically.

Motivation
Many reports coming out about new symptoms conditions. We want to help the user track their progress for what they report.

Describe alternatives you've considered
text boxes of Other. Lame! lol

Additional context
doctors and researchers at columbia keep coming up with new things to look out for. Keeping a longitudinal record/log is the KEY DIFFERENTIATOR!!

**Comment by SomeMoosery** [comment]
This can be closed as we've captured context and will look to break out modularizing issues going forward
