### ISSUE TITLE
Extract private route component

### ISSUE THREAD

**Issue by friedger** [COVID-19-electronic-health-system/Corona-tracker#164]
## Summary
* Move redirect to Login into a `PrivateRoute` functional component
* Replace Route with PrivateRoute for `log`, `symptomsurvey`, `healthlog`, `settings`

## Motivation
This refactoring make the routing more readable.

**Comment by fallon7284** [comment]
I'm working on this.

**Comment by fallon7284** [comment]
I'm curious to know whether userSession will ever be stored in the Redux store.  If it was in the store I could just connect the PrivateRoute component so we don't have to pass the userSession to each PrivateRoute.

**Comment by AdhamAH** [comment]
Thanks for working on it. @pavel-ilin you worked in Redux the most if I am not wrong. Can you maybe answer Brendan

**Comment by fallon7284** [comment]
I'm just going to pass it as props for now to keep the PR narrow and it will be easy enough to change later.

**Comment by SomeMoosery** [comment]
Which parts of `userSession` do you need to handle? I may not have the full scope of this issue, but would it be possible to just store the parts of `userSession` you need in Redux store? Or utilize the Radiks API to get `userSession` data wherever needed?

**Comment by liadove** [comment]
@fallon7284 did you solve the issue with radiks?

**Comment by fallon7284** [comment]
No I still have an issue with Radiks, but it's definitely a separate issue and I'm going to PR this, just hoping someone can point me in the direction of the PR template.  The link in the readme is dead.

**Comment by SomeMoosery** [comment]
Sorry about that @fallon7284 I'll get that fixed tonight. [Here's the link](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/.github/ISSUE_TEMPLATE/pull_request_template.md) to the PR template!
