### ISSUE TITLE
Combining SymptomTracker component with CheckboxButton and/or SingleCheckboxButton

### ISSUE THREAD

**Issue by JWaltuch** [COVID-19-electronic-health-system/Corona-tracker#166]
## Summary

- Adding checkbox components into Symptom Tracker component.
- Removing unnecessary, duplicate, or redundant code in related components to allow these to mesh together seamlessly

## Motivation

Some questions are redundant/hard-coded and no longer necessary.

**Comment by awu556** [comment]
Awesome work Jenna!
