### ISSUE TITLE
PR package for Wachsman- World's largest PR agency

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#168]
## Summary
Spoke with rep from Wachsman today, courtesy of Shannon from Blockstack. 
We will need:
1) any briefing information, like a formal project summary
2) updated website: see [coronatracker.me](https://coronatracker.me)

@BrianHHough suggested that we will need a PR/Media package. 
That would include:
1) create social media handles:
   - twitter
   - anywhere else ?
2) a LinkedIn page?
3) anything else?

Any thoughts on what to add? Please comment in issues.

## Motivation
Why are we doing this? 
This will get the project's name out, which will drive users to use the application.

What use cases does it support? 
It supports gaining users for the site. 

What is the expected outcome?
We will gain users, possible more devs, and enter users into our marketing funnel for user acquisition.

## Describe alternatives you've considered
1) Reach out to our network connections on Linkedin for promotion and usage.

## Additional context
None.

**Comment by lukelin1991** [comment]
social media: twitter, LinkedIn, FB, instagram? and/or patreon? (another possible option)
we can utilize the website that was made for us the other day, and add to it? and/or purchase an official domain name to load our www.____________.com <-- and get a SSL cert if we've decided on a domain and start inviting people to test (once v1 product is done), whether its from our facebook/insta friends list etc. as well as optimizing via SEO.

**Comment by tesla809** [comment]
Great ideas @lukelin1991 !

**Comment by Afrogrrrl** [comment]
Maybe we could come up with a template to share on our respective social medias (ie a description we all agree on with a link to v1). if everyone announces the completion of v1 on their linkedins, twitters, etc simultaneously, it would reach a lot of people

**Comment by tesla809** [comment]
Brilliant Idea @Afrogrrrl !

**Comment by Bellex0** [comment]
Put the word out and advertise the app on different Slack channels we are all a part of.

**Comment by tesla809** [comment]
Brilliant point @Bellex0 ! Should we create a default template we can all use?

**Comment by ngiangre** [comment]
adding to @Afrogrrrl we should also make the sheet include which (highly influential) people we'll contact about the app, using a blanket email response that everyone can use. Thought of originally by Jenna. 

We must use the power of open source to our advantage - get users, get feedback, have others contribute, serve users more, rinse and repeat

**Comment by nathanboone** [comment]
Hey guys - This is really exciting! I'd love to frame the story as - "_Coronatracker is an open-source project to combat the COVID-19 pandemic through education and awareness created by the NY Health Artificial Intelligence community, in partnership with contributors from universities and hospitals throughout the U.S."  So, the organization is NYHAIS and the product is Coronatracker.

1. **Domain Name**: I've purchased [Coronatracker.me](url) - The .com/org/net's were all taken already :( 

2. **Social Media Push**: I agree, having a set post that we can share to our groups is vital!
    a. LinkedIn
      i. I think we should update the NYHAIS page tonight, and potentially consider adding ourselves as "employees" - for instance I could put "Marketing Communications Contributor"
     ii. Let's plan to write an awesome post, linking to our website, and potentially mentioning some of us too. Then, we can all share it to amplify it's reach?

Any thoughts?

**Comment by ngiangre** [comment]
yes yes YESSSS

thank you for doing this.

I agree with the employees idea - I could be analytics and data model contributor

I can help you draft the post when you want

**Comment by AdhamAH** [comment]
I don't know in later on stage maybe we can also look into ProdactHunt

**Comment by SomeMoosery** [comment]
Would we be able to document these changes in a Google Doc and then close this issue? Just due to this having no actionable items, we should clear up the backlog a bit 👍

**Comment by awu556** [comment]
I consolidated the entire conversation in this Google Doc:
https://docs.google.com/document/d/10CzZNNro4N6qbuKiaA_vwMyMyGzMuTZT5dGTwYOCBZc/edit?usp=sharing

I'll also post this in #marketing-communications
