### ISSUE TITLE
Occasional 409 Bug on Login

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#180]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Occasionally, when I go to log in to the app, I get a 409 error, caused by what I believe are two concurrent requests to Gaia. I'm not sure where this is coming from, especially as it's an intermittent error.

<img width="1378" alt="Screen Shot 2020-03-23 at 9 20 39 PM" src="https://user-images.githubusercontent.com/15767602/77378434-50dfae80-6d4c-11ea-9b63-bf9101bf90c9.png">

### Steps to Reproduce

1. clone repo
2. `cd client && yarn install && yarn run start`
3. attempt to log in

**Expected behavior:**

User is directed to `/`

**Actual behavior:**

The site errors out

**Reproduces how often:**

Infrequently

**Comment by friedger** [comment]
I think we do call User.createWithCurrentUser too often.

**Comment by SomeMoosery** [comment]
Closing as this is being addressed by Blockstack [here](https://github.com/blockstack/ux/issues/300)
