### ISSUE TITLE
GitHub Apps/Actions for Security 

### ISSUE THREAD

**Issue by suhacker1** [COVID-19-electronic-health-system/Corona-tracker#182]
I believe the first step to securing this software is to add a system to automatically alert us of major vulnerabilities within the software and its dependencies. There exist a fair number of GitHub apps and actions that do this. The four most useful ones seem to be: 

1. [WhiteSource Bolt](https://github.com/marketplace/whitesource-bolt)
2. [LGTM](https://github.com/marketplace/lgtm)
3. [SonarCloud Scan](https://github.com/marketplace/actions/sonarcloud-scan)
4. [Snyk](https://github.com/marketplace/snyk)

I'm still trying to determine which one would be most optimal for this project. It might also be necessary for us to use multiple. Please let me know if you have any preferences or ideas. 

## Summary

Adding GitHub apps and actions for security 

## Motivation

This will increase the security of our app. 

## Describe alternatives you've considered

There are many more GitHub actions and apps that suit this purpose. I chose four that were verified by GitHub and popular among other open-source organizations. 

## Additional Context 
Each new app or action should be a separate PR.

**Comment by tesla809** [comment]
Great Idea @suhacker1 !!!

**Comment by suhacker1** [comment]
I tested the different apps and actions on my own fork. The clear winners were LGTM and SonarCloud Scan. LGTM found 1 error, 3 warnings, and 11 recommendations. SonarCloud Scan found 1 bug, 5 security "hotspots", and 41 "code smells". In terms of usability, LGTM was much easier to analyze and configure. SonarCloud Scan required a more involved GitHub workflow setup that included creating GitHub and Sonar tokens. 

Continuous integration would require someone with collaborator access to enable the apps onto the repository. For LGTM, I believe all that is needed is to install the app. After that, we can utilize the LGTM website for pushing alerts to pull requests. For SonarCloud Scan, I'd be able to add the workflow files if a collaborator enables access. 

I could also run the LGTM and SonarCloud Scans on my fork and merely push any bugs and vulnerabilities as issues in the repo.

**Comment by SomeMoosery** [comment]
As per other Issue, these have all been written down and scoped issues for them are coming shortly. This is greatly appreciated and all security measures will be attributed to your help 👍
