### ISSUE TITLE
Make new user onboarding component 

### ISSUE THREAD

**Issue by AdhamAH** [COVID-19-electronic-health-system/Corona-tracker#187]
## Summary

Creat new user onboarding component as per [the wireframe](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/design/wireframes/FINAL-V1-03.20/%233%20-%20New%20user%20onboarding.png)

## Motivation

This needs to be done as part of the plan for V2 as mentioned [in the product roadmap](https://docs.google.com/document/d/1W8QviIhwF9HDhCH4ww5dj97-ui6ouiVh6fGsNUCxj4I/edit#)

**Comment by fallon7284** [comment]
Is anyone working on this? It's unclear, it's marked in-progress [in the product roadmap](https://docs.google.com/document/d/1W8QviIhwF9HDhCH4ww5dj97-ui6ouiVh6fGsNUCxj4I/edit#).  If nobody is working on it I'll take it.

**Comment by SomeMoosery** [comment]
All you @fallon7284 - we should stick to GitHub Issues as the source of truth for what's being worked on

**Comment by AdhamAH** [comment]
@fallon7284 thanks for working on it! Please try to keep in mind using Material-UI styling in doing this but use the jsx normal input tag.

**Comment by fallon7284** [comment]
Well thats going to take some reworking, it's nearly finished but I've done it all with Material-UI components
