### ISSUE TITLE
Redirect to CDC  on disagree

### ISSUE THREAD

**Issue by AdhamAH** [COVID-19-electronic-health-system/Corona-tracker#188]
**This was not meant to be a question to chose between CDC and WHO. This can be done later depending on the locality of the user. Which I think is @SomeMoosery expertise from server-side. If not possible then another dialogue to choose where. Now the main initial target is the US, later we may add also RIMV (for the Dutch 😂)**
## Idea 

When a user disagrees to the Disclaimer [issue#140](https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/140), the app will redirect to CDC or WHO page 

## Motivation 
Rather than just log the user out we redirect him to another source of info. In the end, we need users to know more about the virus and the user might find it a good thing and come back to use it 

## How to do it
There are many ways but as we are using react-router, we can use Redirect in a simple conditional statement

**Comment by friedger** [comment]
As we aim for global reach, redirecting to WHO would be most suitable.

**Comment by Afrogrrrl** [comment]
^ seconded on redirecting to WHO. I actually think it should log someone out and redirect them to WHO

**Comment by AdhamAH** [comment]
> As we aim for global reach, redirecting to WHO would be most suitable.

My bad, I didn't ask the right question
  

> ^ seconded on redirecting to WHO. I actually think it should log someone out and redirect them to WHO
thanks for pointing out the logout part.

**Comment by AdhamAH** [comment]
I was waiting for the changes to be made to the disclaimer. Now it looks like it is not needed anymore

**Comment by SomeMoosery** [comment]
Sounds good. We can always open another ticket later if we decide to do something differently :)
