### ISSUE TITLE
Add constant components in top-level component

### ISSUE THREAD

**Issue by AdhamAH** [COVID-19-electronic-health-system/Corona-tracker#189]
## Idea:
To make a united layout throughout the app.

1. Include top-level components like navbar, constant images like logos in a top-level component such as `Layout.js`. Remove them from DiagnosticContainer component
2. Use Material-UI theming
3. As per @friedger and @AdhamAH suggestions, keep constant components in Layout.js’ and React providers in ‘App.js’ 
 
## Motivation:

1.  Keep consistency in the styling of the app
2. Make it easier for anyone new coming on board to follow the same flow
3. Start implementing Material-UI

**Comment by liadove** [comment]
What should be inside DiagnosticContainer component?

**Comment by Afrogrrrl** [comment]
I agree with what was mentioned last night about putting navbar at the highest level possible so it's consistently available throughout the app. Perhaps we can convert DiagnosticContainer into this layout component?

**Comment by AdhamAH** [comment]
The login functionality and showing 

> What should be inside DiagnosticContainer component?

it can be as @Afrogrrrl said, will see and update

**Comment by SomeMoosery** [comment]
I think anything top-level like this could go within `App.js`, unless that's bad practice, not too sure.

I was thinking `DiagnosticContainer` would be the wrapper component for the Health Log, containing both the overview and also weekly view. I don't know if we should repurpose this.

**Comment by AdhamAH** [comment]
Agree. That would be the best

**Comment by friedger** [comment]
I think it is good practise to put all the react providers in `App.js` and the constant components into something like `Layout.js`, then the components for all routes can make use of `Layout` as top level component.

**Comment by JWaltuch** [comment]
I can take a crack at this. I might have some time later this afternoon.

**Comment by SomeMoosery** [comment]
Sounds good @JWaltuch !

**Comment by AdhamAH** [comment]
O am sorry I should assigned to myself, @JWaltuch , talk to me. I was working on it

**Comment by SomeMoosery** [comment]
No problem!

I'd say you and @JWaltuch should collaborate / pair up so we don't end up losing any valuable code, but let's try to stick with @JWaltuch creating the PR for this now to keep consistency/clarity 👍

**Comment by JWaltuch** [comment]
@AdhamAH Let me know where you are at and your thoughts, because I was just about to start it so I don't have any code to contribute yet. I don't know if you'd prefer to collaborate or for me to tackle something else if you are already deep into it.
