### ISSUE TITLE
Education view - cards blocks navbar

### ISSUE THREAD

**Issue by pavel-ilin** [COVID-19-electronic-health-system/Corona-tracker#190]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

View - Education
Fact and quiz cards blocks navbar on the bottom.

Checked for regular screen size and mobile views.

### Steps to Reproduce

1.  Hit /education rout
2. Attempt to click on navbar tabs
3. Select Quiz cards
4. Attempt to click on navbar tabs

**Expected behavior:**

Navbar tabs should be clickable when you in /education view. 
Navbar should be clickable when you select Fact cards
Navbar should be clickable when you select Quiz cards

**Actual behavior:**

Facts cards: Navbar tabs not clickable.
Quiz cards: Navbar tabs not clickable.

**Reproduces how often:**

100% cases

**Comment by liadove** [comment]
@pavel-ilin are you working on it?

**Comment by pavel-ilin** [comment]
> @pavel-ilin are you working on it?

No, I don't
