### ISSUE TITLE
Bug: can't scroll down

### ISSUE THREAD

**Issue by liadove** [COVID-19-electronic-health-system/Corona-tracker#195]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

symptom tracker component isn't scrolling down on Log tab

![image](https://user-images.githubusercontent.com/43704877/77592120-db98e880-6ec7-11ea-8030-05acd811f606.png)

### Steps to Reproduce

1. try to scroll down on Log tab

**Expected behavior:**

Will scroll down to show the whole Symptom tracker component

**Actual behavior:**

Shows just half of the component

**Reproduces how often:**

100%

**Comment by AdhamAH** [comment]
this is because of the navigation. It is fixed in the bottom with position absolute and bottom =0
I think we can try to fix that also or follow the issue mo mentioned
