### ISSUE TITLE
Education tab not rendering component

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#196]
* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

When running the app in QA, navigating to the Education tab does not render anything. This looks to be a problem in the render parameter in the associated `PrivateRoute`.

### Steps to Reproduce

1. Run the application in QA
2. Navigate to education tab

**Expected behavior:**

Education tab loads flashcards as it was before

**Actual behavior:**

Nothing renders

**Reproduces how often:**

100%

**Comment by awu556** [comment]
I can take this one! I just fixed it on my branch.
