### ISSUE TITLE
Make scroll component 

### ISSUE THREAD

**Issue by AdhamAH** [COVID-19-electronic-health-system/Corona-tracker#199]
## Idea
Make a scroll component like in the gif
![scroll](https://user-images.githubusercontent.com/55054963/77600028-e7f06600-6f06-11ea-8a10-fdf544596a3b.gif)

## this already made just need to know if you agree

**Comment by awu556** [comment]
Looks good! I think this solves #195, but does it also scale for the desktop?

**Comment by liadove** [comment]
Looks good!

**Comment by SomeMoosery** [comment]
Yeah definitely something needed! Do you want to take this on @AdhamAH ? When you make a PR for this, just be sure to put "fixes #195" and "fixes #199" so we close both at the same time 👍

**Comment by AdhamAH** [comment]
will do!
