### ISSUE TITLE
Adding a Coronavirus Deaths Forecasting Feature 

### ISSUE THREAD

**Issue by Faustino-Malena** [COVID-19-electronic-health-system/Corona-tracker#201]
After an outline of the perfect data set through the Analytics team 
through information on the number of daily  coronavirus Deaths in the U.S 2020.
The units are a counter and of which are  N observations in different regions.

**Comment by SomeMoosery** [comment]
Closing, perhaps open a new issue with further description in [Coronalytics](https://github.com/COVID-19-electronic-health-system/Coronalytics) but this may be out-of-scope for the time being
