### ISSUE TITLE
Duplicate id's in SingleCheckboxButton.js

### ISSUE THREAD

**Issue by fallon7284** [COVID-19-electronic-health-system/Corona-tracker#203]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

There are multiple components with the same id defined in SingleCheckboxButton.js

### Steps to Reproduce

1. Render Diagnostic container at '/', see error in console.

**Expected behavior:**

id's need to be unique.

**Actual behavior:**

id's are duplicated in TemperatureAutocomplete, MinutesAutocomplete, HoursAutocomplete components defined within SingleCheckboxButton.js

**Reproduces how often:**

100%

### Additional Information

Change id to className, seems like it won't affect styling since I don't see the id used in any css.

**Comment by liadove** [comment]
I'll try to take a look at that!
