### ISSUE TITLE
Split components/.../CheckboxButton.js into multiple files

### ISSUE THREAD

**Issue by fallon7284** [COVID-19-electronic-health-system/Corona-tracker#204]
## Summary

components/survey-view/checkbox-button/CheckboxButton.js exports a react component, but also contains Redux action types, action creators, initial state, and reducers.

Should try to maintain a consistent file structure by moving the Redux code into the src/Redux/actions and src/Redux/reducers.

## Motivation

Maintain consistent file structure

**Comment by Afrogrrrl** [comment]
Would be happy to take this one on!

**Comment by liadove** [comment]
for my understanding useReducer is not the same as Redux. useReducer helps to control inputs in this case. If I understand it right?

**Comment by SomeMoosery** [comment]
Yeah, `userReducer` is separate from Redux, but since for the time being we've decided to move forward with Redux, this story would be more of a refactoring of this code to utilize Redux, right?

**Comment by SomeMoosery** [comment]
And sounds good @Afrogrrrl !

**Comment by fallon7284** [comment]
Absolutely right, I completely misunderstood what was happening in this file.  This is all being done just to handle form inputs within this component.  Mea Culpa.

**Comment by SomeMoosery** [comment]
No problem! It's a great point-out though, this may have gone unnoticed not being in Redux for some time, and we want to rely on it for anything non-trivial 👍 . May be worthwhile to edit the issue to more contextualize refactoring this to use Redux

**Comment by fallon7284** [comment]
I wouldn't even think this gets refactored to Redux, though, now that I understand what it is.  It's holding form state pre-submission.  I don't think you want to use the redux store to hold form state within a single component. 
I think through my misunderstanding I unfortunately created work that didn't need to be done.  I'm not super comfortable editing the issue and would just hope to bring @Afrogrrrl into the conversation since she's working on this now ill-defined task.
Apologies for the mix up.

**Comment by liadove** [comment]
@fallon7284 That's totally fine! I wasn't clear when I wrote it, maybe I should've used regular useState instead? But I thought we can add more symptoms in it, and it would be easier to put it in useReducer. And also it much less code!

**Comment by SomeMoosery** [comment]
Ah, okay, I see what's going on now. Apologies about that. You're right, this is trivial in the sense that we shouldn't be storing like intra-component state in Redux. I think `useReducer` actually maybe was best since it is more likely that `useReducer` is more reusable. 

@Afrogrrrl - would you be willing to take on another issue instead of refactoring this? Apologies for the confusion I caused.

**Comment by Afrogrrrl** [comment]
No problem, I can definitely take on something else

**Comment by SomeMoosery** [comment]
Sounds good - I'll close this issue then.

Agile at it's best!
