### ISSUE TITLE
Disclaimer saving state

### ISSUE THREAD

**Issue by liadove** [COVID-19-electronic-health-system/Corona-tracker#205]
## Summary

Have redux variable for the user answer for disclaimer, which will store values: 'agree', 'not agree' (true, false?). In the future, we'll store it in the database inside the user table. So that way we'll know if the user agreed to the disclaimer.

## Motivation

Why are we doing this? 
We don't want the disclaimer to pop up every time and it won't go away because buttons currently don't work.

What is the expected outcome? 
Disclaimer state will save the user answer and store it redux. And depends on the answer it will send you back or send it to the main tab.

## Describe alternatives you've considered

Have maybe a user profile redux state, that will have a property with a disclaimer answer (initially could be null). Then send it to the disclaimer component and component will change the answer and send to redux, and then to the backend where it will be stored, so the next we won't ask a user to agree or disagree.

**Comment by Afrogrrrl** [comment]
I can take this one on
