### ISSUE TITLE
Symptom Tracker Survey appearance

### ISSUE THREAD

**Issue by liadove** [COVID-19-electronic-health-system/Corona-tracker#208]
## Summary

I was thinking about when the Symptom tracker survey should appear? Should we have a button under the message "Let's log your health for today"? Or/and we can click on a white circle on the calendar (will point on today's day)? Or/and will pop up when you logged in but didn't fill the survey out? 

## Motivation

We want people to submit the survey every day, and visualizing it clearly will help us remind people to do so.

## Describe alternatives you've considered

Under the discussion

**Comment by SomeMoosery** [comment]
I would say this is parallelizable, and a separate issue for all three points you mentioned.
1. Create a button that opens symptom tracker survey
2. Add functionality to click on today's date (highlighted) and open symptom tracker survey
3. Add functionality to display survey on login, if survey hasn't yet been completed for the day

This was a great addition @liadove - great way to break things out. Would you want to write issues for each of these cases? 

This also circles back to a need to finalize what exactly we need for our data model. Particularly in Case 3, we'll need some type of way to check if there exists a survey (observation) already on the given day. Perhaps we can add that as an acceptance criteria to that case.

Just my two cents. Thoughts @everyone?

**Comment by liadove** [comment]
Sure! @SomeMoosery will do this now. I just wanted to confirm it with everybody before creating issues.
You are right about the data model. It would be helpful to know what tables and attributes we're going to have on the backend to build redux :)

**Comment by liadove** [comment]
issues:
https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/212
https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/215
https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/214
