### ISSUE TITLE
Perform unit testing

### ISSUE THREAD

**Issue by njordhov** [COVID-19-electronic-health-system/Corona-tracker#221]
## Summary

Unit testing should catch issues early to avoid breaking master.

## Motivation

Issue #200 reports a bug that caused loading/compiling the app to fail for development. This adds friction and may even turn off new developers. We should catch such issues before they are committed to master, by having processes such as unit testing.

**Comment by SomeMoosery** [comment]
A good note and at this point we are fleshing out a lack of tests and working to create new necessary tests with each new addition now that we have less of a time crunch (although definitely still a significant one, just not strong enough to outweigh testing!)
