### ISSUE TITLE
Create "Subscribe Field/Button for Alpha Testing"

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#224]
## Summary

For the alpha test releasing Friday, one of the milestones is a basic notification service. While we don't necessarily need to decide on the final location of this, we need to present the user with the ability to subscribe to our notifications service.

For the time being, this can be a simple text input field asking for the user's phone number, and a button handling submit. We will worry about the wiring later, as I'm currently working on fleshing out the backend functionality / running it on my local AWS account for alpha testing purposes. 

Down the line, this is where we can finally start managing some of our own backend :) 

## Motivation

After discussing with doctors, as well as product talent, we have decided that having a helpful, not bothersome or useless, notifications system would be a beneficial feature of the app. For the time being, this will send simple, helpful messages, but could be greatly expanded upon later and multiple services could be written out to handle multiple different types of notifications.

## Describe alternatives you've considered

There is no alternative, users need to be able to send us their phone numbers on the frontend.

**Comment by crispinamuriel** [comment]
I'd like to be assigned to this issue, please.

**Comment by SomeMoosery** [comment]
Sounds good!
