### ISSUE TITLE
Connecting Backend with Analytics

### ISSUE THREAD

**Issue by ngiangre** [COVID-19-electronic-health-system/Corona-tracker#225]
## Summary

Evehntually we will be collecting self reported data. That data will be stored in our backend. We need to establish how and when that data can be extracted to derive insights

## Motivation

We neeed to understand who is using the app and their characteristics so we can better serve the user base with tailored development of the application based on reporting.

## Describe alternatives you've considered

None. We can do surveys/focus groups to get feedback on app features. A/B testing will not be feasible for a while or atleast until w gather a larger user base and analytics team.

**Comment by SomeMoosery** [comment]
We'll create a more scoped issue once we launch and are further advanced with Coronalytics 👍
