### ISSUE TITLE
Internal Alpha testing feedback

### ISSUE THREAD

**Issue by ngiangre** [COVID-19-electronic-health-system/Corona-tracker#226]
We put out a survey to receive initial survey of the app on 3/25.

https://docs.google.com/forms/d/1O8cHN4Wowh21K1LPIsBInOLGA4IjaAYfDet5o89rdOc/

Here is the feedback according to these instructions:

**1. Go to the website at http://coronatrackerv1.s3-website-us-east-1.amazonaws.com/**

**2. Press Get started and login**

- 4/14 were not familiar with blockstack, 2/14 were confused by a secret key, and individuals noted they should've known what was needed to create my username before it yelled at me

**3. Once at the home screen, press the education tab**

- I expected something to appear

"Homepage might display username in future? "Hello Username, today is..." Move sign-out button so not touching the top."

"Love the navbar, very stylish and easy to use."

Individuals didn't know where to look

**4. Swipe through the fact cards**

"It was a little difficult to swipe the cards with a laptop touchpad"

"Swiping was too hard why can't I just double click, Or alternatively, can it be more like Quizlet's interface? (Tap for answer, swipe/double-click to change)"

"Yes, It was easy to swipe between cards but hard to swipe on T/F specifically and get points in the quiz. Some of them swiped away and I didn't get the points."

"On web browser it wasn't immediately apparent that I had to swipe. Once I figured that it was easy"

"Took a minute to realize to swipe left and right for true and false"

**5. Once you went through all the cards once, click the quiz tab and swipe through those cards**

"Yes, Once the cards are through, should notify user to go to the quiz (if they'd like)"

"Yes, It wasn't clear that I had to swipe left/right for the quiz. It was hard to swipe because I had to swipe all the way"

**Was the design of the app appealing?**

"It seemed unwelcoming, The color scheme is harsh and I didn't feel like it was very user friendly"

"Not unappealing, but could be better"

"it seemed boring"

Was there any application features that seemed unnecessary or distracting?

"After flipping through all cards the cards re-populate themselves, I was wondering if there should be a notification to take the quiz at that point."

"I'm uncertain as to why the temperature was on the home screen"

"The circle cursor is kind of distracting, no need for that"

**Overall comments:**

The first question on the quiz should be false, not true. Also there's no TODOARROW

The issue with the T/F buttons, if it could be done quickly. Not sure.
While I like the animation of the cards and swiping through them, might be more appealing way to implement that feature. I also think that there might be a better color palette that could be used to make the app more slick and 'modern' looking.

Can users edit their today health log during the day?

Fix the health logging icons! Check the swipe response speed so that it's more streamlined and swipes in real time like your cursor. Provide actual medical advice. Link up actual medical professionals to respond to potential questions users may have

**Comment by SomeMoosery** [comment]
All notes written down, but we should close this as there's not much actionable to do here
