### ISSUE TITLE
Establishing a security process

### ISSUE THREAD

**Issue by suhacker1** [COVID-19-electronic-health-system/Corona-tracker#229]
To manage security vulnerabilities in our code, we should establish a clear security policy that describes our disclosure policy, security update policy, security-related configuration tips, and known security gaps. I think it would be a good idea to allow contributors to raise vulnerabilities as issues, and then create security advisories (which can only be done by users with admin access) for effectiveness. 

## Summary

Add a security policy and workflow.

## Motivation

This will increase the security of our app. 

## Describe alternatives you've considered

We could merely assign security analysis to certain contributors, but it would be more effective to facilitate broader engagement. 

## Additional context

GitHub has written about [how to manage security vulnerabilities.](https://help.github.com/en/github/managing-security-vulnerabilities/managing-security-vulnerabilities-in-your-project)

I'm willing to work on this issue.

**Comment by SomeMoosery** [comment]
I've really appreciated the work you've been doing with regard to researching security measures - I'll reach out tomorrow to discuss further 

I'll assign you to this as well since you said you're willing  👍

**Comment by SomeMoosery** [comment]
We will write out more scoped issue for this coming soon
