### ISSUE TITLE
Create the ToggleInfo.js sub-component for DiagnosticContainer.js

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#23]
**Task**
Use the mockup in the design directory to create a component that toggles between Symptoms.js and Temperature.js, called ToggleInfo.js.

This will be a sub-component of DiagnosticContainer.js as per design/wireframes/CORONATRACKER UI-#17

**What done looks like:**
Add comments to explain code.
We have a ToggleInfo.js component in /components.
We have a ToggleInfo.css file in /css to style the ToggleInfo.js sub-component.

**Design considerations:**
We have decided to use regular CSS files to keep things simple for now. This allows for more contributors and less time to upskill to contribute.

Once MVP is done the team can discuss if we want to transition it to styled-components or something like CSS modules.

**Folder paths**
CSS is located in /client/src/css
Components are located in /client/src/components

**Style guide for CSS files:**
**Naming convention:**
Component -> ToggleInfo.js.
CSS file -> ToggleInfo.css

**To avoid naming collisions:**
prefix class names with the name of component and link with kebab case.
Class name -> .ToggleInfo-header { ... }

**How to handle state:**
If you can use redux, use it.
Create action and reducer with an appropriate name.

**Testing:**
No need to worry about testing for now.
If you choose to add tests, please place in client/src/tests

**Comment by johnemurphy1** [comment]
guys, here's something i've been working on, but not familiar with Redux. So, don't know what needs to be modified to change diagnostic container state from temperature to symptoms. i'll probably need to pair program with someone on adding that. will try to do pull request in next hour https://repl.it/@jm5/CoronaTrackerDiagnosticContainer-toggleinfojs

**Comment by SomeMoosery** [comment]
Is this still being worked on, or does it need to be closed?

**Comment by johnemurphy1** [comment]
Still being worked on. Realistically, I can't get back to it until Friday. At this point, could probably take the code that @Tanvez created for the Facts/Quiz cards with toggle button and just refactor.  If you need it sooner, please reassign.

**Comment by SomeMoosery** [comment]
I'd say keep chugging along with this then! We definitely need it for V2 but not necessarily for the alpha release we want out by Friday 👍

**Comment by Afrogrrrl** [comment]
@johnemurphy1 How is this going? Are you far enough where I could do #334 ?

**Comment by johnemurphy1** [comment]
@SomeMoosery @tesla809 tried rebase. same results. I'm going to clone and create a new branch.

**Comment by johnemurphy1** [comment]
Hey @Afrogrrrl . This is done and PR merged!
