### ISSUE TITLE
Disclaimer should appear on top of all other elements

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#232]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

When the user is greeted with the dialog, that should be the main display on the screen, and everything else should be behind it.

<img width="1387" alt="Screen Shot 2020-03-27 at 1 06 44 AM" src="https://user-images.githubusercontent.com/15767602/77723741-a7a4ec80-6fc7-11ea-9f4e-d110afac8164.png">
<img width="1388" alt="Screen Shot 2020-03-27 at 1 06 36 AM" src="https://user-images.githubusercontent.com/15767602/77723747-aa074680-6fc7-11ea-99a4-7d4dbc1831c6.png">

### Steps to Reproduce

1. Log into the app

**Expected behavior:**

The disclaimer appears top-level, above all other components

**Actual behavior:**

The disclaimer is partially positioned behind buttons, etc

**Reproduces how often:**

100%

**Comment by JWaltuch** [comment]
I can take this :)
