### ISSUE TITLE
Fix validateDOMNesting error

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#238]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

We can't have `<p>` tags inside a `DialogContextText` component in `Disclaimer.js`

Appears for both `<p>` tags.

<img width="470" alt="Screen Shot 2020-03-27 at 12 35 49 PM" src="https://user-images.githubusercontent.com/15767602/77778610-a4d9e400-7027-11ea-9dcf-ef57b41b7a8a.png">

### Steps to Reproduce

1. Log into app and inspect

**Comment by JWaltuch** [comment]
Finished my last issue. I can check out this one :)
