### ISSUE TITLE
Create LoadingScreen.js component Loading Screen view

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#24]
Task
Use the mockup in the design directory to create a Loading Screen View for App called LoadingScreen.js

See: design/wireframes/CORONATRACKER UI-#1.png

It will have the logo in the /design directory.

**What done looks like**
We have a LoadingScreen.js component in /components.
We have a LoadingScreen.css file to style the Diagnostic.js component in /css.

**Design considerations**
We have decided to use regular CSS files to keep things simple for now. This allows for more contributors and less time to upskill to contribute.

Once MVP is done the team can discuss if we want to transition it to styled-components or something like CSS modules.

**Folder paths**
CSS is located in /client/src/css
Components are located in /client/src/components

**Style guide for CSS files:**
Naming convention:
Component ->LoadingScreen.js
CSS file -> LoadingScreen.css

**To avoid naming collisions:**
prefix class names with the name of component and link with kebab case.
Class name -> .LoadingScreen-header { ... }

**How to handle state:**
If you can use redux, use it.
Create action and reducer with an appropriate name.

**Testing**
No need to worry about testing for now.
If you choose to add tests, please place in client/src/tests

**Comment by tesla809** [comment]
@SomeMoosery is loading screen necessary? Would login screen be enough ?

**Comment by SomeMoosery** [comment]
So depending on how we want to do this - I'd say we maybe don't need a full loading page, but we'll need some sort of loading animation or something. Currently, while Blockstack authenticates the user, there's like 1-2 seconds after clicking "sign in" on the Blockstack authentication page where the user is directed back to CoronaTracker's sign-in page before the auth completes and the page changes. This could be confusing for an end-user, so we'll probably want to implement some overlay or animation in [this method](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/ec751b06e6dc92f0e352a1f45df45532adc352ed/client/src/components/App.js#L38) (dealing with logic whiles sign-in is still pending)

**Comment by friedger** [comment]
Depending on the size of the app an initial animation in index.html might be good as well. This issue should be about the animation. A component could be created when needed.
