### ISSUE TITLE
Use react hook for authentication status and Blockstack session

### ISSUE THREAD

**Issue by njordhov** [COVID-19-electronic-health-system/Corona-tracker#244]
### Description

With #216 the authentication status and other functionality from the Blockstack SDK is available in function components through the `useBlockstack()` hook from the [react-blockstack](https://github.com/njordhov/react-blockstack) library, as in:

```javascript
import { useBlockstack } from 'react-blockstack';

function SignOutButton (props) {
  const { authenticated, userSession, signOut } = useBlockstack();
  return ( <button disabled={!authenticated} onClick={signOut}>SignOut</button>)
}
```

This should supersede passing down authentication status through the `authed={authenticated}` prop.

**Comment by Afrogrrrl** [comment]
Just to clarify on what this is asking for, do you want all of the components using `authed={authenticated}` to be changed to use the `useBlockStack()` hook?

**Comment by njordhov** [comment]
> do you want all of the components using authed={authenticated} to be changed to use the useBlockStack() hook?

Yes. Either in one swoop, or updated as they're edited for other reasons. New components should use the hook rather than pass down the values.

**Comment by AdhamAH** [comment]
so do you suggest  using a button component like this:
`import { useBlockstack } from 'react-blockstack'

function Auth () {
    const { signIn, signOut } = useBlockstack()
    return (
        <button disabled={ !signIn && !signOut }
                onClick={ signIn || signOut }>
            { signIn ? "Sign In" : signOut ? "Sign Out" : "..." }
        </button>
    )
}`

**Comment by fallon7284** [comment]
Can I take this?

**Comment by SomeMoosery** [comment]
All you, I'll assign you 👍
