### ISSUE TITLE
change Headache in SymptomsTracker to be mobile size

### ISSUE THREAD

**Issue by AdhamAH** [COVID-19-electronic-health-system/Corona-tracker#251]
## issue 

how originally it looks 

![Screenshot 2020-03-27 at 22 49 42](https://user-images.githubusercontent.com/55054963/77803428-653de700-707d-11ea-88fb-fb730b23491e.png)

to look like:

![Screenshot 2020-03-27 at 22 50 17](https://user-images.githubusercontent.com/55054963/77803459-725ad600-707d-11ea-96b3-1eaf2743c4ce.png)

## Motivation 

To keep consist look

**Comment by SomeMoosery** [comment]
Are you working on this? Or is this good for someone else to pick up?

**Comment by AdhamAH** [comment]
yes, it is done actually. fast change then will make PR and close it in that PR, good?

**Comment by SomeMoosery** [comment]
Yup! Sounds good, just make a PR resolving this and I'll give it a lookover/merge it in 👍
