### ISSUE TITLE
Store survey data in Redux

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#256]
## Summary

- [ ] save submitted observation in Redux after successful database write

**NOTE: we want to only persist data to Redux once we have successfully persisted this data to the database. I'd point to implementing this change in the `submitSurvey()` method of `SymptomsTracker`.**

## Motivation

- Once we persist an observation to the database, we store this data in Redux 
- This eliminates the need for constant expensive database queries throughout other components

## Describe alternatives you've considered

Just constantly reading from the database, which is foolish

**Comment by crispinamuriel** [comment]
Can I try to help with this issue? I'd gladly work with anyone if it needs to be done quickly.

**Comment by SomeMoosery** [comment]
We actually are gonna put this on hold until #237 is done. Apologies I'll update the tags!

**Comment by SomeMoosery** [comment]
I'm going to close this. For the time being, it seems superfluous to store this in Redux - the times we need survey data, we need to pull a specific observation from the database anyway.
