### ISSUE TITLE
Integration of behavioral components: FrontEnd 

### ISSUE THREAD

**Issue by ransing** [COVID-19-electronic-health-system/Corona-tracker#264]
## Summary

This is a follow up from the previous [issue](https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/129). 

## Motivation
The mock application is [here](https://covidmentalhealth.netlify.com/) 
Code [here](https://github.com/Bellex0/covid-mental-health)
Questions [here](https://docs.google.com/spreadsheets/d/1C40mBKCm7-B9WIEEOXPKdfQqVy9mhxZuHEescg2nV-o/edit#gid=0) 
Additional discussion in # health-log on discord 

## Additional context
So far the behavioral section consists of: 
1. Multi step form: The form consists of 8 components. One for each question, confirm, success and stepform. Confirm and success are optional. 
2. Chart: Consists of a chart from ReChart. One component. 

Once we have established where this section will be integrated then we can go ahead and merge the above code. Appreciate any suggestions. 

##Challenges 
- When/where will the user be prompted to enter this section? 
- How to display the chart (landscape on mobile?).
- Would the hover function for chart work on mobile or how will that be displayed? 
- Information on when the previous survey was saved (for the behavioral section) will be saved on the backend. For the current question we wish to display that information for each question. For example, the question will be framed. "In the last < 4 days > have you felt loss of appetite?" OR "Since < last date the survey was completed> have you felt loss of appetite?"

**Comment by AdhamAH** [comment]
From building and styling point of view, that can be integrated into the app. We already have reusable components that can be used with this or need a bit of tweaking. 
But I think the priority now should be to finish the main features (physical health I mean) that already in progress and then we can add upon.
