### ISSUE TITLE
Persist observation to database on survey submission

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#266]
## Goal
We now have a successful survey functionality, and the button click callback wired up properly to handle all data at once. We now want to persist this data to be the backend using Blockstack.

On the submission callback, we want to pass all relevant data into one function that will persist data about the observation into the database.

[This will use Blocktack's Radiks package to create the Observation model and persist it to the database](https://docs.blockstack.org/develop/radiks-models.html)

**NOTE:** we need to include the current date along with answers given.

**Comment by Afrogrrrl** [comment]
@SomeMoosery if you're not working on this I'd like to take a crack at it since I've yet to touch anything related to backend and would like to start learning how to work with blockstack and radiks

**Comment by SomeMoosery** [comment]
I am currently working on this, apologies for not commenting on it - I have a WIP PR out #237 that I've been working closely with @njordhov to complete as a first pass. Feel free to add to the discussion there - it's definitely an open conversation! I'm just trying to glean out the best pattern for interacting with Gaia. Once I do, the backend work will certainly increase.

Apologies there hasn't been much as of yet, there certainly will be plenty more in short notice! With the main application, as well as with the notifications service [here](https://github.com/COVID-19-electronic-health-system/BasicNotificationService)

**Comment by SomeMoosery** [comment]
Closed by #271
