### ISSUE TITLE
Integration of behavioral components: Backend 

### ISSUE THREAD

**Issue by ransing** [COVID-19-electronic-health-system/Corona-tracker#267]
## Summary
For the summary of components/code/demo please refer to #264  

The mock application is [here](https://covidmentalhealth.netlify.com/)
Code [here](https://github.com/Bellex0/covid-mental-health)
Questions [here](https://docs.google.com/spreadsheets/d/1C40mBKCm7-B9WIEEOXPKdfQqVy9mhxZuHEescg2nV-o/edit#gid=0)

## Motivation
Trying to figure out how the fetch (to save the responses) to the backend will work. 
Data to save: The responses from the Multi step form are the following [variables](https://docs.google.com/spreadsheets/d/1C40mBKCm7-B9WIEEOXPKdfQqVy9mhxZuHEescg2nV-o/edit#gid=0)
Total variables to be saved: 6 ( 5 questions and 1 Date.now) for each time the participant logs in a response. 

## Additional context
Once the above is done, we need to fetch the data again to display on the chart but that should not be too bad.

**Comment by SomeMoosery** [comment]
Let's close this as we're saving this to Gaia within our frontend, any backend work will be done in analytics which for now conversation should be moved into the Coronalytics repo
