### ISSUE TITLE
Add redux-logger middleware

### ISSUE THREAD

**Issue by fallon7284** [COVID-19-electronic-health-system/Corona-tracker#268]
## Summary

We should be able to start working on wiring up our React components with Redux soon, and I was digging through what Redux files are present, and realized it was unclear what is functioning and what isn't, which reminded me that someone last night mentioned adding redux-logger which is a fantastic logging middleware for redux that shows how the state of the store changes with every dispatched action.

## Motivation

To bring clarity around the state of our Redux store as we begin to implement Redux and asynchronous actions connecting our front and back ends.

## Describe alternatives you've considered

I considered no alternatives as far as loggers, I have experience with redux-logger and it's great.

**Comment by fallon7284** [comment]
@SomeMoosery @AdhamAH @tesla809 I'd be happy to do this real quick.

**Comment by SomeMoosery** [comment]
That would be awesome, assigning you now
