### ISSUE TITLE
Create login component called Login.js for the Login view

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#27]
**Task**
Use the mockup in the design directory to create a component for the login view called Login.js.

See the following for the design/wireframes/CORONATRACKER UI-#1

**What done looks like:**
1) See if you can find a component that already handles this online. If so, just import it, and figure out how to style it in Login.css like the mock up.
2) Add comments to explain code if necessary
3) We have Login.js component in /components.
4) We have Login.css file in /css to style the Login.js sub-component.

**Design considerations:**
We have decided to use regular CSS files to keep things simple for now. This allows for more contributors and less time to upskill to contribute.

Once MVP is done the team can discuss if we want to transition it to styled-components or something like CSS modules.

**Folder paths**
CSS is located in /client/src/css
Components are located in /client/src/components

**Style guide for CSS files:**
**Naming convention:**
Component -> Login.js
CSS file -> Login.css

**To avoid naming collisions:**
prefix class names with the name of component and link with kebab case.
Class name -> .Login-header { ... }

**How to handle state:**
If you can use redux, use it.
Create action and reducer with an appropriate name.

**Testing:**
No need to worry about testing for now.
If you choose to add tests, please place in client/src/tests

**Comment by SomeMoosery** [comment]
Hey, unless any progress has been made with this - can I take this over as it ties in with my story about a connection with Blockstack? I’ve already made a dummy ‘Login.js’ in order to do so. If someone’s already committed something, let’s chat tomorrow and see what we can do

**Comment by tesla809** [comment]
Sweet have at it @SomeMoosery since it works well with Blockstack task you are doing. I will assign it to you to avoid any blocking. @jchen42703 can work on issue #23.
