### ISSUE TITLE
[Health Log]: Combining Calendar.js and WeeklyTracker.js with Redux data flow

### ISSUE THREAD

**Issue by awu556** [COVID-19-electronic-health-system/Corona-tracker#277]
## Summary

The Health Log needs to be integrated with the Calendar.js and WeeklyTracker.js with functionality specific to each component. This is a complex issue, before taking this on, you will have to be familiarity with the `@full-calendar` and `react-toastify` packages, along with Redux in order to connect it all together. 

Calendar Functionality:

- [ ] Should highlight the current day in a red circle
- [ ] Allow the user to select a previous day, displaying SymptomsTracker survey results, or nothing if the user did not fill out the survey for that day

WeeklyTracker.js (Includes WeeklyTrackerDay.js) Functionality

- [ ] The survey results from a previous day can be edited by swiping right, just in case the user made a mistake while inputting their survey data
- [ ] A prompt will appear below any existing survey results to prompt the user to log their health for the day by swiping right, bringing them to the SymptomsTracker

![Updated HealthLog wireframe](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/design/wireframes/FINAL-V1-03.28/Health%20dashboard%20-%20updated%20(symptoms).png)

**Comment by SomeMoosery** [comment]
I think this is ready to work on if anyone wants to pick this up. For each calendar date, we wouldn't populate the data through Redux (as Redux only stores current survey state), but with a database request, populating each calendar date with each associated observation. 

I can take this on once I finish implement formatting, unless anybody else wants to

**Comment by pavel-ilin** [comment]
@SomeMoosery I can take on this one

**Comment by SomeMoosery** [comment]
Yup, sounds good! I'm looking at this ticket again, and do you think it would be worthwhile to break these up into two tickets - one for calendar and one for weeklyTracker? Or would you want to just try both at once? Up to you

**Comment by pavel-ilin** [comment]
I think I just going to do both.

**Comment by SomeMoosery** [comment]
Closing this as it's too broad, new issues have been added to encapsulate these
