### ISSUE TITLE
DISCUSSION: Migration to TypeScript

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#280]
## Summary

I'm personally a big fan of TypeScript, and think it lends itself to far superior projects overall, both in terms of code clarity and structure. If you don't know what TypeScript is or why it's better than JavaScript, [here](https://www.guru99.com/typescript-vs-javascript.html#4) is a useful summary.

## Motivation

TypeScript encourages our code to be more "mature," and adds a lot more functionality and flexibility while enforcing rigidity at the same time. 

## Describe alternatives you've considered

Sticking with plain JavaScript.

**This is open for discussion, let me know what you all think so we can keep an open record of changes.**

**Comment by johnemurphy1** [comment]
@SomeMoosery I've heard good things about TypeScript vs. Javascript. I've not written anything with it, yet. However,  I'd be happy to try and pick it up for this project. Should we poll the #front-end and #engineering teams to find out who's worked with it before? Maybe, a little more direction on what needs to be refactored and migrated to TypeScript now vs. a future version would be helpful...

**Comment by SomeMoosery** [comment]
Definitely, I can give more context later tonight / tomorrow. I think it would definitely be a later stage move, as it would be refactoring every component we have and a pretty significant undertaking... definitely for when we've matured a bit since we didn't start with it

**Comment by SomeMoosery** [comment]
Closing this for now - too out of scope
