### ISSUE TITLE
Multiple Warnings/Errors on Survey Load

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#281]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

When opening the survey, there are multiple errors relating to DOM elements that should be resolved to ensure our code works smoothly and as planned 100% of the time.

<img width="1380" alt="Screen Shot 2020-03-28 at 2 13 09 PM" src="https://user-images.githubusercontent.com/15767602/77854236-0b413c80-71b7-11ea-92bd-d68fcdb63690.png">

### Steps to Reproduce

1. Log in
2. Navigate to survey and inspect

**Expected behavior:**

No errors/warnings

**Actual behavior:**

Errors/warnings

**Reproduces how often:**

100%

**Comment by JWaltuch** [comment]
I can take this :)

**Comment by JWaltuch** [comment]
I figured out the main errors and one of the warnings.

I'm still getting this warning:
./src/components/Login.js
  Line 17:9:  'changeLanguage' is assigned a value but never used  no-unused-vars
But I'm not certain how/where change language is supposed to be used?

**Comment by JWaltuch** [comment]
Oh cool. Then I'll make a pull request because I handled the error.

**Comment by SomeMoosery** [comment]
Okay nice, just be sure to add the error log from chrome inspector in your PR. Maybe that error you posted inadvertently has to do with survey, I'm not sure, I'll need some autonomy on this one to just make sure all "red" errors are fixed.

**Comment by JWaltuch** [comment]
No problem :)

**Comment by SomeMoosery** [comment]
Reopening: unfortunately, previous changes broke the UI when displayed on mobile, so we should find a different implementation of how to fix errors

**Comment by AdhamAH** [comment]
@JWaltuch if you having trouble fixing this, let me know I can take it

**Comment by SomeMoosery** [comment]
Closing, fixed by #303
