### ISSUE TITLE
Text Logo Misaligned on Disclaimer on Mobile

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#282]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

When viewing the disclaimer on mobile, the text logo is off center and requires scrolling to view the entire disclaimer.

<img width="332" alt="Screen Shot 2020-03-28 at 2 12 06 PM" src="https://user-images.githubusercontent.com/15767602/77854275-5eb38a80-71b7-11ea-8a39-2b904a143b21.png">

### Steps to Reproduce

1. Inspect on mobile view
2. Log in

**Expected behavior:**

The text logo should be centered and fully visible within the disclaimer.

**Actual behavior:**

The text logo is off-center and too large for the screen.

**Reproduces how often:**

100%

**Comment by AdhamAH** [comment]
I noticed this and already fixed it and will be pushed with PR in #276

**Comment by SomeMoosery** [comment]
Sounds good! Just referenced this in your PR so it'll close when that's ready to merge
