### ISSUE TITLE
Chart.js component test failed

### ISSUE THREAD

**Issue by pavel-ilin** [COVID-19-electronic-health-system/Corona-tracker#285]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Chart.js component test failed

### Steps to Reproduce

run 'yarn test' in the console

**Expected behavior:**

test passed

**Actual behavior:**

test failed

**Reproduces how often:**

100%

**Comment by JWaltuch** [comment]
Is this test still failing with the most recent merge? When I try it, it passes.

**Comment by SomeMoosery** [comment]
That's because the test as it stands now isn't doing anything
