### ISSUE TITLE
Create weeklyTracker.js container component

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#29]
**Task**
Use the mockup in the design directory to create a `weeklyTracker.js` container component.

See the following for the `design/wireframes/CORONATRACKER UI-#1`
This component is the container component that holds the sliders which show "You said you felt x/10 today". It is below the Calendar.

`weeklyTracker.js` will hold four `dailyTracker.js`. 

**What done looks like:**
1) See if you can find a component that already handles this online. If so, just import it, and figure out how to style it in weeklyTracker.css like the mockup.
2) Add comments to explain code if necessary
3) We have weeklyTracker.js component in /components.
We have weeklyTracker.css file in /css to style the weeklyTracker.js sub-component.

**Design considerations:**
We have decided to use regular CSS files to keep things simple for now. This allows for more contributors and less time to upskill to contribute.

Once MVP is done the team can discuss if we want to transition it to styled-components or something like CSS modules.

**Folder paths**
CSS is located in /client/src/css
Components are located in /client/src/components

**Style guide for CSS files:**
**Naming convention:**
Component -> `weeklyTracker.js`
CSS file -> `weeklyTracker.css`

**To avoid naming collisions:**
prefix class names with the name of component and link with kebab case.
Class name -> .`weeklyTracker-header { ... }`

**How to handle state:**
If you can use redux, use it.
Create action and reducer with an appropriate name.

**Testing:**
No need to worry about testing for now.
If you choose to add tests, please place in client/src/tests

**Comment by Tanvez** [comment]
I saw this might help in implementing https://codesandbox.io/s/2485wxy78j
https://www.npmjs.com/package/react-toastify

**Comment by awu556** [comment]
Thanks Vesna!

**Comment by awu556** [comment]
I'm stuck on this issue now since it correlates directly with issue #30, see that post for more info.
