### ISSUE TITLE
Organizing the symptoms into cards

### ISSUE THREAD

**Issue by dinadeljanin** [COVID-19-electronic-health-system/Corona-tracker#294]
## Summary

This is what the symptoms look like right now. 
![Screen Shot 2020-03-29 at 17 48 37](https://user-images.githubusercontent.com/32048693/77861847-87527900-71e5-11ea-8691-46345309ee2f.png)

They're spread across one line and the inputs are sized differently... So I thought it would be awesome to separate them into little cards so that way everything can remain centered, but separated.

So the cough input, for example, would be transformed into a mini header. And on click, it'll change to red, to show it's been checked off. And then the symptoms can sit inside this card. And then the temperature and headache inputs can be adjusted to fit inside.

**Comment by SomeMoosery** [comment]
I like this idea a lot! @BrianHHough - would something like fit in with you wireframes (I know he's the design guy so I'm going to defer to him for how to move forward 👍

**Comment by AdhamAH** [comment]
@Tanvez used a very good package and I think it could be also used here with a bit of tweaking or do you have something in mind?

**Comment by dinadeljanin** [comment]
Hey @AdhamAH, what package would that be? I can tweak it with regular CSS and material-ui. It's not a complicated fix.

**Comment by BrianHHough** [comment]
@dinadeljanin Thanks so much for being able to work on this! @SomeMoosery — Dina had a great idea of making the survey have a bit more uniformity. With the UI, we'd want it to look a bit more consistent for the end user, so the cards would help to give it a bit more flow / ease of use.

**Comment by SomeMoosery** [comment]
Would this fit in with the wireframes you created though? If this is a quick fix I'm all for it because I agree, the survey definitely needs improvement. But, if it's going to take a long time to fix, it may be worth trying to move towards the newer wireframes you created?

**Comment by dinadeljanin** [comment]
> Would this fit in with the wireframes you created though? If this is a quick fix I'm all for it because I agree, the survey definitely needs improvement. But, if it's going to take a long time to fix, it may be worth trying to move towards the newer wireframes you created?

 So I'm trying to navigate around the components and alter them using material-ui-- that's probably the bulk of time needed to put this together. But for the most part, really just the container with those inputs and button groups needs to be targeted, to apply flexbox. Adding a bg to the label with the input-- have that change when checked.

**Comment by dinadeljanin** [comment]
Here's an update! Still chipping away. Any thoughts?

![Screen Shot 2020-03-29 at 22 26 29](https://user-images.githubusercontent.com/32048693/77869391-59ccf600-720c-11ea-923c-d930a149a309.png)

**Comment by SomeMoosery** [comment]
I like that a lot!

**Comment by AdhamAH** [comment]
@dinadeljanin I know that component is complicated a bit and applying Material-UI for the first time sure was not easy and will take time. Sorry I was not there to help. That looks great and goes with the flow of the app and theme!
