### ISSUE TITLE
Decide on MVP for our IPR

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#3]
There's been a lot of great discussion around what we want to build, and I want to get as much of these suggestions and ideas built as we possibly can. But, the intent is to have an IPR (Initial Public Release) by Monday 3/16 or early next week. I think to get to that point, we should decide on one definitive feature we want fully fleshed-out and working well. That way (correct me if I'm wrong @tesla809 ), we can look for beneficiaries to assist us with things (primarily the cost) of deploying this at scale. In this IPR we can have a highly-visible list of additional features we'll continue to work on and add, but for time being I think we should focus our efforts on getting our "bread and butter" out the door. 

I think the primary two features right now are:

1. A individual symptom/well-being monitoring tool used by doctors to triage patients. We will work with medical professionals to outline a list of questions to ask individuals (things like, for example, "are you better or worse than yesterday" or "do you have enough soap"). We will aggregate these responses in order to identify high-risk individuals and present this aggregation as a dashboard that medical professionals can use to better triage healthcare. 
2. A crowdsourced inventory-locating tool. Similar to how Waze uses crowdsourced user-submitted data to notify when there is, for example, a police officer nearby - we could use the same format to notify individuals of where there's soap, or non-perishables, etc. This hasn't been fleshed out, but it could be presented as either a simple list, or on a map.

**I think we need to put these two up to a vote so that we can start fleshing out features / individual pieces of work so we can all get working towards the same goal in parallel. Vote 🚀 for 1, 🎉 for 2.** 

Some additional, less-fleshed-out features that could be implemented quickly and in parallel are:

1. A push notification sent every time you leave your house, urging you to practice social distancing, as right now that's the singular best way to stop the spread of disease.
2. **Feel free to suggest below. I can either add to this issue or create a backlog of smaller tasks**

**Comment by sedmo** [comment]
I think 2 seems like it would require having a large amount of people using it which would involve more costs and for it to be more polished. #1 seems like it can grow organically.

**Comment by SomeMoosery** [comment]
Good point! Yeah, I think that's especially important since we're going to hack this together and grow it over the next couple of days / however long we do this

**Comment by SomeMoosery** [comment]
So, the route that seems most logical is going with the symptom/well-being monitoring tool for our first bit of functionality - the first thing we want to have done to say "we have this and can release it." 

At the great suggestion of @BrianHHough we'll have various tabs for additional functionality with a "Coming Soon" overlay until the symptom/well-being tracker is completed (the resource mapping, for example, which some good headway has already been made by @akilhylton in the other repo I believe).

Going to close this and start working on scoping out some features now.
