### ISSUE TITLE
Refactor Gaia requests to utilize react-blockstack useFile

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#306]
## Summary

As mentioned in #299 by @njordhov - we want our applications to be as reactive as possible. We should use the `useFile()` function in [react-blockstack](https://www.npmjs.com/package/react-blockstack) to allow for that. We need to update any puts/gets to Gaia to utilize `useFile()`

## Motivation

We want our code to be reactive, and `useFile()` allows for a familiar interaction with Gaia.

## Describe alternatives you've considered

Continuing to just use put/get

**Comment by Afrogrrrl** [comment]
I’ll do this as part of #298

**Comment by Afrogrrrl** [comment]
would like some help on this if anyone is up to pair programming with me!

**Comment by SomeMoosery** [comment]
Closing - while this is going to be good for a long-term change, it's come to the point where using solely `react-blockstack` or majority `react-blockstack` for at least the near term may slow our dev process, as we're moving towards a release of 4/15.

We may have another new issue for this opened up down the line.
