### ISSUE TITLE
Dockerize React App

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#316]
## Summary

We need to Dockerize our React client. This story: 
- [ ] creates a Dockerfile for React client

## Motivation

As is the case with most modern projects, we should look to Dockerize this application. While for the time being we are simply deploying to S3, that may not always be the case. We should look to Dockerize this so that if we do every host the site elsewhere we have a nice containerized version.

## Describe alternatives you've considered

Not Dockerizing the app, leaving it as is.

**Comment by JWaltuch** [comment]
I'd also like to give this a try if that's cool :) I've been meaning to learn how to Dockerize an app

**Comment by SomeMoosery** [comment]
Go for it! Take a look [here](https://dev.to/ziv/dockerize-create-react-app-in-3-minutes-3om3) for reference, could be useful 👍

**Comment by JWaltuch** [comment]
I'm been trying to do this for a while, and still getting a lot of errors. I don't know if anyone would be interested in pairing, or if someone who's dockerized an app before has any advice? The error is a little long to paste, but this is where it starts: "error /app/node_modules/canvas: Command failed."

**Comment by SomeMoosery** [comment]
There doesn't really seem to be much point in doing this for now - if anything, it's a nice perk but not necessary
