### ISSUE TITLE
Current unable to add more than 10 observations

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#317]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

As it stands now, the current naming convention / method for adding new observations does not allow for new observations past 10. It will just continuously add/replace survey 10 each time.

### Steps to Reproduce

1. Log in
2. Click "Take Survey" -> Complete it ten times
3. Inspect when adding the eleventh element

**Expected behavior:**

We can add as many observations as we'd like (within reason)

**Actual behavior:**

We can only add 10 observations

**Reproduces how often:**

100%

### Versions

0.2.2

**Comment by tylerd92** [comment]
@SomeMoosery I would like to take a look at this, but I do have a few questions. Is the observation data still being saved in the mongoDB database? If so what part of the backend is taking the data from the front end and saving it in the database?

**Comment by SomeMoosery** [comment]
I'll assign you! So we've moved away from using Radiks (which makes use of the MongoDB database) as it added unnecessary complexity. Now, we're just using Gaia, Blockstack's built-in and managed storage solution. Take a look at `DiagnosticContainer` - we're using the `useFile()` provided by the `react-blockstack` package which allows easy setting and getting from this built-in storage. 

This issue will change the way we're entering data in `submitSurvey()` using `putFile`. It may be worth looping in @njordhov to see if there should be a different/better way to add or name these observations.

**Comment by njordhov** [comment]
Possibly due to the zero-padding of the observation key. The key name should be zero padded to have the same number of digits including when the number of observations goes beyond 9. It is not sufficient to just prefix the key with a set number of zeros, in which case the observation keys won't sort alphabetically. Example:

    observation/00001.json
    observation/00002.json
    observation/00003.json
    observation/00004.json
    observation/00005.json
    observation/00006.json
    observation/00007.json
    observation/00008.json
    observation/00009.json
    observation/00010.json
    observation/00011.json
    observation/00012.json
    ....

rather than

    observation/00009.json
    observation/000010.json
    observation/000011.json
    observation/000012.json

**Comment by njordhov** [comment]
Just make sure to have enough zeros to avoid it ever rolling over (year-2000 bug style). Likely we'll migrate the storage scheme by the time there are 99999 observations but pad with as many zeros as seems prudent.

**Comment by SomeMoosery** [comment]
Makes a lot of sense, I figured my initial pass had something off. 

@tylerd92 take a look [here](https://stackoverflow.com/questions/10073699/pad-a-number-with-leading-zeros-in-javascript) for reference as at first glance this looks like it could be of assistance

**Comment by tylerd92** [comment]
Yup, I have a possible solution using the [padStart ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart) method in ES8 Javascript
