### ISSUE TITLE
Don't show disclaimer if user has already consented

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#319]
## Summary

When the user logs in, use `useFile` ( #306 ) to get `"disclaimer.json"`, if it exists. If so, and it indicates that the user has already consented, do not display the disclaimer.

## Motivation

We want to make the UX as seamless as possible. If we can rid the user of a popup each time s/he logs in, that fraction of a second amounts to a much more pleasant UX.

## Describe alternatives you've considered

Leaving as is

**Comment by JWaltuch** [comment]
I'd like to try this. I haven't gotten to work with the backend yet. It's less familiar to me and I'd like to learn more about it.

**Comment by SomeMoosery** [comment]
Sounds good! This one shouldn't be too tough.

You'll probably just have to use react-blockstack's `useFile` in `DiagnosticContainer` with a conditional on whether or not to display the disclaimer 👍 

https://blockstack.github.io/blockstack.js/classes/usersession.html

**Comment by JWaltuch** [comment]
Do I update the version for semantic versioning?

**Comment by SomeMoosery** [comment]
Yup, we’ll do that for each new PR now 👍
