### ISSUE TITLE
Create views for Doctor's dashboard

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#32]
Create views for Doctor's dashboard. @BrianHHough is taking care of mocks ups.

**Comment by BrianHHough** [comment]
![CORONATRACKER UI-List_Patients-InfoCard](https://user-images.githubusercontent.com/56947075/76819758-8b42cc00-67df-11ea-8174-ff2edd668c49.png)
![CORONATRACKER UI-List_Patients](https://user-images.githubusercontent.com/56947075/76819762-8bdb6280-67df-11ea-8b20-8365263ed563.png)
