### ISSUE TITLE
Create skeleton user settings page

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#320]
## Summary

As the final tab of our application, we need to add a user settings page. This issue can encapsulate just creating the UI to be compliant with wireframes made by @BrianHHough 

- [ ] user can navigate to app by clicking settings tab
- [ ] settings page looks similar to wireframe

## Motivation

As we move this app closer to a done state, we need to ensure that all relevant features are there and clickable

## Describe alternatives you've considered

No alternatives, we need this page

**Comment by AdhamAH** [comment]
I was testing an idea, what do you think?
![test](https://user-images.githubusercontent.com/55054963/78038309-fdcdb300-736c-11ea-8f13-88f2f96ade6c.gif)

**Comment by SomeMoosery** [comment]
Nice! I like this a lot as a start. I definitely am a fan of the popup vs a fully separate page. I'd say keep going down this route, I'll assign you 👍
