### ISSUE TITLE
Switch to React-Calendar

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#327]
## Summary

Moving forward, while FullCalendar was useful as a placeholder, it was an Angular-first component. Moving forward, we should use something we're more comfortable with. [react-calendar](https://www.npmjs.com/package/react-calendar) seems to work best.

Acceptance Criteria: 
- [x] Remove all references of FullCalendar, make sure it's not in `package.json` (using `yarn remove`) 
- [x] Install `react-calendar` in and instantiate it in `MyHealthLog`
- [x] Add a Calendar within `Diagnostic Container

**Comment by pavel-ilin** [comment]
I'm on it.

**Comment by pavel-ilin** [comment]
I think calendar need to be styled according to the aesthetics of the app. But functionally it working well.

**Comment by SomeMoosery** [comment]
Good point - let's merge this in and we can create a separate styling story 👍
