### ISSUE TITLE
Create "Show Me More" Skeleton

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#329]
## Summary

One of the final components we need is the "Show Me More" tab. In `HealthLogToggle.jsx` we currently have the "My Health Log" functionality mostly in place, but we need the skeleton UI scaffolding to implement the "Show Me More" page. 

<img width="342" alt="Screen Shot 2020-03-31 at 8 51 36 PM" src="https://user-images.githubusercontent.com/15767602/78088207-75153e00-7391-11ea-8d9f-71832aeca7d4.png">

For the time in, we can feed in dummy data as is being done in `WeeklyTracker`, and then create a new issue to handle user data from Gaia.

## Motivation

We need this component to just about finish out all necessary components for our app! 

## Describe alternatives you've considered

N/A

**Comment by SomeMoosery** [comment]
closing, as this is the old design. Apologies

**Comment by SomeMoosery** [comment]
Nevermind, I'm losing it - we still need this

**Comment by AdhamAH** [comment]
I think because you felt this is made, in that case, you are right. Needed some modification to show.
It still needs to be converted to material-ui but for now it is working
