### ISSUE TITLE
Finalize Temperature Line Chart

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#333]
# Depends on #23 

## Summary

- [ ] temperature line chart queries gaia storage for all temperatures, **or better yet** stores an array of all temperatures as a new redux state variable after initial database query in HealthLog 
- [ ] temperature line chart looks similar to wireframe spec
- [ ] chart in placed under the toggle component

## Motivation

This is one of the necessary components in the wireframe

## Describe alternatives you've considered

Alternatives for how to get user data is specified above - you should defend your choice in your PR

**Comment by pavel-ilin** [comment]
Can take this one.

**Comment by SomeMoosery** [comment]
Now that #331 is merged in, I'd strongly recommend storing any state from initial Gaia query in Redux 👍
