### ISSUE TITLE
Add temperature average next to temperature line chart

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#334]
## Summary

- [ ] Create a Material-UI grid implementation displaying the Temperature Line Chart (`Chart`) next to the temperature average component
- [ ] this is all contained within the symptom toggle

## Motivation

Necessary component as listed in wireframe

**Comment by Afrogrrrl** [comment]
I can take a crack at this one once issue #23 is done

**Comment by johnemurphy1** [comment]
@Afrogrrrl code is done and tested for Temperature/Symptoms toggle. Keep running into merge issues with Git. I'll try again either tonight or tomorrow morning to get the PR in and approved.

**Comment by SomeMoosery** [comment]
Is this in the codebase anywhere? If so could someone link me to it, I can't seem to find it anywhere. Otherwise, I'll add a "help wanted" tag

**Comment by Afrogrrrl** [comment]
There hasn't been a PR for it yet. Sorry for the delay!

**Comment by SomeMoosery** [comment]
Oh no problem! I just didn't know if there was anything unclear above :)

**Comment by Afrogrrrl** [comment]
Apologies, I've had a lot going on this week and I figure I've been sitting on this issue for too long so I thought it best to give someone else a chance to do it. If no one else wants to take it on I can ultimately do it. I know it's not a huge task, I just haven't been able to sit and focus on it with everything else going on.

**Comment by SomeMoosery** [comment]
No problem - take as much time as you need hope all is well

**Comment by gitalink** [comment]
I will take a stab at this.

**Comment by gitalink** [comment]
Hey @johnemurphy1, you mentioned code for the temperature/symptoms toggle was ready and tested, were you able to merge it? I picked up this ticket to add the temperature average.
