### ISSUE TITLE
Clicking calendar date highlights it

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#337]
## Summary

- [ ] on calendar click, date is highlighted (speak with contributor to #336 to make sure you're not using the same highlighting / indication)

## Motivation

Appealing UI!

**Comment by mamutahr** [comment]
Hello, it seems that the most recent merge solves this as well as issue #336. Is there anything I should to add or change or are these both closed issues?

**Comment by SomeMoosery** [comment]
It looks like #336 has been closed and it seems like this one should be closed out as well - good catch!
