### ISSUE TITLE
Create Bar Chart for Symptoms

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#339]
# Depends on #23 

## Summary

- [ ] Creates bar chart using package of your choosing (but be prepared to defend why you chose it in PR)
- [ ] **OPTIONAL but preferred** on initial database query in health log, create arrays of temperature, fever, sore throat, etc as new redux state variables
- [ ] Displays this bar chart in Symptom toggle

## Motivation

This is a key component of the wireframe spec

## Describe alternatives you've considered

There's a few ways to best implement this. Be prepared to defend your choice and if you didn't choose to do the OPTIONAL step then why

**Comment by pavel-ilin** [comment]
Can take on this one.

**Comment by SomeMoosery** [comment]
Now that #331 is merged in, I'd strongly recommend storing any state from initial Gaia query in Redux 👍
