### ISSUE TITLE
Make calendar look more similar to wireframes

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#343]
## Summary

- [ ] Make map look more similar to wireframe spec

## Motivation

Prepare for 4/15 launch

**Comment by crispinamuriel** [comment]
I'd like to work on this.

**Comment by SomeMoosery** [comment]
sounds good! Take a look at how I did the gradient for `WeeklyTracker`, as I bet a similar technique could be applied for the background of the calendar as well! Also, I had some trouble finding this but @BrianHHough has the hex colors we need in the README of the `/design` folder 👍

**Comment by AdhamAH** [comment]
@crispinamuriel I was looking at this yesterday and I know it could be hard to deal with. You need to change or override the original calendar.css file. let me know if I can help but I am sure you got it

**Comment by crispinamuriel** [comment]
Hello! I think I might be misunderstanding the wireframes. Is there any way I can get clarification on the color of the calendar? 

[blue calendar](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/design/wireframes/FINAL-V1-03.28/MASTER_WIREFRAME_daily_health_log.png)
[red calendar](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/design/wireframes/v1-final-MVP-subcomponents/CORONATRACKER%20UI%20-%20Logged%20In%20Home%20Page%20-%20Patient%20Calendar%20Tracking.png)

**Comment by SomeMoosery** [comment]
We want to go with the blue calendar - it's the "final" UI for the time being and we should go with that (we should probably remove the other outdated files from GitHub as well, good catch). For this PR, don't worry about any of the circling or indication of dates, because we have separate stories out for those now. We just want to make the calendar itself look as similar to that blue calendar as well can.

Hope that helps / makes sense!

**Comment by AdhamAH** [comment]
@crispinamuriel check
[this](https://discordapp.com/channels/687791378075484161/689541206686040094/693919857627889694) for the wireframes and [this](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/design/README.md) for the colors
