### ISSUE TITLE
toastify package a bug

### ISSUE THREAD

**Issue by AdhamAH** [COVID-19-electronic-health-system/Corona-tracker#347]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description
Random string shows between the weekly tracer and calendar as shown 
![Screenshot 2020-04-01 at 16 11 43](https://user-images.githubusercontent.com/55054963/78147275-93cc1100-7433-11ea-818b-7eaa40032747.png)

### Steps to Solve 

Tired to do some research on how to fix [search](https://www.google.com/search?sxsrf=ALeKk03MAP42IVm6EamyiBttMxwLBedPEg%3A1585750229370&ei=1aCEXv-SFsjasAeak7PoCQ&q=random+string+react-toastify&oq=random+string+react-toastify&gs_lcp=CgZwc3ktYWIQAzoECAAQR1CSMliSMmD8M2gAcAN4AIABOogBOpIBATGYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwi_0f74s8foAhVILewKHZrJDJ0Q4dUDCAs&uact=5)

**Expected behavior:**

Not to show this string 

**Actual behaviour:**

showing the random string 

**Reproduces how often:**

Infrequently

**Comment by SomeMoosery** [comment]
Are you going to take this on? Or, if you want to switch over to `react-spring` will doing so close this bug as well?

**Comment by AdhamAH** [comment]
If we use `react-spring` and remove `toastify` that will fix it. Other than that it needs fixing and I did the research but couldn't fix it.

**Comment by SomeMoosery** [comment]
Interesting, but it seems like since moving over to react-spring is the right move (appreciate that research good looking out!) that will hopefully get rid of this bug too 👍

**Comment by SomeMoosery** [comment]
Taking this on as well in a sense, as it will be closed out by #348
