### ISSUE TITLE
Change package used in WeeklyTracker

### ISSUE THREAD

**Issue by AdhamAH** [COVID-19-electronic-health-system/Corona-tracker#348]
## Summary
Change the package `react-toastify` used in `WeeklyTracker.jsx` and use `react-spring` used in `Card.jsx` 

## Motivation
1- `react-toastify`  has a bug #347 and needs some work to style.

2-  `react-spring` we already using it and proved to be reliable and gives more options regarding the motion and the style

## Alternatives
1- we can use [slide](https://material-ui.com/components/transitions/#slide) and [snackbars](https://material-ui.com/components/snackbars/) from Material-UI. this will give motion in entering and exiting but may only work `onClick` 
2- keep as it is

**Comment by SomeMoosery** [comment]
Are you taking this one?

**Comment by AdhamAH** [comment]
Yeah I did my research as I was reviewing all the components after reading the new issues and pulls.

I can take this but it will take time and I am a little busy. I don't know when this should be done? @SomeMoosery

**Comment by SomeMoosery** [comment]
No worries! I was actually going to start looking into the WeeklyTracker work myself today, so I can pick this up as a first issue around that. Thanks for pointing this out! It’s definitely key to be sure we’re using the best packages we can be early on
