### ISSUE TITLE
Remove old Radiks code

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#356]
## Summary

Since we have moved away from Radiks, we have no need for the code in our code base that utilizes it, such as the `loadObservations` redux flow.

- [ ] remove all traces of Radiks from codebase and associated reducers, functions, etc

## Motivation

We want to keep our codebase current and up-to-date

**Comment by tylerd92** [comment]
Since we are no longer using Radiks I guess the models would need to be changed? I guess they could be changed to regular JS classes, but then there would be no typing. Also, I guess we won't be needing the custom Radiks server.

**Comment by SomeMoosery** [comment]
Yeah, so at this point I think we can:

1. Change the models to regular JS classes
2. Tear down / decouple the Radiks server for the time being
3. Remove things such as LOAD_OBSERVATIONS, as those were interacting with Radiks

I don't think I've seen any more uses, but I may be missing something

**Comment by tylerd92** [comment]
I would like to try to work on this.
