### ISSUE TITLE
Formalize fields in client/public/locales/en for translators

### ISSUE THREAD

**Issue by salvolpe** [COVID-19-electronic-health-system/Corona-tracker#359]
Could anyone work on labeling all of the fields in `client/public/locales/en` in a formalized way? @akilhylton has done some great work to set up .json files and the react module for integrating the translations, but if there is a set format and identifiers for each section of text, it will make it a lot easier for the translations team to give you the corresponding text! I'd say you can message myself, @akilhylton , and/or @AdhamAH  if you have any questions about it!

**Comment by johnemurphy1** [comment]
@salvolpe here's a rough first draft of what I would propose for the format of what would be delivered back to the translation team. Each screen in the wireframe would be titled in all caps then fields would map to the json/react syntax based on @liadove's original work. This is just a draft to make sure it's heading on the correct path. Your feedback, @SomeMoosery, @akilhylton and @AdhamAH feedback and agreement would be needed before I get this started.
[translationfieldsdraft.txt](https://github.com/COVID-19-electronic-health-system/Corona-tracker/files/4463294/translationfieldsdraft.txt)

**Comment by johnemurphy1** [comment]
Note: this draft only includes the Log In and Disclaimer screens on https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/design/wireframes/FINAL-V1-03.28/MASTER_WIREFRAME_reduced.png

**Comment by salvolpe** [comment]
@johnemurphy1 I think this looks great and would be readable to the translators!

**Comment by SomeMoosery** [comment]
@johnemurphy1 are you working on this?

**Comment by johnemurphy1** [comment]
Yes, I am working on it.

**Comment by johnemurphy1** [comment]
Hi all, this is the translation JSON file that I created per this issue. After a discussion with Sal and Austin, the questions center around what questions have to be included in the launch version and/or could be added (or deleted) later based on @ngiangre 's analytics and/or other parties contributing on various components. Please review attached and comment.
[translationsFormatted.txt](https://github.com/COVID-19-electronic-health-system/Corona-tracker/files/4483147/translationsFormatted.txt)

**Comment by johnemurphy1** [comment]
looks like this closes this https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/Translations/appText.json closes this issue...credit to @BrianHHough

**Comment by BrianHHough** [comment]
Awesome! I can close this one. Feel free to edit this file in case there are any bugs/needed edits, but all the text is there and organized for the app as of today: https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/Translations/appText.json

Go team! 🎉

**Comment by SomeMoosery** [comment]
Reopening this - we need more active communication for what's going on here.

How does this ticket pertain to #643 - should we close this as another ticket has been made "on top" of it? Or can these be paralellized and John can continue to work on this while Brian continues to work on something else

**Comment by ngiangre** [comment]
#643 is very similar/the same as this issue. I think it was a miscommunication - sorry about circumnavigating the PR process - we'll talk to @BrianHHough

**Comment by SomeMoosery** [comment]
No worries at all!

**Comment by ngiangre** [comment]
closing in lieu of #643
