### ISSUE TITLE
Contributing file updates

### ISSUE THREAD

**Issue by whoabuddy** [COVID-19-electronic-health-system/Corona-tracker#361]
## Summary

After PR #354 there were a few small changes that need to be made, and some additions requested by @tesla809. The list of updates are below.

- [x] fix local repo reference to use `Corona-tracker` versus `COVID-19-TRACKER` (the latter was the name I used for my fork, didn't catch it when putting things together)
- [x] add more info on using git branches
- [x] add more info on clean commit messages
- [ ] add more info on what to do when _things go wonky_ (technical term)
    - [x] rebasing against upstream master
    - [ ] resetting against upstream master (fresh start)
    - [x] force pushing changes to origin
- [x] review file for any duplicate content

## Motivation

The additional information above would fit well with the [Forking the Repo](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/CONTRIBUTING.md#forking-the-repo) and [Updating a Forked Repo](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/CONTRIBUTING.md#updating-a-forked-repo), possibly adding a third outline item for "I broke my repo, now what?" or similar.

## Describe alternatives you've considered

None at this time! Trying to find the balance between short and sweet and overly informative. :information_source: 

## Additional context

None.

**Comment by whoabuddy** [comment]
Some items are complete and I reflected that in the checkboxes above. After looking over the updates again and some changes submitted by @tesla809, I'd like to pause on completing this before initial launch and ask some bigger questions, mainly toward content duplication and moving some items to their own files. This became quite a large CONTRIBUTING file!

For example, [Updating a Forked Repo](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/CONTRIBUTING.md#updating-a-forked-repo), [Git Contribution Workflow](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/CONTRIBUTING.md#git-contribution-workflow), and [Updating the Repo](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/CONTRIBUTING.md#updating-the-repo) have very similar content about fetching and merging upstream master repo in slightly different contexts.

Here were some ideas I had reading through today:

- move bug reports and suggestion enhancements to the top because they are quick and based on creating issues, not forking the repo
- move section on installing yarn to common commands file, then reference at beginning of front-end config as "if not installed"
- consolidate getting started and contributing code sections
- grouping both sets of resource links into one section
- separate doc for common commands / cheat sheet
- ensuring each section corresponds to an action, and look for more opportunities to link sections to each other / other files in repo
- consider evergreen text that works with any text editor (saw that `esc` + `:x` in there!)

I can take a deeper dive into this later on but didn't want it to be a blocker in any way, I am curious to know your thoughts, and if something needs immediate update feel free to ping me.

**Comment by SomeMoosery** [comment]
Maybe we should have the PR you have out now close this issue, and then take these suggestions and write out newer, more parallelizable issues?

**Comment by tesla809** [comment]
GREAT OBSERVATIONS @whoabuddy !!!! Impressive stuff!

**Comment by whoabuddy** [comment]
@SomeMoosery Agreed, will create a new issue and close this one, and if you look at my notes in the PR we may close and recreate that as well to start fresh. No need to mess things up over a minor change! (Sorry for making more of a mess - just trying to help!)

**Comment by SomeMoosery** [comment]
Sounds good! You didn't mess anything up either of course - having great documentation is crucial so this is all great 👍
