### ISSUE TITLE
Refactor observation storage: master list and read-only copies

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#365]
## Summary

As we move towards a more final-state layout for out data, as brought up by @pavel-ilin and expanded on by @njordhov [here](https://github.com/COVID-19-electronic-health-system/Corona-tracker/pull/358), we should aim to have a "master file" of all observations in order to easily manipulate, iterate through, and work with our data for all observations, as well as our pre-existing individual copies of each observation.

That way, when we want to access all, say, temperatures, we can read in our master `observations.json` list, and iterate through the JSON-ized version of that. Additionally, if we know we want a specific list, we can still access that particular observation just as easily.

## Motivation

This added redundancy will allow for the easiest interaction with our observations that we can get.

## Describe alternatives you've considered

Combining Blockstack API calls like `getFile()` and `putFile()` with React Blockstack hooks like `useFile()` and `useFilesList()`

**Comment by SomeMoosery** [comment]
I'm on this, as it will affect work on #338 which I have already been assigned

**Comment by njordhov** [comment]
Consider keeping the aggregated _"master file"_ in the **Local Storage** of the browser (rather than in Gaia), generated initially from the persistent content in Gaia then later kept updated with changes in the state.

**Comment by SomeMoosery** [comment]
This was brought up [here](https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/457) in #457 - closing this issue as this new one has more up-to-date information
