### ISSUE TITLE
Navbar either not showing up or showing up not as designed

### ISSUE THREAD

**Issue by sedmo** [COVID-19-electronic-health-system/Corona-tracker#38]
The Navbar component is not functioning as expected probably because of conflicts with CSS in bootstrap. Will need to be refactored so it matches the expected design.

**Task:**
Refactor navbar to appear as intended design

**What done looks like:**
It matches the design located at the footer of in /design/wireframes/ CORONATRACKER UI - Login Screen.png

**Comment by jchen42703** [comment]
I'll take a look at this

**Comment by SomeMoosery** [comment]
Is this good to be closed? @jchen42703

**Comment by jchen42703** [comment]
@SomeMoosery Yeah
