### ISSUE TITLE
Update Education button to look more like wireframes 

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#386]
## Summary

- [ ] Facts/Quiz buttons in the "Education" tab use our current color scheme

Look to use @acthelemann `buttons.js` styling 

## Motivation

Getting everything to a near-ready state

**Comment by crispinamuriel** [comment]
May I work on this?

**Comment by SomeMoosery** [comment]
All you!

**Comment by crispinamuriel** [comment]
Hello! I just wanted to clarify the wireframes to make sure this is what's expected for this issue:
<img width="1055" alt="Screen Shot 2020-04-05 at 11 30 27 AM" src="https://user-images.githubusercontent.com/47477912/78503824-0dffdc80-7737-11ea-90c8-34bd96d8f882.png">

**Comment by SomeMoosery** [comment]
So I don't think we have wireframes for it, actually, but we should have the colors be consistent with other buttons (like the ones below). Connor's `buttons.js` allows that to be easy as you can just do something like 

```
const useStyles = makeStyles({
  buttons: {
    ...buttonsCss.buttons,
    margin: '2px 15px',
  },
});
```

<img width="327" alt="Screen Shot 2020-04-05 at 12 23 44 PM" src="https://user-images.githubusercontent.com/15767602/78504008-4eac2580-7738-11ea-8c9f-5c0446279d46.png">
