### ISSUE TITLE
Create skeleton for survey indicator from wireframe

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#391]
## Summary

- [ ] Create an indicator of what step of the survey you're on, modeled after [the wireframe](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/design/wireframes/FINAL-V1-03.28/Survey%20Part%203%20of%203.png)
- [ ] Should be able to highlight each circle along the way, but doesn't need to pull in real data until #390 is complete

## Motivation

- We want to get this to a near-final state, and this is a big aesthetic boost

## Describe alternatives you've considered

- Not including this in beta, but I think we can get it done!

**Comment by AdhamAH** [comment]
do you mean something like [this](https://material-ui.com/components/steppers/)?

**Comment by SomeMoosery** [comment]
Yes, perfect, I just didn't know the term for it 😆

**Comment by AdhamAH** [comment]
I am not sure whats your plans for #390 because this connected to it. are you planning to keep everything in one file? I had an idea of breaking them to be reusable and easy to modify if we want to add more surveys or even a symptoms like "loss of smell'. 
if so I can start working on it asap. if not better to wait until #390 finished

**Comment by SomeMoosery** [comment]
I'd say let's hold off then, I'm currently working on #390 and should hopefully be done tonight. I'm storing data in a new way and I think a little bit differently than you might be describing so when I push my changes up I'll let you know and we can discuss 👍

**Comment by AdhamAH** [comment]
Tonight = early morning to me 😆 
that sounds good!

**Comment by AdhamAH** [comment]
@kevin-Price check this also
