### ISSUE TITLE
Add back buttons in new survey

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#399]
## Summary

- [ ] add back buttons in pages 2 and 3 of survey
- [ ] the previous page's state should be retained (so if you go from 2 back to 1, the selections you made in 1 should still show up)
- [ ] these buttons should be stylized similar to our UI/UX guidelines (although there are no wireframes for this, use shared CSS like `buttonsCSS`

## Motivation

This will allow users to go back and edit survey questions, making the process more seamless.

## Describe alternatives you've considered

- Not adding a back button

**Comment by JWaltuch** [comment]
I can take a look at this tomorrow. It'll be a nice break to clear my mind from trying to figure out what's wrong with my Dockerizing hehe.

**Comment by SomeMoosery** [comment]
Great, no problem - as Dockerizing can wait until after V2 since it's just a React app. We'll need to wait for my PR for #390 to merge in though, which will hopefully be tomorrow, so I'd keep going on Dockerizing in the meantime 👍 

I'll assign you to this though!

**Comment by JWaltuch** [comment]
Sounds good
