### ISSUE TITLE
Stuck on loading animation on logout

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#400]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

- When logging out, the user gets the loading icon and nothing happens unless the page refreshes

### Steps to Reproduce

1. Login
2. Logout

**Expected behavior:**

We return to the login page

**Actual behavior:**

We hang on loading

**Reproduces how often:**

~80%

### Versions

0.2.23

**Comment by AdhamAH** [comment]
could be this, #254 and #180 related? or did the other issues been fixed but not closed?

**Comment by SomeMoosery** [comment]
I think these two are more separate issues - this one isn't so much as an error as there's probably some missing logic (i.e. maybe clicking "Sign Out" doesn't redirect you to login or something). 

I've been leaving that other issue open because I still occasionally get it locally with my Blockstack, but may close it soon as it seems to be pretty isolated to just one user on one Blockstack account when running locally.

**Comment by gitalink** [comment]
I will look at this as my first issue

**Comment by SomeMoosery** [comment]
Great! Don't hesitate to reach out if you need anything

**Comment by gitalink** [comment]
Cool!

**Comment by SomeMoosery** [comment]
It looks like this issue has actually already been resolved within another PR - sorry about that! If you're still interested, I'll be adding more issues later this afternoon as we move towards our beta launch on 4/15, and can assign one of these to you!

**Comment by gitalink** [comment]
Yes, please assign a good first issue to me. Looking into #400 was still
useful to get familiar with the code. Thanks
