### ISSUE TITLE
Update text styling on page 2 of new survey

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#402]
## Summary

- [ ] Kind of open ended, but we want to make our text more appealing to the user, as this is the core part of our app

## Motivation

Making the survey look as good as it possibly can

## Describe alternatives you've considered

- Leaving this as is

**Comment by AdhamAH** [comment]
I am not sure if this still needed as we updated the fonts for all the app I think.
If there is something specific let me know,
but this what it might be done (hence I don't like fonts on full black) 
![Screenshot 2020-04-16 at 19 55 16](https://user-images.githubusercontent.com/55054963/79489864-40091c80-801c-11ea-8533-e32e6e86f2fe.png)

**Comment by SomeMoosery** [comment]
I'd say we can wait on this for now, and think of a more complete redesign of how to present this page on desktop and make it user-friendly
