### ISSUE TITLE
Need to navigate to health log to get numObservations

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#403]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Currently, `numObservations` is set in `DiagnosticContainer`, when it should probably be set in a higher level component. This might negatively affect our app if, for example, someone navigates right to the survey, and then uploads their newly-completed survey as Observation 1 because we never got the current count of observations for the user 

**I would suggest moving this to `App.js`**

### Steps to Reproduce

1. Navigate directly to the survey
2. Complete a survey and see it update Observation 1

**Expected behavior:**

We have the number of observations available to us in every component

**Actual behavior:**

Sometimes, we don't get that

**Reproduces how often:**

100% if you don't hit `DiagnosticContainer` first

### Versions

0.2.22

**Comment by tylerd92** [comment]
Last weekend I was looking into react hooks since it is used a great deal in this project. One benefit of creating a custom hook is that you can share reusable logic between components. https://reactjs.org/docs/hooks-custom.html I think this may be a good use case for a custom hook for numObservations.

**Comment by SomeMoosery** [comment]
Good call, definitely seems like a good use case. If you want to write a new issue to create new hook for this it's all you!
