### ISSUE TITLE
Sometimes doesn't redirect to homepage on survey submission

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#404]
# Blocked by #390 

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Sometimes, after finishing the survey, the user is not redirect to the Health Log page.

### Steps to Reproduce

1. Log in 
2. Complete a survey
3. Wait to see if you are redirected

**Expected behavior:**

Redirected to homepage 

**Actual behavior:**

Don't navigate away from survey, or navigate back to page 1 because of Redux update

**Reproduces how often:**

~50%

### Versions

0.2.22

**Comment by JWaltuch** [comment]
I can take a look at this while I'm waiting for the other PR to get merged in.

**Comment by JWaltuch** [comment]
Oh, this one's also blocked by 390? Just confirming. I can still take this issue when it's ready :)

**Comment by SomeMoosery** [comment]
You may have to change some things up once my PR merges in, but a lot of the logic of submitting an observation with this current flow vs my new flow will be the same.

Also, should I remove you from #316? I just don't want you to be stretched too thin, especially if someone else wants to come along and pick that up I don't want anyone to be blocked

**Comment by JWaltuch** [comment]
Would you prefer I remove myself? I'd love to figure out how to do it so if someone else is interested in working with it I'd love to pair. I've tried it in many iterations already, which have just led to varying errors.

**Comment by SomeMoosery** [comment]
I can list it back up as "Help Wanted" to encourage people to pair!

**Comment by JWaltuch** [comment]
Sounds good!
