### ISSUE TITLE
Migrate to react-use-gesture

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#405]
## Summary

- [ ] switch over from react-with-gesture to react-use-gesture

## Motivation

react-with-gesture is depreciated, and we should make sure our dependencies are up-to-date so we stay current and also, more importantly, secure

**Comment by mamutahr** [comment]
The only place I can find react-with-gesture is in the yarn.lock file, should this issue be closed?

**Comment by SomeMoosery** [comment]
I’m pretty sure it’s being used for the WeeklyTracker / DailyTracker sliding components no? It was last I checked (not at computer now). If not, all that needs to be done would be to remove it entirely using ‘yarn remove’

**Comment by mamutahr** [comment]
I found react-use-gesture in the sliding parts for those components so i think were good, ill try it out and submit a pull request

**Comment by SomeMoosery** [comment]
Ah, nice - hadn’t noticed someone must’ve changed it when updating them at some point!
