### ISSUE TITLE
Create custom 404 page

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#407]
## Summary

- [x] create custom 404 page
- [x] [add it to our router](https://medium.com/@NaveenDA/creating-a-custom-404-notfound-page-with-react-routers-56af9ad67807)
- [x] page should stick with common theming / styling of the application

## Motivation

We want this to be as sleek as site as possible, but this is also a beta, so in the likely event someone navigates to a site and doesn't get what they were hoping for, we need a custom 404 page

**Comment by liadove** [comment]
I'm on it
