### ISSUE TITLE
Update onboarding component to fit with styling

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#408]
## Summary

- [ ] Styling should be done with Material-UI wherever possible, not plain HTML
- [ ] While there's no wireframe for this, we should update our onboarding screen to look and feel more similar to the rest of the components, using the same color scheme, spacing, etc.
- [ ] Work with @BrianHHough in order to make sure design in up-to-date
- [ ] Remove name, as this is already provided through Blockstack's platform
- [ ] Remove `eslint-disable` tag at the top when button is moved to Material-UI

## Motivation

We want all of our components to fit together as smoothly and seamlessly as possible

**Comment by AdhamAH** [comment]
this will be done by midday 10/4
