### ISSUE TITLE
Custom react hook for numObservations 

### ISSUE THREAD

**Issue by tylerd92** [COVID-19-electronic-health-system/Corona-tracker#413]
## Summary

Create a react hook for numObservations thus allowing that data to be accessible to other components
## Motivation
A feature to fix a bug [issue #403](https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/403)

## Describe alternatives you've considered
An alternative could be using a higher-order component

**Comment by SomeMoosery** [comment]
I'm realizing while you brought this up and I support this idea, but I'm not too familiar with custom React hooks so can't properly estimate how much time this would make. I just realized I should point out that this may be a good use case, especially moving forward, for using the `react-blockstack` package, as there's a `useFilesList()` hook which returns `[files, numFiles]` - we should just have to go through and parse out which of these are observations. 

I'm of the thinking that if it's not too difficult or time-consuming writing a hook to fit our specific use case could be a good use of our time, but we should let others (@njordhov especially) give their input as well!

**Comment by tylerd92** [comment]
I started digging into how I could use redux with hooks, but I found out that you can use React Redux hooks to get part of the [state](https://thoughtbot.com/blog/using-redux-with-react-hooks). You can use hooks to replace connect mapStatToProps
