### ISSUE TITLE
login screen should not have navbar

### ISSUE THREAD

**Issue by sedmo** [COVID-19-electronic-health-system/Corona-tracker#42]
the functionality for the user to do things like talk to the doctor cannot be done if they are not logged in. WIll need to change by removing or disabling user only features.

You can use the map or settings but cannot use the health log or the talk to a doc feature.

**Comment by sedmo** [comment]
There can be a future distinction between user specific features and more generic ones.

Settings, map, and news are not user specific whereas health log and talk to a doc are.

**Comment by SomeMoosery** [comment]
Are you seeing the navbar in the login screen running locally now? Or just in the wireframe? I agree that some features should be available without authentication with Blockstack, but for the time being I hadn't added in the NavBar to the login page unless someone else did or something got messed up?

**Comment by tesla809** [comment]
Na, it's not in the code running locally. The issue I think is related to the wireframe.

**Comment by tesla809** [comment]
Code is looking great so far though @SomeMoosery

**Comment by SomeMoosery** [comment]
Closing this as the UI for Login doesn't have the nav bar
