### ISSUE TITLE
Move survey upload to thunk

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#424]
## Summary

- [ ] move our survey submission to a Redux thunk

## Motivation

Should errors occur reading/writing to Gaia it will protect stability of the app, since the error will be "caught" in the thunk and not passed along to live components. It will also make it easier to debug should these errors occur (credit @Afrogrrrl for the great description)

**Comment by Afrogrrrl** [comment]
I can take this
