### ISSUE TITLE
Setup global fonts and screen breaking points

### ISSUE THREAD

**Issue by AdhamAH** [COVID-19-electronic-health-system/Corona-tracker#427]
## May block issues:
#422 #418 #402

## Plan
- [ ] Setup the fonts globally to be used with the help of @BrianHHough 
- [ ] Setup breaking points also globally using Material-UI
- [ ] Update the styling guide to how to use 
### Motivation:
- start using the fonts to better reflect the wireframes
- Make a united setup for everyone which make it easier to debug and prevent conflict between components as everything following the same setup

## Alternative
leave it as it is so it is added in every component spritely

**Comment by AdhamAH** [comment]
I can start working on it as soon as agreed to move forward with it

**Comment by SomeMoosery** [comment]
Great idea, this will definitely help scale number of features more organically! And I'd say yeah, I'll put blockers on those 3 tickets as we should handle the global break points first before updating the styling so we don't risk having repeat work 👍
