### ISSUE TITLE
FAQ and getting started Guide for Analytics Team (OpenMined + PyTorch + other tools)

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#432]
## Summary
To start to onboard and scale the analytics team, we need a "Getting Started Guide" with FAQ section for the analytics team. It will be linked to our CONTRIBUTING.md and README.md

This will help point new devs to the right area and get started with minimal help.

Deliverables:
1. Call the document ANALYTICS-GETTING-STARTED.MD or something along those lines.
2.  Have a FAQ section with commonly asked questions
3. Have a setup guide. See CONTRIBUTING.md for inspiration. 
4. Have a resources guide.
5. Have it in Coronanalytics repo and in CoronaTracker repo.
6. Link CoronaTracker's README.md and CONTRIBUTING.md to the document
7. Have a style guide on what is good code: Keep it PEP8 or an agreed-upon standard.
8. Mention the team lead's discord handle and github.
9. Add the "How Can I Contribute?", "Values", "Townhalls", and "Background" Sections from CONTRIBUTING.md at the top.
10. Links to learn about PyTorch and Openmined.

See an example from [airbnb engineering](https://github.com/airbnb/knowledge-repo) 

## Motivation
Why are we doing this? 
We want to:
1. Increase the retention of the analytics devs that onboard.
2. Have all the devs on the same page and understand the team and its goals
3. A clear and straight forward contribution workflow
4. Clear standards for what is good work

What use cases does it support? 
Developing the analytics team, helping everyone to be on the same page, and scaling it.

What is the expected outcome? 
New Devs on the analytics team will be able to get started on 
a) learning the stack
b) get the answer for their most common questions
c) know the contribution workflow for the team
d) know how to submit code, create tests, etc
e) be self-sufficient to start to contribute with little repetition from analytics lead.

## Describe alternatives you've considered
Keep repeating the same things to people? Not a sustainable or scalable. We have learned from scaling the front end dev team on how to have a good workflow that scales.

**Comment by whoabuddy** [comment]
Closing in favor of [#1 in Coronalytics repo.](https://github.com/COVID-19-electronic-health-system/Coronalytics/issues/1)

I moved all the remaining tasks and information there.
