### ISSUE TITLE
Implementing Share Buttons in app and on website

### ISSUE THREAD

**Issue by BrianHHough** [COVID-19-electronic-health-system/Corona-tracker#433]
## Summary

Either www.sharethis.com or a bit of JavaScript to enable easy sharing / pre-drafted social posts that auto-populate in social channels (Twitter, Facebook, LinkedIn) and help to amplify our app to other people so they can share this on social.

## Motivation

To help make our app more viral/marketable.

## Describe alternatives you've considered

www.sharethis.com or Javascript code

## Additional context

make buttons with pre-drafted posts so its easy for users to share the app/their experience directly to social media/online!

**Comment by BrianHHough** [comment]
<img width="1105" alt="Screen Shot 2020-04-07 at 10 59 09 PM" src="https://user-images.githubusercontent.com/56947075/78739954-6a275400-7923-11ea-9022-683db8f90cd4.png">

**Comment by pavel-ilin** [comment]
I can take this one. Not be ready for todays beta release, but I'm sure I can crack it.

**Comment by SomeMoosery** [comment]
No prob! 4/10 was really an internal goal, and the press release has been pushed from 4/15-4/17 so there's time :)
