### ISSUE TITLE
Calendar language should match the language selected by user 

### ISSUE THREAD

**Issue by liadove** [COVID-19-electronic-health-system/Corona-tracker#438]
### Description

Right now the calendar is on Russian, but instead, it should correspond with the language user chose when was logging in.

### Suggestions

1. Leave one language, but set it to English
2. Make it corresponding to the user language

**Expected behavior:**

The calendar should be on language user know

**Actual behavior:**

The calendar is only on Russian

**Reproduces how often:**

100%

### Versions

0.3.8

![image](https://user-images.githubusercontent.com/43704877/78839413-6f89aa80-79c6-11ea-97f3-756f81c57b8f.png)

**Comment by liadove** [comment]
@pavel-ilin what do you think?

**Comment by AdhamAH** [comment]
I don't get it 
it is here the other way around
![Screenshot 2020-04-09 at 00 53 25](https://user-images.githubusercontent.com/55054963/78841083-c27e5480-79fc-11ea-80cb-0ba1c3b38950.png)

in any case this should be handled from `react-calendar` locale setting I think

**Comment by liadove** [comment]
@AdhamAH ohh, that's interesting I still have Russian everywhere. Maybe it's something in my settings then. 
When you set English as the language does it show the calendar in English?
![image](https://user-images.githubusercontent.com/43704877/78842267-90a1c980-79cd-11ea-9456-0fad046ef4c8.png)

**Comment by AdhamAH** [comment]
@liadove yes it does and actually it is always English. Maybe the system setting of your computer and mine?

**Comment by SomeMoosery** [comment]
Hmm... yeah this seems like it's been a bit of snag with those who have or have had their phones set to different languages... and I think especially so with Russian because of the different alphabet used. Could definitely use some further investigation.

I personally haven't had any issues on my end when changing languages, but that's because I've only ever lived in/around NYC 😆

**Comment by pavel-ilin** [comment]
I just switch languages several times and calendar stays in English every time. I test Russian as well as every other language.

I believe that calendar library follows the language scheme our OS using.

**Comment by SomeMoosery** [comment]
Is there a verdict on this? Is this something that needs to be worked on - or can we close this?

**Comment by liadove** [comment]
@AdhamAH  My laptop set to English but maybe somewhere in my settings I have Russian 😅
@SomeMoosery I think we still need it in the future for different languages. But if it works in English on your end then it's good for now. Maybe we can leave this as a long-term?

**Comment by pavel-ilin** [comment]
I test calendar with several users in Russian and 100% report that they have calendar in Russian. 

I stick to the hypothesis that Calendar library tracks OS primary language.

I think we can close the issue.

**Comment by SomeMoosery** [comment]
Sounds good! We can always create a new issue if this pops up again :)
