### ISSUE TITLE
Discuss Deployment Methodology

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#44]
So I've had a few ideas regarding this, and I'm adding this issue as a Long-Term Change for when the time comes. At a certain point, we'll want to bring this application live, and need a good way to do that. I'm a fan of AWS and have my Certified Solutions Architect certificate (although I got it a while back, and am definitely not super experience with building distributed systems from scratch myself). But, I am relatively comfy with AWS.

I've been thinking of a general architecture that we could use, which I'll attach to this issue when I draw it out. Just adding this here for a placeholder/discussion issue for the time being.

**Comment by tesla809** [comment]
Amazon sounds good to me. They have great support and will probably donate credits to us. And if you are certified to do it, then let's go with that. Easier to deploy.
