### ISSUE TITLE
Button highlighting not working on page 1 of survey

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#445]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Button does not highlight properly on Page 1 of the survey. Could potentially be fixed by whoever fixes #444 too.

<img width="789" alt="Screen Shot 2020-04-08 at 8 55 16 PM" src="https://user-images.githubusercontent.com/15767602/78934073-4de8fb80-7a78-11ea-938e-d409a1127e61.png">

### Steps to Reproduce

1. Login
2. Take Survey
3. Select page 1 answers

**Expected behavior:**

Button highlights in a similar fashion to all other buttons on app

**Actual behavior:**

Button stays transparent and highlights text yellow

**Reproduces how often:**

100%

### Versions

0.3.9

**Comment by AdhamAH** [comment]
this and #444  I've could do them when I fixed the scroll I thought you wanted them like that. I should have asked you, my bad!
