### ISSUE TITLE
Survey Page 1 Q1 displays inline to headers on larger screens

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#446]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

<img width="1390" alt="Screen Shot 2020-04-08 at 8 55 01 PM" src="https://user-images.githubusercontent.com/15767602/78934224-8f79a680-7a78-11ea-9faf-e5368301a80a.png">

**We probably just need an additional `<Grid>` to solve something like this!**

### Steps to Reproduce

1. Login on a large monitor
2. Navigate to survye

**Expected behavior:**

Survey displays the same as on all screen sizes

**Actual behavior:**

The question is inline with other components

**Reproduces how often:**

100% on larger screens

### Versions

0.3.9

**Comment by acthelemann** [comment]
Fixed in [this PR](https://github.com/COVID-19-electronic-health-system/Corona-tracker/pull/439).

**Comment by AdhamAH** [comment]
on the suggestion from @acthelemann I also prevent it the slider from stretching all the width in [this PR](https://github.com/COVID-19-electronic-health-system/Corona-tracker/pull/440)
