### ISSUE TITLE
Wording of question 3 on Survey Page 1 was missing word "to"

### ISSUE THREAD

**Issue by Josh1794** [COVID-19-electronic-health-system/Corona-tracker#447]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description
Survey page 1 Q3 was worded poorly/Incorrectly

Original Text: How are you feeling compared yesterday
New Text: How are you feeling compared **to** yesterday
### Steps to Reproduce
N/A
1. 
2. 
3. 

**Expected behavior:**
Fixed wording

**Actual behavior:**
poor wording

**Reproduces how often:**
100%

### Additional Information
I have a branch created that fixes this

**Comment by SomeMoosery** [comment]
Hi Josh, will you be working on this? Or are you just filing the issue? Just want to be sure we're not duplicating work

**Comment by Josh1794** [comment]
Id be happy to take care of it, it will be my first open source contribution so just trying to learn the system

**Comment by SomeMoosery** [comment]
Happy to have you on board! No worries at all, this is a great place to learn 👍

**Comment by Josh1794** [comment]
Thanks so much super excited to help out I joined the discord as well
