### ISSUE TITLE
Mathematical Modeling of Disease

### ISSUE THREAD

**Issue by jmsmdy** [COVID-19-electronic-health-system/Corona-tracker#45]
It's often possible to mathematically model the spread of a disease given a few parameters. It might be helpful to use this to give a risk assessment to people based on their geographic location and other data we collection about the disease. More information about the basics of mathematically modeling disease spread can be found [here](https://en.wikipedia.org/wiki/Mathematical_modelling_of_infectious_disease).

**Comment by ngiangre** [comment]
closing - we are not considering modeling disease with our current versions and scope
