### ISSUE TITLE
Create Quick Overview section under Getting Started section in CONTRIBUTING.MD

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#453]
## Summary
In a section called "Project Overview" which will be under to "Getting Started" section, 
let's add an overview of the project with
1)  Schematic of architecture from pitch deck
2) Summerize the project again
3) A quick summary of Blockstack,
   a) how it's used, 
   b) definitions for terms and tools (Gaia, Radiks, Secret Key, etc.) or links to them
   c) relevant links to get started
4) Links to get started with AWS 
5) Links to get started with MongoDB
6) Links to MaterialUI, React, Jest Documentation
7) Link to Notification repo 
8) Links to get started with GoLang

## Motivation
Why are we doing this? 
We want users to understand the overview of the project and have resources to learn how to contribute

What use cases does it support? 
Helping to lower barrier to entry and improve the developer experience to contribute

What is the expected outcome?
More contributions across the entire stack.

## Describe alternatives you've considered
Keep repeating what is Blockstack, other tech and its uses to people. However, this is not scalable.

## Additional context
None.

**Comment by bcsaxon** [comment]
Hi! new here. I'd like to try to tackle this one if no one else has claimed it yet?

**Comment by SomeMoosery** [comment]
All you - feel free to join the Discord (linked in README) and reach out to @whoabuddy if you need additional context! He has been doing a great job refactoring/refining our docs

**Comment by bcsaxon** [comment]
Sounds good! thank you!

**Comment by whoabuddy** [comment]
Closing in favor of [#2 in the .github repo](https://github.com/COVID-19-electronic-health-system/.github/pull/2)
