### ISSUE TITLE
Use Redux store to get observations instead of fetching

### ISSUE THREAD

**Issue by acthelemann** [COVID-19-electronic-health-system/Corona-tracker#454]
## Summary

Use Redux store (observations reducer) to get the list of observations instead of fetching them using Blockstack in the `Table` and `Chart` components.

- [x] Use Redux store to get observations in the `Table` component
- [x] Use Redux store to get observations in the `Chart` component

## Motivation

When navigating to the "Show Me More" screen the components fetch the observations twice instead of using the Redux store, which slows down the app.

## Describe alternatives you've considered

Leaving it the way it is.

**Comment by njordhov** [comment]
The difference is pre-fetching the observations initially vs fetching them on demand, right? Consider a combination (more like a proxy) to avoid the initial delay of having to pre-fetch all observations as their number grows.

**Comment by fallon7284** [comment]
I think, if I understand the issue, the difference is fetching them once and not having to re-fetch them every time we render a component that needs them.

**Comment by acthelemann** [comment]
Exactly, @fallon7284.

Currently, we fetch them all on initial app load and put them in the store. They're all there, so there's no need to fetch them again when we go the "Show Me More" screen.
