### ISSUE TITLE
Yes/no onboarding questions not free inputs

### ISSUE THREAD

**Issue by acthelemann** [COVID-19-electronic-health-system/Corona-tracker#455]
## Summary

Make the yes or no questions on the onboarding form not free inputs.

Options:

- Yes and no buttons
- Dropdown

- [ ] Make the "Do you smoke?" question not a free input
- [ ] Make the "Do you have obesity?" question not a free input
- [ ] Make the "Do you have asthma?" question not a free input

## Motivation

Free inputs on yes or no questions allow the user to input anything. We should restrict their answers to what we expect.

**Comment by JWaltuch** [comment]
I can take this

**Comment by acthelemann** [comment]
You got it!
