### ISSUE TITLE
Bug in More component, singout button text

### ISSUE THREAD

**Issue by AdhamAH** [COVID-19-electronic-health-system/Corona-tracker#462]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description
When the keyboard pop up the size becomes very small and the yet get out of the button 

![bug](https://user-images.githubusercontent.com/55054963/79026923-985a9d00-7b8a-11ea-96a9-0f2230376c53.gif)

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**
text inside the button

**Actual behavior:**
text outside

**Reproduces how often:**
100% when small size applied 

### Versions
0.3.16

### Additional Information
none

**Comment by mamutahr** [comment]
I am also able to replicate this on all buttons in the more section on desktop by making the window very small.
![image](https://user-images.githubusercontent.com/36338290/79030568-9af7cb00-7b67-11ea-8df8-24026b468be4.png)
Is it alright if I try working on this issue for a bit?

**Comment by SomeMoosery** [comment]
All you 👍
