### ISSUE TITLE
Flashcards need to be better positioned for all screen sizes

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#465]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Flashcards are displayed too highly, blocking text

<img width="307" alt="Screen Shot 2020-04-10 at 10 23 04 PM" src="https://user-images.githubusercontent.com/15767602/79033172-f59a2280-7b79-11ea-8a59-c34c81e89ceb.png">

### Steps to Reproduce

1. Log in
2. Go to flashcards

**Expected behavior:**

- [ ] Flashcards are centered in screen and fit between top-level components such as the logo at the top, and bottom nav
- [ ] Text is changed to remove "TODOARROW" and replace with something more fitting

**Actual behavior:**

Flashcards are too high

**Reproduces how often:**

100%

### Versions

0.3.16

**Comment by petesamper** [comment]
I can take this

**Comment by SomeMoosery** [comment]
All you! If you'd like to be actually assigned on the ticket, I sent you an invite to the org as well 👍

**Comment by AdhamAH** [comment]
I should have been faster but time man!
@SomeMoosery @petesamper 
this an issue is that more card stacked now, not padding or margin issue because if you add that the card will look normal in less long screens(say  Samsung S9, iPhone 5s) but if you keep swiping some of the lastest cards will be under the navbar. 
we might need to look into the whole style/motion of the cards

**Comment by BrianHHough** [comment]
I did a screenshare user test and they were having the same issue where the cards were cut off on the bottom by the bottom nav. Any way we could create a container for the cards to fit between the top text and bottom nav bar?

**Comment by BrianHHough** [comment]
Also @AdhamAH do you think you could adjust the text at the top to say "Swipe to the right or left to learn more about COVID-19" and then remove that typo that's in all caps?

**Comment by SomeMoosery** [comment]
I'll add changing the text as an acceptance criteria for this ticket, and change the context of this ticket to fit more with making sure the flashcards are more just scaled / centered in any screen 👍

**Comment by petesamper** [comment]
Hey all, sorry for the delay. I know this is a simple issue so I apologize.

I gave the flashcards container a margin property (changed from marginTop in my PR) with the expectation that it would prevent the flashcards from touching the navbar on bottom. I know @AdhamAH mentioned this may just be an issue with the animations themselves, particularly when the last cards in the decks are reached, but I haven't had any luck adjusting the animations, so I left them alone.

I'm having trouble logging in on mobile to test my changes there, so I haven't been able to recreate the issue on mobile to see if my changes look alright. 

That said, here is a screenshot of it on my machine, on the last flashcard, with no issues:

Again sorry all, I am a noobie :sweat_smile:.

![Screen Shot 2020-04-11 at 6 54 33 PM](https://user-images.githubusercontent.com/53917594/79056649-a65dfb80-7c26-11ea-93ee-0876f76252ae.png)

**Comment by SomeMoosery** [comment]
While it's not perfect, [you can use Chrome Devtools to simulate mobile environments!](https://developers.google.com/web/tools/chrome-devtools/device-mode#viewport) 

No worries, take your time! We'd rather have something great than something only partially fixed :)

**Comment by petesamper** [comment]
Whoa, didn't know about that. Alright I'll use that for now and get back to you when I have results. I'll fix this! :muscle:
