### ISSUE TITLE
Location of Navigation Bar on Screen Relative to Content

### ISSUE THREAD

**Issue by salvolpe** [COVID-19-electronic-health-system/Corona-tracker#468]
On my screen in the survey, I can't get out of it and up back on the homepage because I believe that the `Continue` button is lost underneath the navigation bar on page 2.

<img width="735" alt="image" src="https://user-images.githubusercontent.com/37944330/79049556-5107f700-7bf2-11ea-82ec-32b96b770a4b.png">

As you can see, there's a similar problem on the `About` page, where it looks like the text is actually sitting below the bar:

![image](https://user-images.githubusercontent.com/37944330/79049590-83195900-7bf2-11ea-9c26-4bb348df0146.png)

**Comment by AdhamAH** [comment]
What's the size of the screen? It happened to me once and I didn't have the latest update, are you sure your fork updated to the latest comment?
because I think this issue already fixed and actually refixed

**Comment by salvolpe** [comment]
@AdhamAH I had just been working on this link that was sent out a while ago and didn't know if updates were being pushed to this URL or not: coronatrackerv1.s3-website-us-east-1.amazonaws.com/

I had not been running it locally, but I can go through that again

**Comment by AdhamAH** [comment]
@salvolpe there are many things added and fixed that are not in coronatrackerv1.s3-website-us-east-1.amazonaws.com/  and this one of them
So I will close this and let me know if you find anything else
