### ISSUE TITLE
Button Functionality in "More" Tab

### ISSUE THREAD

**Issue by salvolpe** [COVID-19-electronic-health-system/Corona-tracker#469]
If I click on `More`, I have to click specifically on the text in order to advance myself to the screen of interest. This applies ONLY to `Settings` and `About`. It works perfectly fine for `Sign Out`, i.e. I can click anywhere on that button and it will sign me out.

[![Image from Gyazo](https://i.gyazo.com/8ab943d62c0acde7ff152be3b4b0a82a.gif)](https://gyazo.com/8ab943d62c0acde7ff152be3b4b0a82a)

**Comment by AlexRAV** [comment]
Hi! I can take it.
