### ISSUE TITLE
Update Gender Labels in Settings Screen

### ISSUE THREAD

**Issue by salvolpe** [COVID-19-electronic-health-system/Corona-tracker#470]
Currently, the only two options for genders are _Male_ and _Female_. We should either be adding a third button for _Non-Binary_ or, something that could be much more dynamic, turn it into a dropdown menu in case we add more in the future (e.g. genderqueer, gender-fluid, **trans male, **trans female). 

**The last two should only be added if we think that, for analytical purposes, knowing their sex-assigned at birth will be relevant. At the moment, it is not so we don't need to have that.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/37944330/79049903-5a925e80-7bf4-11ea-9aab-6612ea4e8363.png">

**Comment by kevin-Price** [comment]
Ill pick this one up.
