### ISSUE TITLE
Update static images to reference S3 bucket

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#472]
## Summary

Image links are of this format:

`https://dg1fd6ea8poyj.cloudfront.net/images/<FILE_NAME>`

Where <FILE_NAME> is the file name found in the client/src/img directory.

Example:

https://dg1fd6ea8poyj.cloudfront.net/images/Logo_CORONATRACKER_Logo.svg

- [ ] Use S3 image links in our React app, instead of hardcoded references
- [ ] Remove references to images from our `client/src/img` directory

## Motivation

This will result in a smaller build file and potentially faster load times for www.coronatrackapp.com

## Describe alternatives you've considered

Leaving the images where they are now

**Comment by pavel-ilin** [comment]
Can take on this one. 

All images in "coronatracker-media-assets" bucket, correct?

**Comment by SomeMoosery** [comment]
I believe so, I'll just double check with @acthelemann

**Comment by acthelemann** [comment]
@pavel-ilin You got it!

**Comment by acthelemann** [comment]
@pavel-ilin I just set up a CDN for our images so the URL is different now. Use the following:

`https://dg1fd6ea8poyj.cloudfront.net/images/<FILE_NAME>`

Where <FILE_NAME> is the file name found in the client/src/img directory.

Example:

https://dg1fd6ea8poyj.cloudfront.net/images/Logo_CORONATRACKER_Logo.svg

**Comment by pavel-ilin** [comment]
@acthelemann Got it! Working on that.
