### ISSUE TITLE
days selection on the calendar to match the design 

### ISSUE THREAD

**Issue by AdhamAH** [COVID-19-electronic-health-system/Corona-tracker#474]
## Summary:

- Update the styling for the day's selection in `Calendar.jsx` to match the wireframes. We can use the images provided by @BrianHHough in `/client/src/img`
- remove any weird or bugs related to the `Calendar.css`file 

## Motivation:

Better design and better user experience

## Describe alternatives you've considered
This needs to be done.

**Comment by SomeMoosery** [comment]
What do you mean by the styling for the day's selection? I think the way we have it should be good for now, no?

It's up to @BrianHHough - but I don't think we necessarily need to circle elements and could highlight them instead, as we have now. Thoughts?

**Comment by AdhamAH** [comment]
I thought we needed it before the 15/4, I will close it as it can wait

**Comment by AdhamAH** [comment]
Waiting for v3

**Comment by AdhamAH** [comment]
I thought we needed it before the 15/4, I will close it as it can wait
