### ISSUE TITLE
Which types of temperature measure do we use? 

### ISSUE THREAD

**Issue by ahmadtechnik** [COVID-19-electronic-health-system/Corona-tracker#478]
This is logical Issue, the user have to know in which temperature measure should enter the value.

![image](https://user-images.githubusercontent.com/50963733/79070307-44a89a80-7cd5-11ea-8b05-2f724e0d44a8.png)

## Summary
To make the user able to understand what number is gonna to enter. There is 5 different kind of temperature measurements out there.
## Motivation
Better UX 
## Describe alternatives you've considered
either create new selection menu to choose the kind of temperature measurements or add small sign beside the input field.

**Comment by SomeMoosery** [comment]
Good point - as this will be US-based first, let's use Fahrenheit for now
