### ISSUE TITLE
Change health log view on large screens

### ISSUE THREAD

**Issue by AdhamAH** [COVID-19-electronic-health-system/Corona-tracker#485]
## Summary
The calendar looks wired and big on a large screen 

## Motivation
Make it look better in my opinion 
![Screenshot 2020-04-13 at 14 13 18](https://user-images.githubusercontent.com/55054963/79119583-f953c200-7d90-11ea-912c-a49da0b5518e.png)

## Describe alternatives you've considered
leaving it  as it is

**Comment by SomeMoosery** [comment]
I like that! Should we mark as "help wanted" or are you on this?

**Comment by AdhamAH** [comment]
I will do the PR now
