### ISSUE TITLE
Set up Cloudfront CDN for S3 site

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#488]
## Summary

- [x] Create a Cloudfront CDN for our S3 site

## Motivation

- Allows HTTPS
- Improves performance

**Comment by acthelemann** [comment]
I used just about all of the default settings.

Some things to consider for the future:

* Custom domain name
* Logging accesses
* Confirm price class
  * I selected **All Edge Locations** for best performance, but will increase costs
  * https://aws.amazon.com/cloudfront/pricing/
