### ISSUE TITLE
Create a form/way for users to provide feedback

### ISSUE THREAD

**Issue by kevin-Price** [COVID-19-electronic-health-system/Corona-tracker#489]
Summary
We need a way to capture user feedback to help drive new stories/refactors.
- [ ] Set up a User feedback page/popup of some form 

Motivation
We want to be able to get insights into what pain points our users are experiencing so that we can improve them.

**Comment by SomeMoosery** [comment]
Great point, I was actually meaning to write out stories for this as well as analytics today! Would you be willing to scope out an issue for this with acceptance criteria for this feedback system (I think a star system in the More popup could work well for now)?

**Comment by kevin-Price** [comment]
I can definitely do that! I'll write up a user story and attach it to the issue. Im not sure how valuable a star rating is by itself. The purpose here is to capture user feedback in order to drive meaningful changes. TBH, Im not even sure if the star rating is going to be valuable at all in this case -- I should probably take it out. Google store and app store use the star rating to help _other users_ decide whether they should use an app or not. Whereas here we want detailed feedback that can be turned into stories.

**Comment by SomeMoosery** [comment]
Exactly - definitely reach out to @nathanboone as he's been doing great work writing user stories already 👍

**Comment by ngiangre** [comment]
@SomeMoosery if the beta survey is properly linked, does that close this issue?

**Comment by SomeMoosery** [comment]
Good call @ngiangre - yeah, I'd say that covers it so we can close this 👍
