### ISSUE TITLE
3/17/20 @ 6:30pm- Meeting with Dr. Jigna Zatakia- Assistant Professor in Pulmonary Critical Care Medicine at Baylor College of Medicine

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#49]
Details here:
Meeting with Dr. Jigna Zatakia- Assistant Professor in Pulmonary Critical Care Medicine at Baylor College of Medicine
https://www.linkedin.com/in/jigna-zatakia-2734b333/

Topic: Coronatracker <> Dr. Jigna Zatakia
Time: Mar 17, 2020 06:30 PM Eastern Time (US and Canada)

Join Zoom Meeting
https://us04web.zoom.us/j/789835902

Meeting ID: 789 835 902

One tap mobile
,,789835902# US Toll

Dial by your location
         US Toll
        
Meeting ID: 789 835 902
Find your local number: https://us04web.zoom.us/u/fWebnPsa

**Comment by SomeMoosery** [comment]
[Notes from Call](https://docs.google.com/document/d/1u_DLPah3SuENQZa9MUJBPKNPeOGK1_MGKrY2TazEN80/edit) - feel free to add to this!
