### ISSUE TITLE
On Education Quiz section should be changed to True or False (Currently "False or True")

### ISSUE THREAD

**Issue by Josh1794** [COVID-19-electronic-health-system/Corona-tracker#490]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description
Wording on Quiz in education section is a bit clunky should be True or False 

### Steps to Reproduce

1. Navigate to Education
2. Go to Quiz Section
3. Read

**Expected behavior:**
Change wording to "True or False"

**Actual behavior:**
Currently "False or True"

**Reproduces how often:**
100%

**Comment by Josh1794** [comment]
I can work on this

**Comment by Josh1794** [comment]
Should I also change the direction you drag for true or false to match the words?

**Comment by SomeMoosery** [comment]
Yes to both! Good suggestions

**Comment by Josh1794** [comment]
Would you happen to know where the swipe functionality is I cant find it
