### ISSUE TITLE
Log health slider more options needs too much sliding on large screens

### ISSUE THREAD

**Issue by acthelemann** [COVID-19-electronic-health-system/Corona-tracker#495]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

The log health slider needs to be moved too much to show more options on large screens.

### Steps to Reproduce

1. Use a screen size >= 839px
2. Go to Calendar page
3. Drag slider just past the vertical bar
4. See that the slider doesn't stay past the vertical bar

**Expected behavior:**

Slider stays past the vertical bar when dragging it just past the vertical bar.

**Actual behavior:**

Slider returns back to its original position when dragging it just past the vertical bar.

**Reproduces how often:**

100%

### Versions

0.3.24

### Additional Information

![log-health-slider-bug](https://user-images.githubusercontent.com/16993949/79180977-507d8500-7dd9-11ea-853d-8b3cf271f16e.gif)

**Comment by PhurbaSherpa** [comment]
Could I work on this issue, it will be my first contribution?

**Comment by SomeMoosery** [comment]
Yup, all you!
