### ISSUE TITLE
Create "Delete All User Data" functionality 

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#497]
## Summary

- [ ] create button in onboarding underneath "Delete All Observations" (once #496 merges in) asking if user wants to delete all user data - with an appropriate notice
- [ ] add functionality to delete all user data (disclaimer status, onboarding data, etc) based off of @JWaltuch changes #496 

## Motivation

Certain states' and countries' laws give individuals the right to be forgotten - and we want to comply with that. So, we should allow the user a way to delete all of their user data if they so wish. This is also a good faith measure as an open-source, individual-empowering initiative.

**Comment by Afrogrrrl** [comment]
I think this is an interesting one, definitely want to give it a try. Is this needed by tomorrow?

**Comment by SomeMoosery** [comment]
We've moved the release back to Friday, so just by Friday would be great!

**Comment by fallon7284** [comment]
https://blockstack.github.io/blockstack.js/classes/usersession.html#listfiles

**Comment by Afrogrrrl** [comment]
question about styling here, I'm thinking we might not want the delete buttons to be too similar? This is how it looks now 

![image](https://user-images.githubusercontent.com/53954135/79475377-9737ce80-7fd5-11ea-8ac8-eda4dc0b4ff5.png)

I think the delete all user data button should be how it is but maybe the delete observations button should be an in-between. Perhaps a blue background with red lettering? Just something a little less severe. would love input on this from UX

**Comment by Afrogrrrl** [comment]
It just seems like with these two delete buttons a user might not exactly know what is the difference/purpose between them

**Comment by acthelemann** [comment]
Maybe this is too involved for this issue, but one button that says something like "Manage My Data" which opens a pop-up that has a checkbox for "Survey data" and "All data". The "All data" checkbox should check "Survey data" automatically. This would also prepare for more fine grain data deletion options

**Comment by whoabuddy** [comment]
I'd go the simple route for the bottom button as a quick fix: "Delete All Data".

Otherwise it's hard to differentiate what is observation data vs user data, and might not imply their linked?

Plus more buttons could be added and/or a popup modal created in v2 per @acthelemann's point in a future release.

**Comment by Afrogrrrl** [comment]
Yeah I like the idea of having a "Manage My Data" modal and it can go into details on the different options there. I guess for now I'll call the button Delete All Data and leave the styling as is?

**Comment by SomeMoosery** [comment]
I agree, I'd say yeah for now this is good! Maybe create a PR for this so we can have it in by tonight / tomorrow morning, and then we can open up another issue for the modal?

**Comment by Afrogrrrl** [comment]
I should be done with it by tonight. Also wanted to clarify on what's being deleted - does delete all observations already clear out gaia? if not, what other info needs to be deleted in gaia? also, does it need to clear out the rest of the redux store?

**Comment by SomeMoosery** [comment]
This should delete everything, not just observations (so all `.json` file we have - disclaimer, demographics-comorbidities, etc) 👍
