### ISSUE TITLE
Update README to reflect first steps, tech stack

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#5]
Update the README in order to reflect discussion from previous issues and in the Discord.

- What our tech stack is
- The main feature we want to complete for our IPR early next week

Reformat the README in order to emphasize the things we're working on and de-emphasize the things that come after the IPR.

**Comment by tesla809** [comment]
Looking good so far. @tesla809 will add answer to TD;LR for FAQs section.
