### ISSUE TITLE
3/17/20 @ 1:30pm Project overview with Flatiron School alums to get front end help

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#50]
3/17/20 @ 1:30pm Project overview with some Access Labs, Flatiron School alums to get front end help.

See: 
https://wework.zoom.com/j/5921238737

**Comment by johnemurphy1** [comment]
ok if i join this call?

**Comment by SomeMoosery** [comment]
Unfortunately can't join this call as it's during my work hours. @johnemurphy1 I'm sure that would definitely be useful - the more help and input, the better!

**Comment by tesla809** [comment]
@johnemurphy1 Everyone is welcomed! for sure! Thanks for joining!
