### ISSUE TITLE
Weekly tracker ratings out of 5

### ISSUE THREAD

**Issue by acthelemann** [COVID-19-electronic-health-system/Corona-tracker#500]
## Summary

The `WeeklyTrackerDay` component displays values out of 10 when the survey rates on values out of 5.

- [ ] Make the "You said you felt" rating out of 5
- [ ] Make the "Symptoms" rating out of 5

## Motivation

Make the weekly tracker align with the survey.

## Describe alternatives you've considered

Make the ratings in the survey out of 10.

**Comment by petesamper** [comment]
I'll take this

**Comment by acthelemann** [comment]
You got it!

**Comment by petesamper** [comment]
To be sure, just changing the 10 to a 5 for both "You said you felt" and "Symptoms", right? Nothing else?

**Comment by acthelemann** [comment]
Yeah, bonus points if you find other places to change it.

**Comment by petesamper** [comment]
In the Table component, under 'Overall feeling". Just says the number. Could add "/5" to it if you'd like.

**Comment by acthelemann** [comment]
Sounds good to me

**Comment by petesamper** [comment]
Cool. PR coming in shortly.
