### ISSUE TITLE
Update notifications subscription service to hit current API Gateway

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#502]
## Summary

- [ ] update the text input where you subscribe to text updates to our current API Gateway URL for the `subscribe` lambda

## Motivation

We want to have users be able to subscribe to notifications by Friday's beta launch

**Comment by pavel-ilin** [comment]
I can take on this one. Although, I can't see `subscribe` lambda service. Only `coronalert-unsubscribe`.

**Comment by SomeMoosery** [comment]
Make sure you're in `us-east-1` (N. Virginia)

**Comment by acthelemann** [comment]
@pavel-ilin Here's an example `curl`:

```sh
curl --location --request POST 'https://kplh25sfce.execute-api.us-east-1.amazonaws.com/default/coronalert-subscribe' \
--header 'Content-Type: application/json' \
--data-raw '{
	"phoneNumber": "+12346578910"
}'
```

**Comment by pavel-ilin** [comment]
Got it! Thank you!
