### ISSUE TITLE
Create QA client in CoronaTracker AWS

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#504]
## Summary

- [ ] Create a new S3 bucket containing the most up-to-date copy of the site
- [ ] Share this with the community, preferably pinning it in large Discord groups and potentially adding it to the README (reach out to @whoabuddy for this)

## Motivation

While longterm we may look to add more environments with separate test backends and all, but for the time being, a simple separate client where we will deploy in order to test functionality before deploy to should will suffice.

This also fully removes my personal AWS from the picture.

## Describe alternatives you've considered

Waiting until we have a separate QA/Staging backend in order to implement this, but we really should have somewhere to test the client as that's currently the most heavily-under-development aspect of CoronaTracker

**Comment by pavel-ilin** [comment]
If no one working on this, I can take it.

**Comment by SomeMoosery** [comment]
All you - this is much needed and shouldn't be that hard!

Some steps to take after creating the S3 bucket for this if you haven't already would be 
1. Set up the `aws` [CLI](https://aws.amazon.com/cli/)
2. Configure it with `aws configure` and your access codes

And then you can just 
1. build the react file `yarn run build`
2. sync it with S3`aws s3 sync build/ s3://<BUCKET-NAME>`

**Comment by pavel-ilin** [comment]
App build successfully deployed on s3 bucket.

Initially build has failed. Here the error:
![](https://i.ibb.co/smhwBRv/Screen-Shot-2020-04-15-at-4-33-04-PM.png)

After brief research I learn that we should add `@babel/compat-data` to dev dependencies. When I add it and build was successful.
