### ISSUE TITLE
Possible opportunity 

### ISSUE THREAD

**Issue by ngiangre** [COVID-19-electronic-health-system/Corona-tracker#51]
Hi everyone, I've been watching your developments over the last few days and I have to say remarkable teamwork! There is considerable efforts being done to study the COVID-19 outbreak. At Columbia where I reside, the biomedical informatics department is hard at work to support the NYP-hospital system. Also, the Observational Data Science and Informatics consortium leverages real world data in a standardized data to generate evidence from data sources world wide. They are heavily working on an initiative as well. I think the data that may be captured and generated from the app being developed here could be of great use for this community. I think it is a bit early but I think @tesla809 at least should reach out to inform the consortium about the app development and possible contribution by y'all citizen scientists https://forums.ohdsi.org/t/ohdsi-virtual-study-a-thon-to-support-covid-19-response-to-take-place-26-29mar2020-collaborators-wanted/9810

**Comment by tesla809** [comment]
Can you do some investigation and write up a draft to communicate with them @ngiangre

**Comment by ngiangre** [comment]
Sure

 

Cheers,

Nick

**Comment by SomeMoosery** [comment]
Wow - that's awesome Nick! Glad to see that our progress is being recognized! I can't speak for a group opinion, but I'm certainly excited about the prospect!

**Comment by ngiangre** [comment]
closing - we are already in talks with columbia on a different effort than the one metioned
