### ISSUE TITLE
External image .jpg - access denied

### ISSUE THREAD

**Issue by pavel-ilin** [COVID-19-electronic-health-system/Corona-tracker#510]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Image ```codevscovid.jpg``` in external storage is not available. 

![](https://i.ibb.co/DCp14CL/Screen-Shot-2020-04-15-at-11-31-56-AM.png)

### Steps to Reproduce

Open url: ```https://dg1fd6ea8poyj.cloudfront.net/images/codevscovid.jpg```

**Expected behavior:**

Should get access to the .jpg file

**Actual behavior:**

Access Denied

**Reproduces how often:**

100%

### Versions

Not related to the app itself.

**Comment by SomeMoosery** [comment]
Does this happen for all files hosted in S3, or just `codevscovid.jpg`?

**Comment by pavel-ilin** [comment]
> Does this happen for all files hosted in S3, or just `codevscovid.jpg`?

Only for `codevscovid.jpg`, rest of the files, at least which I was using, working fine.

**Comment by SomeMoosery** [comment]
Hm... maybe something to look into with how S3 handles .jpg vs .png - would you be able to look into this? If not, I can later tonight

**Comment by pavel-ilin** [comment]
There was not such file as `codevscovid.jpg` in S3. I upload it there and now everything is working as it should.

I think we should add instruction for the UI contribution, to upload everything to S3 so we can have single source of truth.

**Comment by SomeMoosery** [comment]
Definitely, good catch! And I'll note that down to add to the `README` 👍
