### ISSUE TITLE
Swipe for weakly tracker and log health slider not working

### ISSUE THREAD

**Issue by AdhamAH** [COVID-19-electronic-health-system/Corona-tracker#511]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description
When trying to swipe on both sliders it doesn't redirect 
![1 0](https://user-images.githubusercontent.com/55054963/79360706-930fa080-7f44-11ea-9cde-c194f1b994b8.gif)

### Steps to Reproduce

1. Log in
2. try to swipe

**Expected behavior:**
redirect to the related destination 

**Actual behavior:**
slider goes always to the previous position 

**Reproduces how often:**
100%

### Versions
"0.3.29"

### Additional Information
if I change the files `LogHealthSlider.jsx` `WeeklyTracker.jsx` and add `!` before `swiped` in this line
```
const [{ x }, set] = useSpring(() => ({
    x: 0,
    onRest: () => {
      if (!swiped) {
        // After swipe animation finishes, navigate to survey
        history.push('/symptomsurvey');
      }
    },
  }));
```
it works
![1 1](https://user-images.githubusercontent.com/55054963/79361321-6f992580-7f45-11ea-9c29-dc841a5e1996.gif)

**Comment by AdhamAH** [comment]
@SomeMoosery if this is not meant to be, I will do a PR ASAP

**Comment by SomeMoosery** [comment]
This is happening for you on the most up-to-date master? I'm trying on my end on both mobile/desktop view and things are working fine 🤔

**Comment by AdhamAH** [comment]
I actually use GitHub desktop and always check it, it still present. I don't know 
![Screenshot 2020-04-15 at 18 31 24](https://user-images.githubusercontent.com/55054963/79362876-6ad57100-7f47-11ea-8b23-42452444c5d6.png)

**Comment by SomeMoosery** [comment]
Hm, let's see if others notice the same thing...

**Comment by AdhamAH** [comment]
@SomeMoosery I think it is only a bud on desktop. Because it is working on an actual mobile but not on the mobile port on desktop or the default view which is strange.
I made sure I am on the last commit

**Comment by AdhamAH** [comment]
@acthelemann could you help me with this? does it work on desktops? 
if so then maybe it is my setup or something.

**Comment by acthelemann** [comment]
Yeah, it should work everywhere. It's a little tricky, you need to do what is considered a swipe. It's a quick motion, it's not that your mouse/finger goes to the edge of the screen it's that you were going fast enough when you let go.

**Comment by acthelemann** [comment]
Flick of the wrist

![swipe](https://user-images.githubusercontent.com/16993949/79403001-95312980-7f5b-11ea-9a5c-993066a7211e.gif)

**Comment by acthelemann** [comment]
I think the swipe detection could be improved in the future, I just used what the library considers a swipe.

**Comment by AdhamAH** [comment]
@acthelemann thanks! yeah, I agree. I think it is really a great library but needs some workaround to fit our needs 
I will close
