### ISSUE TITLE
Add suggested topics to free response section of survey

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#514]
## Summary

- [x] for Q6, add in text encouraging users to write about a loss of smell or taste

## Motivation

We need to include the smell/taste information by Friday's release, but are taking a three-step approach to make sure we implement these changes properly:

1. Issue to just coax the user to mention things in the free text box
2. Implementing actual smell/taste buttons
3. Implementing a four-button scheme for all questions

This is step 1 of said approach

## Describe alternatives you've considered

Implementing the final approach at once, risking it not being merged into master by Friday

**Comment by acthelemann** [comment]
@SomeMoosery This sound okay?

Anything else you want to add?
Loss of smell or test, headache, diarrhea, nausea, vomiting, abdominal pain, etc.

**Comment by SomeMoosery** [comment]
I think that's great for now - just basing this off of a quick convo from the Discord 👍
