### ISSUE TITLE
More modal closes when clicking anywhere

### ISSUE THREAD

**Issue by acthelemann** [COVID-19-electronic-health-system/Corona-tracker#518]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

The more modal closes when clicking anywhere.

### Steps to Reproduce

1. Click the "More" icon on the bottom nav bar
2. Click on the modal that appears

**Expected behavior:**

Modal remains visible. Modal only disappears when clicking off the modal or an appropriate button.

**Actual behavior:**

Modal disappears.

**Reproduces how often:**

100%

### Versions

0.3.32

### Additional Information

![more-modal-close-bug](https://user-images.githubusercontent.com/16993949/79410145-9bc89c80-7f6d-11ea-80d3-3331932be69d.gif)

**Comment by PhurbaSherpa** [comment]
I can work on this.

**Comment by acthelemann** [comment]
All you
