### ISSUE TITLE
Create UI view for maps feature

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#52]
**Task**
Create a UI view of the map feature of the app.
Add to /designs

**Questions to consider:**
What information will it provide? 
What information will it need?
This will help with database decisions.

**What done looks like:**
1) We have a view that outlines how the maps features will look like.
2) It will outline what functionalities it will have

**Comment by ngiangre** [comment]
closing - will reopen or create new issue when developing a map feature
