### ISSUE TITLE
Create a UI view of the Setting feature of the app.

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#53]
**Task**
Create a UI view of the setting feature of the app.
Add to /designs

**Questions to consider:**
What information will it provide?
What information will it need?

**What done looks like:**
1) We have a view that outlines how the maps features will look like.
2) It will outline what functionalities it will have

**Comment by ngiangre** [comment]
closing - we have already been in discussions about this and we can reissue once we develop this more
