### ISSUE TITLE
Missing survey questions in survey component in regards to the Data Model and Translations sheets

### ISSUE THREAD

**Issue by awu556** [COVID-19-electronic-health-system/Corona-tracker#530]
## Summary

We're currently missing a good amount of questions from the survey that relate to the data model created by the analytics team, and translations also needs these questions in order to help properly format the JSON file to drop in the translated text.

See the link for more details on what's missing [Data model](https://docs.google.com/spreadsheets/d/1gifZGnj-ntIOXbZrRY4S5KEULoV64DCbi0pZSVWKsns/edit?usp=sharing) - green means existing questions, red means missing questions 

If anybody has any opinions on where/how we're going to organize all the remaining questions, feel free to comment down below!
## Motivation

Without the questions, the analytics team will be missing information from their model, and the JSON format needed for the translations team can't be finalized.

**Comment by SomeMoosery** [comment]
Could you provide some more actionable steps for devs to take to complete this? And potentially break up into multiple issues if need be - as we move forward and have a broader and broader I feel that clear acceptance criteria are key to each issue

**Comment by awu556** [comment]
Yes, I was actually going to ask if you had any opinions on where some of the questions should end up. It seems part of them are in the settings tab, while the rest are in the survey. If I knew which ones should be consistent with each component, I could split it up into different issues for devs to work on

**Comment by ngiangre** [comment]
closing in lieu of #643
