### ISSUE TITLE
Custom 404 page not shown

### ISSUE THREAD

**Issue by whoabuddy** [COVID-19-electronic-health-system/Corona-tracker#532]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

I somehow got to https://coronatrackerbeta.com/onboard on mobile and noticed the 404 page has an error. There is a [custom 404 page mentioned here](https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/407), but right now this is what I see:

![2020-04-16 13 20 06 coronatrackerbeta com c3971f2cfd0d](https://user-images.githubusercontent.com/9038904/79503029-5a73d380-7fe5-11ea-9f00-00179b7cec5d.png)

### Steps to Reproduce

1. Access https://coronatrackerbeta.com/onboard or https://coronatrackerbeta.com/imaginary or any link that does not exist.

**Expected behavior:**

Expected the custom 404 page.

**Actual behavior:**

Receive the error in the screenshot above.

**Reproduces how often:**

:100: %

### Additional Information

The value for `Key` always matches the requested resource.

https://coronatrackerbeta.com/__onboard__

```
Code: NoSuchKey
Message: The specified key does not exist.
__Key: onboard__
```

**Comment by AdhamAH** [comment]
Good catch! after checking this is what I found
This is happening when you refresh anything other than the root `/` i.e `/symptomsurvey` will give the same 404 page 
I am not sure if it is a problem with the `react-router` set up or it is a server-side problem
what do you think @SomeMoosery @pavel-ilin @acthelemann

**Comment by pavel-ilin** [comment]
I fixed it for `corona-tracker-client` bucket by adding `homepage` into package.json and add index.html as an error page in properties of the bucket. 

![](https://i.ibb.co/NYTXXWg/Screen-Shot-2020-04-16-at-6-06-12-PM.png)

@SomeMoosery @acthelemann  Should I synch build with `coronatrackerbeta` bucket?

**Comment by SomeMoosery** [comment]
I would try syncing with another bucket if you haven't already. If you have and you tested it and it works, let's sync with the `coronatrackerbeta` 👍

**Comment by acthelemann** [comment]
@pavel-ilin Nice job!
