### ISSUE TITLE
Improvement to the Daily survey questions 

### ISSUE THREAD

**Issue by Josh1794** [COVID-19-electronic-health-system/Corona-tracker#534]
## Summary

an idea I had for improving the survey would be to add a pop-up/modal that would show the user resources for mental/physical health services if they put a low score on their daily survey.

<img width="1225" alt="Screen Shot 2020-04-16 at 4 34 08 PM" src="https://user-images.githubusercontent.com/46975990/79505608-a1bc8d00-8002-11ea-88fa-cf8fe723b7a8.png">

## Motivation

Makes the daily survey more responsive to a user's potential needs and helps to provide useful information to the public

**Comment by ngiangre** [comment]
Great idea! We should try to form partnerships to direct to some services. @Josh1794 do you want to suggest services and work on partnerships?

**Comment by SomeMoosery** [comment]
Going to close and make a relevant issue capturing this suggestion
