### ISSUE TITLE
Configure Chart.js component with dummy data to look like mockup

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#54]
**Task**
Configure Chart.js component with dummy data to look like the mockup
See  [wireframe](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/design/wireframes/CORONATRACKER%20UI%20-%20Login%20-%20Logged%20In%20Home%20page.png).

**Questions to consider:**
What information will it provide?
What information will it need?
This will help with database decisions.

**What done looks like:**
1) We have a chart.js with dummy data.
(It will be replaced once all the components are in place and refactored. For now, we are setting things up then polishing it later).

**Comment by tesla809** [comment]
@pavel-ilin is working on the sub-component. If you take #16 make you will replace the dummy component with what @pavel-ilin is working on.

**Comment by SomeMoosery** [comment]
Do we still need this? 

Even if there is dummy data, part of V2 will be linking up client <--> server so we won't need to hardcode in dummy data

**Comment by tesla809** [comment]
Good point. Not needed. We can nix it.
