### ISSUE TITLE
User profile setup not saving or showing

### ISSUE THREAD

**Issue by whoabuddy** [COVID-19-electronic-health-system/Corona-tracker#541]
### Prerequisites 

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

After setting up my profile, I am unable to see my profile data when I go to More then Settings.

### Steps to Reproduce

1. Log into the app
2. Fill in the profile set up questions
3. Click Save my Responses
4. Click on More then Settings
5. Try filling in the profile set up questions again and saving - same result

__Filling in the data and saving:__

![20200416_114710 Entering the Info](https://user-images.githubusercontent.com/9038904/79509809-1a1a5280-7ff1-11ea-8dfb-ec76c326ef15.gif)

__Viewing the settings page after:__

![20200416_115229_Health_Data_Not_Shown](https://user-images.githubusercontent.com/9038904/79509829-256d7e00-7ff1-11ea-9c4c-c191e51d915d.gif)

**Expected behavior:**

Expect to see my responses populated on the settings page.

**Actual behavior:**

The settings page is empty as if I had not set it up at all. Re-entering the info does not fix it either.

**Reproduces how often:**

100%

### Additional Information

None.

**Comment by fallon7284** [comment]
I can handle this.

**Comment by fallon7284** [comment]
This is finished, if you'll just assign it to me I'll PR it.  Or tell me to just PR it.  Just trying to keep to the system.

**Comment by fallon7284** [comment]
It wasn't a bug it was just work we never did.

**Comment by SomeMoosery** [comment]
Sweet - yeah, this was on my todo list of things to add. Thanks for this! Feel free to PR whenever 👍
