### ISSUE TITLE
Buttons on today / survey slider not responding

### ISSUE THREAD

**Issue by whoabuddy** [COVID-19-electronic-health-system/Corona-tracker#543]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Originally reported by Josh on Discord while using Mac / desktop view, and I am having the same issue on Android using Chrome.

If you slide the red survey slider at the bottom out partially, it exposes three buttons. Clicking/tapping those buttons does not do anything.

![20200416_055534_Screen_Recording](https://user-images.githubusercontent.com/9038904/79511449-2b189300-7ff4-11ea-95fc-956b6bedd1e2.gif)

### Steps to Reproduce

1. Open the main page of the app with the calendar
2. Slowly and partially swipe on the TODAY slider
3. Try and click any of the exposed buttons

**Expected behavior:**

Based on the image it looks like I can:
- check to complete the notification, e.g. "I read it / did it already"
- set a reminder for the notification, e.g. "remind me in 2hrs or 1 day"
- delete or remove the notification, e.g. "I don't want to see this again"

**Actual behavior:**

Clicking the three buttons produces no result.

**Reproduces how often:**

100%

### Additional Information

None.

**Comment by whoabuddy** [comment]
After trying again from my desktop, I also found that it was difficult to swipe the notification all the way across the screen to initiate the survey. It worked well on mobile, but from the desktop I had to try a few times to get it to work.

**Comment by SomeMoosery** [comment]
As of right now, these buttons don't serve a purpose - but maybe we should think about removing them
