### ISSUE TITLE
Daily survey scales are inconsistent

### ISSUE THREAD

**Issue by whoabuddy** [COVID-19-electronic-health-system/Corona-tracker#545]
### Prerequisites 

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

The first section of the survey goes from (0) Worst to (5) Best, and defaults to (3) Middle.

The fourth section of the survey goes from (0) Best to (5) Worst, and defaults to (0) Best.

### Steps to Reproduce

1. Take the survey
2. Observe the slider in section 1
3. Observe the slider in section 4

![2020-04-16 15 33 17 coronatrackerbeta com 555ae8c3a063](https://user-images.githubusercontent.com/9038904/79513136-f6a6d600-7ff7-11ea-858b-7eba7366ede6.png)

![2020-04-16 15 33 34 coronatrackerbeta com 4c55bff7c2e2](https://user-images.githubusercontent.com/9038904/79513141-f9093000-7ff7-11ea-950d-3594b3a0870e.png)

**Expected behavior:**

I expect the sliders to be consistent either way, and could argue for both directions:
- (0) Best to (5) Worst, with (0) Best automatically selected <-- we have the best outlook for a positive outcome, and by default, the answers show the person is doing well (the ideal situation)
- (0) Worst to (5) Best, with (3) Middle automatically selected <-- this makes sense in the logical form of "I'm doing better so the score is higher", and is consistent with the first section. All entries being down the middle does encourage the user to slide it to their preference.

**Actual behavior:**

The sliders go opposite directions between sections and start on a different default value.

**Reproduces how often:**

100%

### Additional Information

None.

**Comment by Bellex0** [comment]
Hey, I mentioned this in PR #460, I'll explain it here too.  
In regards to the rating scale, I understand that we should keep the rating scale consistent for all questions. However, the way these questions are phrased, it doesn’t sound rational to the user if 5 means “I’m feeling great, I haven’t lost any interest” and 1 means  “I’ve had significant loss of interest.” User will naturally equate 5 with being the most and 1 with none. 

For example, for question 1, "have you lost interest..?", it would not make sense if 5 is equal to a happy face. The user will logically see 5 as indicating "a lot", so it should be a sad face.

**Comment by Josh1794** [comment]
I was thinking of submitting a similar thing perhaps it would make sense to re word the questions to better fit the scales

**Comment by ransing** [comment]
So I will play out scenarios here, and this is also for meditating on it for my purpose: 

**This was the original Question** as seen in the screenshot in the above comment: 
1. Have you lost interest or pleasure in doing things? 
Response: Not at all (1)<---------Somewhat(3)-------> A lot(5)

**Current Scale**: 
2. . Have you lost interest or pleasure in doing things? 
Response: 🙂<-------😐--------> 😟 
_This change was made in terms of maintaining the nature of the scale._ 

Scale from SurveyPage1: 😟<-------😐-------->  🙂

So the Original question is from a standard published questionnaire for us to compare the data which was intended for us to publish certain user data (not a whole but instances such as "you are doing well" or "your interest has improved'). We can back it up with peer review research claiming that our scales are legit and not something experimental that we came up with on the fly. And hence my original intention was to keep the language of the question (and answer) as it is.
I also understand and abide by the importance of keeping uniformity of the app and hence I don't have any particular reservations. 
Now if we were to reword stem of the question then we cannot claim that our data comes from a standard questionnaire, which I am totally fine with. So my take on the reworded questionnaire would be: 

**Proposed Q**: Have you maintained interest or pleasure in doing things? 
Answer: (_Scale from SurveyPage1_) :  😟<-------😐-------->  🙂 

So if the proposed question makes sense (or anyone has any suggestion) we can maintain the scale from SurveyPage1.

**Comment by ngiangre** [comment]
For the launch tomorrow, whatever is put inn the app should be consistent to what's in the data model:
https://docs.google.com/spreadsheets/d/1gifZGnj-ntIOXbZrRY4S5KEULoV64DCbi0pZSVWKsns/edit?usp=sharing

If these Qs aren't in the survey tab, append them and follow the current annotation as for the other Qs (you have my permission, but just don't delete everything 👍 ). These Qs would be considered nonphysical observations in the data model. There needs to be more restructuring per the survey which I'll relay soon, but for tomorrow w need there to be congruency between the data model and what's shown in the app. 

You can ping NickG or laseplov in discord if this doesn't make sense.

I want to reiterate that this is awesome and I love this feature :)

**Comment by acthelemann** [comment]
Following the data model - this okay for page 1? The [1-10] scale messes with the symmetry a little.

![page-1](https://user-images.githubusercontent.com/16993949/79525773-aea4a500-8031-11ea-8c75-37387c2adcdc.png)

**Comment by ngiangre** [comment]
Looks great! Just congruence as of now. In my opinion, I think all likert scale questions should all be 1->5 or 1->10 for component consistency. That we can deal with later. I'm going to write up a protocol with @salvolpe after the launch.
