### ISSUE TITLE
Discussion – Translations

### ISSUE THREAD

**Issue by salvolpe** [COVID-19-electronic-health-system/Corona-tracker#56]
Hello all, I want to use this thread to pool our translating resources together so that we can provide as many options as we have available for the app when the time comes to translate.

I have a relative proficiency in French and Italian, with comprehensive skills in Spanish. None of these are my first language.

Please comment below your comfort with languages other than English and definitely note if you are a native speaker and if you have experience using these languages in healthcare.

I am going to create a Translations.md for us to be working in

**Comment by tesla809** [comment]
Help needed for:
Chinese Mandarin
Italian
Farsi (Persian)
Spanish (I can do this one)
French 
Hebrew 
Arabic 
Portuguese 
Russian
Hindi

Any others?

**Comment by tesla809** [comment]
We also need to figure out a way to deliver the right language for people, depending on their preference? How do we store it?

Any ideas?

**Comment by salvolpe** [comment]
I think that we could consider the option that was offered by dgreen899 in Discord: https://www.codeandweb.com/babeledit

I think that it would be best to keep working on the translations.md file as a reference point and then throw any of those things into BabelEdit. We'd just need whoever wants to tweak the React code to make it comply with this program to do so and we can start throwing the translations in. It seems rather comprehensive and useful.

**Comment by salvolpe** [comment]
If this doesn't exactly resolve the preference issue, maybe its a local variable that needs to be stored. I haven't looked through BabelEdit in its entirety.

**Comment by AdhamAH** [comment]
I can help with Arabic, there is Dutch also which is not my mother language as Arabic but I speak it too and can help

**Comment by givonz** [comment]
I can do the Hebrew

**Comment by SomeMoosery** [comment]
Closing as there is a PR #74 relating to translations that is more relevant
