### ISSUE TITLE
Add meta og:image tag in index.html

### ISSUE THREAD

**Issue by Bellex0** [COVID-19-electronic-health-system/Corona-tracker#567]
Add a meta og:image tag in index.html with an image of the homepage (or any other page) of the app. 

## Motivation

When the app link is posted on LinkedIn, other social media, etc., the post will show an image of the app. Currently, it is blank.  

<img width="553" alt="Screen Shot 2020-04-17 at 7 17 52 PM" src="https://user-images.githubusercontent.com/47994630/79621182-71e3b700-80e0-11ea-9f08-7ac2b186e16d.png">

**Comment by acthelemann** [comment]
Should we use the logo here or an image of a page?

**Comment by SomeMoosery** [comment]
I'd vote logo an image of the health log page, maybe - but open to suggestions

**Comment by pavel-ilin** [comment]
I think health log page would be more interesting preview image.

**Comment by tylerd92** [comment]
I can work on this. Should the image be the health log page?

**Comment by SomeMoosery** [comment]
Let's go with the health log page 👍
