### ISSUE TITLE
Link to Contributing.md on README.md is broken

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#569]
### Prerequisites 

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Link to Contributing.md on README.md is broken.
Please update and provide a place where Developers can onboard and get setup.

### Steps to Reproduce
1. Click on the link to contributing.md on readme.md

**Expected behaviour:**

It goes to place that has documents to set up and learn how to contribute to the project.

**Actual behaviour:**
Broken link, a 404 error
**Reproduces how often:**
100% of time

### Versions
N/A

### Additional Information
We need to make sure that our onboarding documents are accessible by our new devs.

**Comment by whoabuddy** [comment]
Fixed in #565
