### ISSUE TITLE
Cards on small screens cut off

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#576]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Since scrolling is disabled on the flashcards component, sometimes cards are cut off on very small screens.

### Steps to Reproduce

1. Log in 
2. Go to flashcards
3. Inspect, make screen very small

**Expected behavior:**

We should allow all users to be able to scroll to see the full card

**Actual behavior:**

Often full cards aren't visible

**Reproduces how often:**

100% on relevant screen sizes

### Versions

1.0.1

**Comment by gitalink** [comment]
I will work on this issue.
