### ISSUE TITLE
Flashcards go from #15 -> #1, not vice versa

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#577]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Currently, the numbered flashcards go in reverse order

**Expected behavior:**

Flashcards go from 1 to 15

**Actual behavior:**

Flashcards go from 15 to 1

**Reproduces how often:**

100%

### Versions

1.0.1

**Comment by mamutahr** [comment]
Hello, could I try working on this?

**Comment by SomeMoosery** [comment]
All you!

**Comment by mamutahr** [comment]
To fix this I was thinking of making an array for the cards and reversing this:
![image](https://user-images.githubusercontent.com/36338290/79810124-4bbc5200-8340-11ea-8419-3811b77cbb7e.png)

As opposed to:
![image](https://user-images.githubusercontent.com/36338290/79810215-88884900-8340-11ea-8474-b96c69c077c8.png)


Would this affect any planning of future ordering of the cards or the comment seen in both pictures?

**Comment by SomeMoosery** [comment]
Why not just reverse the current ordering we have now at the point that ordering occurs? Even if it maps starting at i i.e. 15, we could just do something like `i-(i+1)` i.e. 15-14 = 1

**Comment by mamutahr** [comment]
Oooh I see thats even better, so it would just be something like data={ cardData[ length - i - 1 ] }?

**Comment by SomeMoosery** [comment]
Yeah I'm frankly not sure the most elegant solution here but I feel like there's an easier and more inline way that creating a separate array of `FlashCards` - but I could be wrong!

**Comment by mamutahr** [comment]
On it! Will send a PR soon, thanks for helping me out!
