### ISSUE TITLE
Add additional 'None' button to survey

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#578]
## Summary

We want to add an additional "None" option for people to choose from when choosing answers about symptoms during survey.

- [ ] Add "None" option for all button-based questions
- [ ] Ensure state is updated in Redux
- [ ] Ensure state is persisted to Gaia and properly shows up when survey is selected

## Motivation

Since this app is supposed to be used by everyone, not just people already showing symptoms, we should make that clear in the survey.

**Comment by tylerd92** [comment]
I would like to work on this. I do have a question on how to maintain the UI after adding another button. I attached a screenshot showing what is happening currently when I added the "None" button, the "Moderate" button label was affected.
![Screen Shot 2020-04-20 at 11 06 11 PM](https://user-images.githubusercontent.com/12787123/79821097-d9596b00-835b-11ea-9cbc-bb507327e2f4.png)

**Comment by SomeMoosery** [comment]
Hmm... I'm thinking if there's another word we could use instead of "moderate" that would fit for these small screen sizes, but this is probably a better questions for @ngiangre

**Comment by tylerd92** [comment]
This is only happening for a mobile screen not desktop. I was using chrome dev tools. Is there a way to resize for a mobile interface?

**Comment by SomeMoosery** [comment]
Like how do we mimic mobile in desktop? https://developers.google.com/web/tools/chrome-devtools/device-mode#viewport

**Comment by ngiangre** [comment]
Unfortunately I don't see the scale could be changed to something nore amenable to the problem. Minimal/Moderate/Severe or Low/Medium/High where len(Moderate)-len(Medium)==1 so I'm sure there will be overflow. Can't we have the font size decrease on small screens?

**Comment by SomeMoosery** [comment]
We definitely could make text smaller, we'd just have to do some user testing to ensure it's still readable 👍

**Comment by tylerd92** [comment]
Here is what I have so far

![Screen Shot 2020-04-22 at 5 15 04 PM](https://user-images.githubusercontent.com/12787123/80034901-1ee17980-84bd-11ea-8718-59844c2c15bf.png)
![Screen Shot 2020-04-22 at 5 16 17 PM](https://user-images.githubusercontent.com/12787123/80034903-1ee17980-84bd-11ea-814b-d7e06fcebfb1.png)

**Comment by tylerd92** [comment]
I'm looking to see for mobile there is something in Material UI I could use. If anyone knows of anything, in particular, let me know.

**Comment by tylerd92** [comment]
I found a way to remove that overlap I slightly changed the values for the items in the grid when the screen is small like on a phone.

![Screen Shot 2020-04-22 at 9 07 46 PM](https://user-images.githubusercontent.com/12787123/80048175-68da5780-84dd-11ea-8c08-ea6c5216cca9.png)
