### ISSUE TITLE
When the user first logs in, click "back" on the onboarding page takes them to survey

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#581]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Currently, when the user first signs into CoronaTracker and is prompted to complete the onboarding page, if the user presses "back" they're taken to the survey. We should either prevent users from going back on this page (not sure if that's possible), or if users do press back, just link them back to the onboarding page so it's required they fill it out.

### Steps to Reproduce

1. Create new CoronaTracker account (or alter code so that it thinks you did)
2. Log in
3. Press back on onboarding

**Expected behavior:**

The user is not able to navigate to other parts of the health log / survey until onboarding is complete

**Actual behavior:**

User can go from login -> onboarding -> survey by pressing "back," which is confusing

**Reproduces how often:**

100%

### Versions

1.0.1

**Comment by liadove** [comment]
Can I take this one? @SomeMoosery

**Comment by SomeMoosery** [comment]
All you 👍
