### ISSUE TITLE
Autopopulate and clean onboarding 

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#582]
## Summary

- [ ] Integrate with a maps API so that choosing address becomes an autocomplete process
- [x] Require state to be a dropdown with all 50 states, so we can keep collected data clean
- [x] When selecting a free text field, remove the "Click here" text, as this is confusing and makes the user feel like their click didn't work

## Motivation

This allows for
1. A smoother and more complete UI/UX
2. Cleaner collected data by giving users only set options to choose from

**Comment by SomeMoosery** [comment]
Does Mapbox have the functionality for this? Just because we're already using it for the map itself. If not I think Google is fine at this point - especially if just for autocomplete. Just need to be sure Google isn't doing anything with users' location data, as this gets tricky especially with PHI if we ever are able to call our data PHI

**Comment by acthelemann** [comment]
Good call, they do:

https://www.mapbox.com/pricing/#search
