### ISSUE TITLE
Survey buttons de-select on mobile when scrolling

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#586]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

When using CoronaTracker on an actual mobile phone (currently using iPhone X, both on Chrome and Safari) - filling out the survey page 2 and scrolling will cause buttons to become de-selected in the UI. They're still "selected" behind the scenes, but the UI shows them de-selected.

### Steps to Reproduce

1. Open the app on a mobile device
2. Take a survey

**Expected behavior:**

Buttons stay highlighted while scrolling

**Actual behavior:**

Buttons occasionally de-highlight while scrolling

**Reproduces how often:**

~80%

### Versions

1.0.0

### Additional Information

**This does not reproduce on the mobile view for Chrome dev tools, you need to test it on an actual mobile device**

**Comment by PhurbaSherpa** [comment]
I can work on this

**Comment by SomeMoosery** [comment]
You're on a roll!
