### ISSUE TITLE
Create separate settings page from onboarding

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#587]
## Summary

- [ ] Create a component similar to, but different from `Onboarding`, which users will go to when navigating from `More` -> `Settings`
- [ ] Move data-related buttons (like the delete data buttons) into the settings page

## Motivation

As we grow, we should really have a designated settings page that's separate from the onboarding page

**Comment by PhurbaSherpa** [comment]
I can work on this
