### ISSUE TITLE
Differentiate UI between button and input fields

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#589]
## Summary

- [ ] In onboarding section, and anywhere else with text inputs, make it more obvious that these are text input fields, and not buttons. For instance, don't say "click here."
- [ ] Change Age input to only accept numbers

## Motivation

User and professional reviews are telling us buttons and text inputs look too similar

**Comment by PhurbaSherpa** [comment]
Would making the input boxes with a white background be good ?

<img width="958" alt="Screen Shot 2020-04-19 at 7 35 44 PM" src="https://user-images.githubusercontent.com/53540583/79779796-f153cf00-8308-11ea-9b2e-bd549b38e4c7.png">

**Comment by SomeMoosery** [comment]
Yeah! I'd say either white or clear 👍

**Comment by SomeMoosery** [comment]
Also, perhaps check if this is another issue first, but "Age" should really be a dropdown or at least a number input, not free text

**Comment by PhurbaSherpa** [comment]
> If that's not in another issue, feel free to edit the original issue to contain that here since it should be a quick change

I don't think I'm able to edit the original issue.

**Comment by SomeMoosery** [comment]
Ah okay, I'll go ahead and edit it then 👍
