### ISSUE TITLE
Make "Show Me More" table more appealing on mobile

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#590]
## Summary

The "Show Me More" table currently requires users to scroll horizontally on mobile, which is unpleasant
- [ ] Display the "Show Me More" table in a more user-friendly way on mobile, perhaps in multiple rows per observation. `react-device-detect` is a good package for this. 

## Motivation

We want the UX to be as smooth as possible, and users are saying this is a pain point

**Comment by AdhamAH** [comment]
I will rebuild the table component

**Comment by AdhamAH** [comment]
When I day rebuild I mean I will make sure that it is good for mobile and easy, but I will look into that package
