### ISSUE TITLE
Make graphs more obvious to select

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#591]
## Summary

- [ ] In the "Show Me More" tab, create a more visible and inviting call to action than checkboxes for the user to view graphs, perhaps highlighted buttons like elsewhere in the app

## Motivation

Beta surveys are informing us that it's not obvious that the checkboxes display graphs.

**Comment by AdhamAH** [comment]
I will be doing this with #590
