### ISSUE TITLE
[DOCS] Add Translations README

### ISSUE THREAD

**Issue by whoabuddy** [COVID-19-electronic-health-system/Corona-tracker#593]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement this update.

### Summary

We need to create a README.md file for [the /Translations folder](https://github.com/COVID-19-electronic-health-system/Corona-tracker/tree/master/Translations) of Corona-tracker.

### Motivation

This will help explain what the Translations folder represents in terms of the application, and some context to the files contained within. It should include:

- [x] A link to the readme file of Corona-tracker
- [x] A reference to the lead contact and discord link
- [x] A basic description of the translation efforts
- [x] A basic description of the repo files, e.g. Translations.md
- [x] Links to external docs like translation spreadsheet
- [ ] Optional: links to the org-level CoC, Contrib, and Support docs _(they also show under "Helpful resources" section on the right of any issue/PR)_

### Possible Alternatives

Leave it as-is, which doesn't explain the goals of the group and/or this part of the project. It's also confusing if you open Translations.md in an effort to "see how I can help".

### Additional Context

- [x] update CoronaTracker readme when done with link to README.md instead of Translations.md

**Comment by salvolpe** [comment]
Completed this! Thanks @whoabuddy for pointing it out!

**Comment by SomeMoosery** [comment]
Is this good to close then @salvolpe ?

**Comment by salvolpe** [comment]
Oh yes! Didnt know if you want to look this over first, but I'm good with it!
