### ISSUE TITLE
[DOCS] Update client README

### ISSUE THREAD

**Issue by whoabuddy** [COVID-19-electronic-health-system/Corona-tracker#594]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement this update.

### Summary

We need to update the README.md file in [the /client folder](https://github.com/COVID-19-electronic-health-system/Corona-tracker/tree/master/client) of the Corona-tracker repo.

### Motivation

This will help explain the contents of the folder better, as well as allow for an opportunity to put in some front-end specific items if necessary. It should include:

- [ ] A link to the readme file of Corona-tracker
- [ ] A reference to the lead contact and discord link
- [ ] A basic description of the front end (also see: [SUPPORT.md in .github](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md))
- [ ] A reference to repo-specific commands and nuances, such as:
    - always use `yarn` not `npm` or it will break
    - always use `yarn lint` before submitting code
    - etc.
- [ ] Any other specific info to getting started with front end work
- [ ] Optional: links to the org-level CoC, Contrib, and Support docs (they also show under "Helpful resources" section on the right of any issue/PR)

### Possible Alternatives

Leave as-is, which shows off how fancy a react boiler-plate readme file can be.

### Additional Context

- should be linked from CoronaTracker readme already, but want to make sure information flows well between both documents

**Comment by crispinamuriel** [comment]
Hello, I'd like to work on this issue!
