### ISSUE TITLE
[DOCS] Update design README

### ISSUE THREAD

**Issue by whoabuddy** [COVID-19-electronic-health-system/Corona-tracker#596]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement this update.

### Summary

We need to update the README.md file for [the /design folder](https://github.com/COVID-19-electronic-health-system/Corona-tracker/tree/master/design) of Corona-tracker.

### Motivation

This will help explain what the design folder represents in terms of the application, and some context to the files contained within. Note that images were being migrated to Amazon Cloudfront/S3, so some of the content in this repository may be removed. Contact @SomeMoosery and/or @BrianHHough if additional detail is needed.

The readme should include:
- [ ] A link to the readme file of Corona-tracker
- [ ] A reference to the lead contact and discord link
- [ ] A basic description of the design team efforts
- [ ] Review colors in use between app/website against chart, and update
- [ ] A basic description of the repo files 
- [ ] Formatting for external links via Amazon CloudFront
- [ ] Optional: links to the org-level CoC, Contrib, and Support docs _(they also show under "Helpful resources" section on the right of any issue/PR)_

### Possible Alternatives

Leave as-is, with minimal description and a brand guide that may or may not be complete. This is a good opportunity to unify the brand guide and design outlines between the website and the CoronaTracker app.

### Additional Context

This should be thought of as a "Brand and Style Guide" that will expand beyond colors to help others with design considerations (layout, positioning, etc), color choices (primary, alt, etc), and other resources to provide a consistent experience across all digital outlets.

**Comment by crispinamuriel** [comment]
I'd like to work on this!

**Comment by crispinamuriel** [comment]
I'm having a little problem understanding this checkbox
[ ] Formatting for external links via Amazon CloudFront

I completed everything else!
