### ISSUE TITLE
Add Symptom Diarrhea 

### ISSUE THREAD

**Issue by givonz** [COVID-19-electronic-health-system/Corona-tracker#597]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Add diarrhea to the list of symptoms on page 2, where there are a list of symptoms.

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by ngiangre** [comment]
added to master health survey on google sheet

**Comment by SomeMoosery** [comment]
Do we want this as a button? As something to mention in the free text section?

**Comment by ngiangre** [comment]
Agreed with @SomeMoosery. I propose we have this be a symptom to be filled into the free text box and be a symptom indicated by a body map and symptom fill in feature. I know @ransing was working on something like this - is that right? Can you make an issue for it if you are @ransing? Thanks!

**Comment by SomeMoosery** [comment]
Closing, as it seems we've already captured it and/or won't be adding it as a button for the time being 👍
