### ISSUE TITLE
Age field should not say click.  It is a fill-in not a drop-down.

### ISSUE THREAD

**Issue by givonz** [COVID-19-electronic-health-system/Corona-tracker#598]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Age field should not say click.  It is a fill-in not a drop-down.

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by SomeMoosery** [comment]
Similar to #589
