### ISSUE TITLE
Create landing page design

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#6]
We want to have a baseline landing page design for this application so we know where to build things off of.

**Comment by BrianHHough** [comment]
Thanks @SomeMoosery! I'm on it!

**Comment by BrianHHough** [comment]
![CORONATRACKER UI - #1](https://user-images.githubusercontent.com/56947075/76689858-85e35700-6610-11ea-874b-88f25ba244a8.png)
