### ISSUE TITLE
Update coronatracker.me to HTTPS (discussion)

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#608]
## Summary
Is it necessary to update Coronatracker.me to https?
Currently, it is 
If we start to collect emails (and perhaps for SEO if its a thing) would it better to upgrade?

## Motivation
Why are we doing this? 
Conveys more security, especially if we collect initial user data 

What use cases does it support? 
Security and user acquisition.

What is the expected outcome? 
Our site is HTTPS, more secure.

## Describe alternatives you've considered
This could be a non-issue and not necessary

## Additional context
None

**Comment by SomeMoosery** [comment]
This is more @nathanboone or @BrianHHough territory - this is the Squarespace site so I don't really touch this as it's not a part of the web app, it may be necessary but not within the scope of the repo 👍

**Comment by tesla809** [comment]
Good call! Thanks!
