### ISSUE TITLE
Break up designs into components and create issues

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#61]
**Tasks**
Break up designs into components and create issues

**What does done look like**
1) We have a series of issues that looks at each view, identifies components. 
2) If a component looks like it has sub-components, create an separate issue for the sub-component. The main component will be a container component. Link both the issues.

**Questions**
If you have any questions, please comment on the issue and message me on the discord.

**Comment by lukelin1991** [comment]
can I suggest maybe a form that breaks up into 2 subforms, 1 with pre-reqs? (are you smoker? diabetic, age, etc. etc.) and 2 (regular daily-"how are you?", record temperature, short description on how you're feeling) that'll append into possibly a calender for a (per day) reading?

**Comment by tesla809** [comment]
Yup! @lukelin1991 What do you think @BrianHHough .

We will need to get info related to pre-existing conditions, so we need a view for that as well.

**Comment by tesla809** [comment]
@lukelin1991 check out the [designs](https://github.com/COVID-19-electronic-health-system/Corona-tracker/tree/master/design) and comment where you would like to see it.

**Comment by lukelin1991** [comment]
@tesla809 i think in the designs wise, seems like a lot is going on.  out of curiosity, how adamant are we in regards of keeping the wireframed UI the way it is?

**Comment by lukelin1991** [comment]
in my mind, i see "Talk to Doc", and "map" as a V2, or V3 part of the project.
i'd say a simple app that gives you recommendations in blurbs instead of "news" would be something more warm and welcoming.
and a "feeling Log" to track how you're doing. with a calendar.

**Comment by tesla809** [comment]
For sure. Good point @lukelin1991 after our discussions with the medical experts, it seems that the talk to doc is a more complex feature to ship due to regulations. 
v1: Education and translations
v2: get survey info
v3: create analytics

**Comment by Tanvez** [comment]
I would like to help with creating the issues and breaking down the designs into components.

how would the review process for draft issues look like before actually going ahead and creating the issue? 

Ex. write a draft -> send to review(via discord or just create the issue with a draft in the title?) -> create issue

**Comment by tesla809** [comment]
See [CONTRIBUTING.md](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/CONTRIBUTING.md)

**Comment by tesla809** [comment]
To keep it simple here is a way to go about it:  
1) take the images in /v1-final-MVP, 
2) copy those images. 
3) Then identify each component in each image.
4) Take a screenshot of that image specifically.
5)  If a component has a sub-component it gets its own file too.
6) Name them and place them in a new folder called /v1-final-MVP-subcomponents

Then with that folder submit a pull request. It will be reviewed by someone. They will give you suggestions. You will fix things based on that suggestion. This part is a collaborative process. Then once everything is good, it will be merged. 

Viola! You have your first PR! And it will greatly help the team!

**Comment by Tanvez** [comment]
Awesome. Will do!
