### ISSUE TITLE
Closing Get Started Dialog keeps you stuck at loading

### ISSUE THREAD

**Issue by PhurbaSherpa** [COVID-19-electronic-health-system/Corona-tracker#611]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

When initially coming to the app and clicking get started a popup shows up. If you close that pop up the app is stuck on the Loding component with no way of getting out except for refreshing.

![loding](https://user-images.githubusercontent.com/53540583/79823702-5e478300-8362-11ea-805c-cc6b60d3211d.gif)

### Steps to Reproduce

1.  Start at Login page (sign out)
2.  Click Get Started
3.  Click the x on the top right

**Expected behavior:**
Probably should go back to the Login component

**Actual behavior:**

Is stuck on Loding component
**Reproduces how often:**
 100%

### Versions

1.0.10

### Additional Information

could remove the loding page since its only used there 
or
we could move setLoading(true) somewhere else instead of onclick of the 'Get Started' button since there is no way of setting loading to false after.

**Comment by pavel-ilin** [comment]
Can tackle this bug.

**Comment by PhurbaSherpa** [comment]
I had an idea that seems to work, we could add an event listener on the onclick of the 'Get Started Button' because when inspecting I saw that the modal from Blockstack was still there but hidden.

`document.addEventListener('transitionend', event => {
      if (event.target.style.pointerEvents === 'none') {
        setLoading(false);
      }
    });`

**Comment by SomeMoosery** [comment]
Interesting! That seems like it could work @pavel-ilin 

If this works, this could actually potentially be used to workaround login issues too... great catch @PhurbaSherpa
