### ISSUE TITLE
Bottom nav and start issue slider should be different colors

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#615]
## Summary

A complaint I'm getting from my own and others' user surveys is that it's confusing have the "swipe to complete a survey" slider and the bottom nav as the same color.

<img width="328" alt="Screen Shot 2020-04-21 at 7 57 44 PM" src="https://user-images.githubusercontent.com/15767602/79926285-7d015480-840a-11ea-8f79-438e566e0600.png">

We should consult with @BrianHHough on how to best go about changing this

## Motivation

To best suit our community

**Comment by AdhamAH** [comment]
I was thinking about it for a long time. I looked at the most famous apps `facebook, drive, twitter...etc` all beside twitter when you open them in a web browser they change to top navbar and dump the bottom navbar. The browser here plays a part I think and you can not really control it through style. ###this was a big side note

As for the colour this could work I think @BrianHHough 
![Screenshot 2020-04-23 at 01 37 15](https://user-images.githubusercontent.com/55054963/80043827-0a27d480-8503-11ea-863c-44349801d0a5.png)

**Comment by BrianHHough** [comment]
hey @AdhamAH ! I like that bottom nav bar where it's blue! Let's do that. Also, can we put arrows to the right of each slide bar so users know/are indicated to swipe them?

**Comment by SomeMoosery** [comment]
Totally agree on both points! Let’s make a separate issues for arrows on the slider bar though
