### ISSUE TITLE
Clicking health log tab should always return to calendar view

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#617]
## Summary

- [ ] Whenever the health log tab is clicked, it should return the user to the calendar view of their health log
- [ ] Even if the user is in "Show Me More" - which is technically part of the Health Log - they should be navigated back to the calendar view

## Motivation

It is not inherent to outside users that the "Show Me More" portion is an extension of the health log, therefore it's confusing when they click the health log tab and are not redirected to the calendar view of the health log.

**Comment by PhurbaSherpa** [comment]
I can work on this
