### ISSUE TITLE
Add ability to show charts for all surveys, not just specific ones

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#619]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

In the "Show Me More" view for all surveys, there doesn't appear to be the checkboxes to display graphs when there are many surveys (or, rather, they're rendered out of view)

![Screen Shot 2020-04-21 at 11 37 30 PM](https://user-images.githubusercontent.com/15767602/79937920-26574300-8429-11ea-9bb9-964d3b83872a.png)

<img width="1388" alt="Screen Shot 2020-04-21 at 10 40 10 PM" src="https://user-images.githubusercontent.com/15767602/79937922-26efd980-8429-11ea-9b72-d325e3758b23.png">

### Steps to Reproduce

1. Log in
2. Enter a bunch of surveys
3. Go to the "Show Me More" page for all surveys

**Expected behavior:**

We can still create appropriate charts

**Actual behavior:**

Checkboxes to view charts are hidden

**Reproduces how often:**

100%

### Versions

1.0.15

**Comment by pavel-ilin** [comment]
Can take on this one
