### ISSUE TITLE
Adjusting Code in All Components for Translation Integration

### ISSUE THREAD

**Issue by salvolpe** [COVID-19-electronic-health-system/Corona-tracker#623]
## Summary

We need to make sure that all of the translation JSON files are being exported from the spreadsheets and then moved into the respective locales that match whatever format is most conducive to dynamically pulling them into the components. Issue #359 references a possible JSON document for holding the information. [This folder](https://github.com/COVID-19-electronic-health-system/Corona-tracker/tree/master/docs/content) contains the existing JSON exports from the Google Sheets.

## Motivation

We need to be able to automate as much of the language support as we provide and to ensure that we have a workflow in place for seamless integration and adaptation in the future. An example of the societal impetus was voiced in Issue #595 for Dutch Translation.

## Describe alternatives you've considered

Manually copy and pasting all of the text. Not fun.

## Additional Context

If you look at [Login.jsx](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/client/src/components/Login.jsx) you'll see the general formatting for including the translations in each component. [Translations.jsx](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/client/src/components/Translations.jsx) is also a good reference for knowing how it pulls from the locale folders.

## To Do List

- [ ] Make a locale folder for each of the languages that we offer (named with the [ISO Standard](http://www.mathguide.de/info/tools/languagecode.html), e.g., English --> en). List is available [here](https://docs.google.com/spreadsheets/d/1Deaaybwk8TPDlOnXJkFCQe6CIcrAqWoDA5Gbot3joyY/edit#gid=0). The locale folder can be found [here]()
- [ ] Present languages in `Language Select` drop down in that respective language (e.g., English, Italiano, Français, Русский, 한국어)
- [ ] Include formatting from [Login.jsx](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/client/src/components/Login.jsx) at any location using text.
- [ ] Standardize field names as described in [Health](https://docs.google.com/spreadsheets/d/1tjeTH99QZSmyfG-TvX5seSYKa03yAHdMWrZt1z9521I/edit#gid=0), [Education](https://docs.google.com/spreadsheets/d/1OdasOk5y8w9JLv3VWmziV8XkznaYiW-OQzbQq5ZK26M/edit#gid=435919453), and [Display Text](https://docs.google.com/spreadsheets/d/1zBEZp5I7IE-nYVGmNshh0GbajnbuLx5Vqkh7hfY5bJY/edit#gid=0) reformatting to camelCase, when necessary, for eventual switch to TypeScript.

## Further Work

- [ ] Devise methodology for dynamically adding and changing questions without needing to hard code the components (iterating through an array of question/text Types and pushing new components to the app)

**Comment by ngiangre** [comment]
Closing in lieu of #643
