### ISSUE TITLE
Create RESOURCES.MD to help onboard developers 

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#63]
**Task**
Create RESOURCES.MD to help onboard developers

**What done looks like**
1) Create RESOURCES.MD in root
2) Links RESOURCES.MD to README.md and CONTRIBUTING.md
3) Breaks up resources for devs to lookup by tech: Front-End, Backend, Blockstack, Design, Analytics etc.

**Comment by SomeMoosery** [comment]
Is this the same as the `resources_to_use` file we have?

**Comment by tesla809** [comment]
Look about right! yup seems to be resolved. @SomeMoosery
