### ISSUE TITLE
[FEAT] Validate phone number for subscription

### ISSUE THREAD

**Issue by acthelemann** [COVID-19-electronic-health-system/Corona-tracker#630]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement the feature.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Summary

Either disable the subscribe button if the phone number is not valid or show an error message once the subscribe button is pressed. Either way, don't make a request to the subscription service and inform the user of what went wrong.

- [x] Validate the phone number is of [E.164 format](https://www.twilio.com/docs/glossary/what-e164)
- [x] If the phone number is not valid, do not make a request to the subscription service
- [x] If the phone number is not valid, inform the user

### Motivation

Phone numbers being subscribed to the notification service should be of a consistent format and should be able to support international numbers.

### Possible Alternatives

Only do the validation on the backend. It would return a `400` status code and it could be handled on the frontend.

### Additional Context

[E.164 format](https://www.twilio.com/docs/glossary/what-e164)

**Comment by SomeMoosery** [comment]
I can work on this
