### ISSUE TITLE
[FEAT] Clicking on stepper will take you to corresponding survey page

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#635]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement the feature.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Summary

- [ ] Clicking on a stepper value when taking a survey will take you to the corresponding page
- [ ] Ensure all data is saved in Redux so users won't have to re-type anything

### Motivation

As responsive a UX as possible

**Comment by PhurbaSherpa** [comment]
I can try this.

**Comment by AdhamAH** [comment]
yes, Thank you!
