### ISSUE TITLE
[FEAT] Add T&C / privacy policy from disclaimer as links in settings

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#636]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement the feature.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Summary

- [ ] Similar to how we have them in the disclaimer, add links to the terms & conditions and privacy policy in settings

### Motivation

Users should always be able to get to the terms & conditions and privacy policy, not just when they first log in

**Comment by petesamper** [comment]
I can take this.
