### ISSUE TITLE
[BUG] Swiping on WeeklyTrackerDay does nothing

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#640]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to address the issue.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reproduced the problem in QA
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Description of the Bug/Issue

Title is self-explanatory, swiping on a WeeklyTrackerDay card doesn't open the "Show me More" page

### Steps to Reproduce

1. Log in
2. Swipe on a WeeklyTrackerDay card

### Expected Behavior

Opens "Show Me More" page

### Actual Behavior

Nothing happens

### Reproduces How Often

100%

**Comment by PhurbaSherpa** [comment]
I can look at this

**Comment by PhurbaSherpa** [comment]
Am I still redirecting to the survey or am I now having the slider go to Show me More after swiping?

**Comment by SomeMoosery** [comment]
When swiping on one of the blue WeeklyTrackerDay swipers that should take you to "Show Me More" with just that observation and not all observations, if that makes sense
