### ISSUE TITLE
[DOCS] Add OpenCollective link to all documentation

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#641]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement this update.

### Summary

Let's add to the link to OpenCollective site. This will help us gain more avenues to add to the donation funnel. If we get ahead of the cost of servers before we need it, we will be able to scale with greater ease.

Create a section that asks for donations on each page at the top of each documentation page. We should strive to do this in a tasteful manner. 

At the beginning and end of each doc we can add a simple prompt: 
**[Like our project? Please make a tax-deductible donation](https://opencollective.com/coronatracker)**.

### Motivation
**Why are we doing this?**
Greater exposure of our tax-deductible donation platform will help increase donations over the long term.

** What use cases does it support?**
If we address funding now, future scaling issues and AWS costs will be lessened. If we go viral, it is safe to assume that our AWS bill will as well.

** What is the expected outcome?**
A greater increase in donations and more avenues to our donations funnel. The greater size of the fund to address future escalating AWS costs. 

### Possible Alternatives

This seems to be the lowest cost solution to the problem. I estimate the ROI of action is high over the long term.

### Additional Context

See our OpenCollective site:
https://opencollective.com/coronatracker

**Comment by whoabuddy** [comment]
Closing, fixed via [.github#21](https://github.com/COVID-19-electronic-health-system/.github/pull/21) and #688
