### ISSUE TITLE
[FEAT] Rename any references to "Fun Facts" to just "Facts"

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#645]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement the feature.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Summary

- [ ] Any time there is a reference to "Fun Fact," replace this with just "Fact" (using a global search in your code editor will help with this)

### Motivation

Nothing about this pandemic is fun

**Comment by njordhov** [comment]
Alternatively, use an icon to represent the concept of a fact (e.g a light bulb or checkmark).

**Comment by Lukabaramishvili** [comment]
I can take this one.
