### ISSUE TITLE
[BUG] Unable to fill out beta survey from the link on the about page

### ISSUE THREAD

**Issue by balinm** [COVID-19-electronic-health-system/Corona-tracker#646]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to address the issue.

### Prerequisites

- [ ] check this box if you have completed the following:
    - Reproduced the problem in QA
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Description of the Bug/Issue

The 'Take our Beta Survey!' link on the about page links to an editable version of the survey, preventing users from filling it out.

### Steps to Reproduce

1.  Login
2.  Click 'more' at the bottom of the page
3.  Click 'About'
4.  Click 'Take our Beta Survey!'

### Expected Behavior

Links to a survey the user can fill out

### Actual Behavior

Links to an editable version of the survey: https://docs.google.com/forms/d/1sMp_qZYIrVxY6dxVCfIF6XQCU2lUeM_3qITC8hOph1w/edit

### Reproduces How Often

100%

**Comment by ngiangre** [comment]
https://forms.gle/PrD1QY2z3a7htB5W9 <-- add this please

**Comment by balinm** [comment]
@SomeMoosery mind if I take a stab at this?

**Comment by SomeMoosery** [comment]
All you
