### ISSUE TITLE
[DOCS] Add OpenCollective "backers" Badge to repo

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#648]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement this update.

### Summary

A metric to show the world is the number of backers we have. The more we have, the more legit we look, the more we can gain. It also gives a good overview of the project at a glance

See the docs:
https://docs.opencollective.com/help/collectives/data-export#badge
https://opencollective.com/coronatracker/tiers/badge.svg

### Motivation
**Why are we doing this?**
We want to give possible project donors (of time, money, social shares) a quick glance at our project. Showing them how many backers we have conveys more legitimacy. Over time, the more backers we have, the more social proof we have, which increases the chances of a donation. We can turn financial capital into social capital, and vice versa.

 **What use cases does it support?**
This helps with fundraising long term. Giving a summary of our project from the financial dimension and making our project more legitimate. 

** What is the expected outcome?**
Prospective donors will see the number of donors and feel more confident with the project. The additional metric can help increase our social capital and long term donations.

### Possible Alternatives

We can add the text on the current number of donors, but that is more labour-intensive. The current solution has the biggest ROI on the investment of time.

### Additional Context

See the documentation:
https://docs.opencollective.com/help/collectives/data-export#badge
https://opencollective.com/coronatracker/tiers/badge.svg

**Comment by SomeMoosery** [comment]
Would this be in documentation? In the app itself? How should it be represented - a number, panel of images, etc?
