### ISSUE TITLE
[DOCS] Add twitter button to  Corona-tracker's github repo

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#649]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement this update.

### Summary

Adding Twitter button on top of our GitHub will help increase our social media.

see:
https://gist.github.com/studiopress/6867036

Sample code from Babel's README:
  <a href="https://twitter.com/intent/follow?screen_name=babeljs"><img alt="Follow on Twitter" src="https://img.shields.io/twitter/follow/babeljs.svg?style=social&label=Follow"></a>

See how Babel did it:
https://github.com/babel/babel

### Motivation
**Why are we doing this?**
More follower on twitter. More legitimacy and integration across our social channels. Social capital from twitter can lend itself to our project and vice versa. This will help our marketing and engagement.

**What use cases does it support?**
This will help our marketing and engagement.

**What is the expected outcome?**
We get more followers on twitter which helps our organic social media

### Possible Alternatives

We can have a twitter link inside the README.md, but that is less clear. 
Having a prominent button helps us get attention and a higher click rate to sign up.

### Additional Context

Sample code from Babel's README:
  <a href="https://twitter.com/intent/follow?screen_name=babeljs"><img alt="Follow on Twitter" src="https://img.shields.io/twitter/follow/babeljs.svg?style=social&label=Follow"></a>

See how Babel did it:
https://github.com/babel/babel

**Comment by tesla809** [comment]
Should we add it to all github repos @whoabuddy ?

**Comment by SomeMoosery** [comment]
I'd say this should be moved to the `.github` org as I think this should be present across all repos
