### ISSUE TITLE
[FEAT] Add an indicator to swipe WeeklyTracker.jsx

### ISSUE THREAD

**Issue by AdhamAH** [COVID-19-electronic-health-system/Corona-tracker#658]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement the feature.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Summary
Add an indicator to swipe `WeeklyTracker.jsx` like the one in `LogHealthSlider.jsx`
![Screenshot 2020-04-28 at 15 49 49](https://user-images.githubusercontent.com/55054963/80495526-53937c00-8968-11ea-92d2-2e739d206b73.png)

### Motivation
To make it clear for the user of this function 

### Possible Alternatives
none

**Comment by SomeMoosery** [comment]
Good point - I'd say for now, let's add an indication to swipe just so we have the functionality ready to go. And then, if we decide we want to move to click, we can create a new story to refactor these to click functionality, as that will take a bit of work 👍
