### ISSUE TITLE
[BUG] Typo in English translation

### ISSUE THREAD

**Issue by givonz** [COVID-19-electronic-health-system/Corona-tracker#659]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to address the issue.

### Prerequisites

- [ ] check this box if you have completed the following:
    - Reproduced the problem in QA
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Description of the Bug/Issue

Type in Text1 of the translation file.
"You are in control of how you woulrd"  should be
"You are in control of how you would "  no 'r' in the word "would"

**Comment by ngiangre** [comment]
Fixed on google sheets
