### ISSUE TITLE
[DOCS] Hebrew Translation

### ISSUE THREAD

**Issue by givonz** [COVID-19-electronic-health-system/Corona-tracker#660]
[CoronaTracker appText.zip](https://github.com/COVID-19-electronic-health-system/Corona-tracker/files/4546409/CoronaTracker.appText.zip)

# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement this update.

**Comment by salvolpe** [comment]
@givonz Thank you for the work.

Can you please put this and all subsequent translations in the [Hebrew Translations Mastersheet](https://docs.google.com/spreadsheets/d/10HsV7mfBTYgmR-hb7OVGSkopL_ARxGhT0mJsB8rjYEo/edit#gid=0) and mark your progress on the [Translations Efforts Sheet](https://docs.google.com/spreadsheets/d/1Deaaybwk8TPDlOnXJkFCQe6CIcrAqWoDA5Gbot3joyY/edit#gid=0)

**Comment by SomeMoosery** [comment]
Closing this issue as this isn't really an issue - please follow @salvolpe's directions for how to add translations
