### ISSUE TITLE
[FEAT] Implement return to the homepage

### ISSUE THREAD

**Issue by salvolpe** [COVID-19-electronic-health-system/Corona-tracker#662]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement the feature.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Summary

Users should be able to return to the homepage by clicking on a button that lives on the nav bar or a return/home button that is present on all of the screens.

### Motivation

I have to complete the survey every time that I want to get back to the homepage.

### Possible Alternatives

Leave it as is and force users to complete the survey every time.

**Comment by SomeMoosery** [comment]
So this is something that I've been thinking about - what actually is our "home page?" The health log? If so, the users can just click on that in the nav bar already.

What do you think?

**Comment by salvolpe** [comment]
@SomeMoosery Currently, when I try do that by clicking `Log` it doesn't move:
[![Image from Gyazo](https://i.gyazo.com/e2303d10b0112a8601744fafd8bcd1a9.gif)](https://gyazo.com/e2303d10b0112a8601744fafd8bcd1a9)

**Comment by SomeMoosery** [comment]
Have you already filled out a survey today? We added this functionality intentionally to require users to fill out a survey before navigating to the health log if they hadn't yet logged one on today's calendar date.

Do you think this could be frustrating UX? If so - I'd suggest we close this issue and file a new one to remove that functionality.

**Comment by salvolpe** [comment]
I hadn't filled one out yet, so I see why it wasn't working.
I'm a bit hesitant on forcing users to do anything on an application. Particularly in this instance: I'm a user who fills out my survey at 5pm because I like to see how my symptoms were throughout the day and I take my vitals just before dinner time. But it's the morning and I want to look at my log to see a trajectory, or discuss something with a healthcare provider. Now I can't access my log until I fill out the survey and I have to fill out my answers early.

I think closing this and opening a new issue is a good idea. I think we can think of a more user-friendly way to get them to fill out the log, perhaps it's a prompt to fill it out every time they open the app, but they haven't logged the day yet. We'd have to consider alert fatigue, but at least they can dismiss it if they're not ready to do so.

**Comment by AdhamAH** [comment]
that brings two ideas to me
### First
I think it is a good idea to let the user choose if the user ready to take the survey or not.
I am working on something
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/55054963/80592041-0d4d2400-8a1f-11ea-917f-121b34bbffcf.gif)
we can make it glow when there is no survey taken today as a call for action and normal button when taken 
### Second 
The idea of pages. I was thinking about talking with @SomeMoosery about it. Reorgnize the app stracture as it is getting bigger. Some components are not used but could be kept and used later liake an `Archive` and better than we are using `container` like `FactQuizContainer.jsx` or `DiagnosticContainer.jsx`, etc. We can do something like this:
```javascript
scr|----Components|---showMeMore|---Observations.jsx
   |              |             |---BehavioralChart.js
   |              |             |---AvgTemperature.jsx
   |              |             |---Chart.jsx
   |              |---survey|---SurveyPage1.jsx
   |                        |---SurveyPage2.jsx
   |                        |---SurveyPage3.jsx
   |---Pages|---showMeMore.jsx
   |        |---Survey.jsx
```

**Comment by AdhamAH** [comment]
So, if you all want, we can make an issue to remove that function. Then and issue for the button and maybe another one for reorganizing the files in the app `I can do the last two as the first almost done and the second I have a good idea how to do it`

**Comment by SomeMoosery** [comment]
Go for it! That seems like the best course of action. Thanks for pointing this out @salvolpe

**Comment by AdhamAH** [comment]
closing in favour of #668
