### ISSUE TITLE
[DOCS] Add DocMusher as advisor to Docs and Website

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#667]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement this update.

### Summary

Add DocMusher as an advisor to Docs, our main Website and any other locations.
He is the Belgian doctor who is advising us on how to improve the product and is willing to test it. 

See picture:
https://discordapp.com/channels/687791378075484161/689541237174566958/704413049972326540

Background:
https://discordapp.com/channels/687791378075484161/689541237174566958/702603956823523418

### Motivation
**Why are we doing this? **
DocMusher asked to be on the advisory board and has given really good feedback, and we are honoured. Very happy to do so.

**What use cases does it support? **
The more doctors can inform us on the product, the close we can get to product-market fit and help the users. It will also help us with our distribution model if doctors ask patients use this if they see the usefulness. 

**What is the expected outcome?**
We have another medical expert on our advisory board. It increases our legitimacy and gets us closer to product-market fit.

### Possible Alternatives

None, this is the lowest cost implementation.

### Additional Context

See links above.

**Comment by ngiangre** [comment]
@whoabuddy this is done right? Can we close?

**Comment by whoabuddy** [comment]
Closing, fixed via [.github#21](https://github.com/COVID-19-electronic-health-system/.github/pull/21)

@ngiangre I had it open to make sure I got the changes into support.md of .github as well, which is now done. Thanks!
