### ISSUE TITLE
[FEAT] Allow user to navigate to HealthLog without completing survey 

### ISSUE THREAD

**Issue by AdhamAH** [COVID-19-electronic-health-system/Corona-tracker#668]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement the feature.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Summary
Now when the user logs in for the first time is promoted to do the survey. If the user doesn't want to do that, the user can't access `HealthLog` until completing the survey.
we want to promote the user to take the survey upon login but allow to go to `healthLog` without taking the survey 

### Motivation
Give the user the choice when to take the survey 

### Possible Alternatives
remove this function and redirect to `healthLog` upon login 

### Additional Context
We can make a way later to remind the user to take the survey like the idea in #662 or any other way

**Comment by PhurbaSherpa** [comment]
I could work on this

**Comment by AdhamAH** [comment]
all yours, thanks!
