### ISSUE TITLE
[DOCS] Move ROADMAP-TO-MVP.md to ideal location

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#675]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement this update.

### Summary

I pushed  ROADMAP-TO-MVP to main coronatracker repo. Not sure if this is the right place. Should we instead move it to https://github.com/COVID-19-electronic-health-system/.github

### Motivation
**Why are we doing this?**
We want to keep the docs organized

**What use cases does it support?**
Organization

**What is the expected outcome?**
organized docs

### Possible Alternatives

Keep it here. Depends on the preference of @whoabuddy

**Comment by ngiangre** [comment]
@whoabuddy whats the status of this?

**Comment by whoabuddy** [comment]
Closing this issue, I think that since the roadmap is specific to Corona-tracker it should live in the repo, so it's good where it's at!
