### ISSUE TITLE
[DOCS] Add Dr. Sal Volpe as advisor to Docs and Website

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#676]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement this update.

### Summary

Add Salvatore Volpe, MD, FAAP, FACP, CHCQM as an advisor to Docs, our main Website and any other locations.

He is the doctor with experience in clinical informatics who is advising us on how to improve the product.

LinkedIn Profile: https://www.linkedin.com/in/salvatore-volpe-651a5a2/

Bio:
Salvatore Volpe, MD, FAAP, FACP, CHCQM has 30 years of primary care practice experience. He has achieved board certification in Pediatrics, Internal Medicine, Geriatrics, Clinical Informatics and Quality Assurance. Dr. Volpe is a national lecturer on diverse topics such as Consumer Health software, e-Prescribing, Electronic Health Records, patient-centred Medical Home, and Physician-Patient Communication.

He is currently the Chief Medical Officer for the Staten Island Performing Provider System. He serves as Chairman for the Staten Island Heart Society, is a member of the Board of Directors for New York eHealth Collaborative and Medical Liability Mutual Insurance Company, and serves on the Medical Society of the State of NY HIT committee. He has used an EHR and Patient Portal in his practice for almost 15 years.

### Motivation
**Why are we doing this? **
Dr. Volpe asked to be on the advisory board and has given really good feedback, and we are honoured. Very happy to do so.

**What use cases does it support? **
The more doctors can inform us on the product, the close we can get to product-market fit and help the users. It will also help us with our distribution model if doctors ask patients use this if they see the usefulness. 

**What is the expected outcome?**
We have another medical expert on our advisory board. It increases our legitimacy and gets us closer to product-market fit.

### Possible Alternatives

None, this is the lowest cost implementation.

### Additional Context

See links above.

**Comment by ngiangre** [comment]
@whoabuddy this is done right? Can we close?

**Comment by salvolpe** [comment]
Yes we can close haha
