### ISSUE TITLE
[FEAT] Create UX/UI of Pulse Capture via Camera

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#685]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement the feature.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Summary

Create a UI/UX for the  Pulse Capture via Camera feature.
It will need a button in the navbar as well. 

For now, we can replace the map feature with this feature that is NEEDED for MVP to be deployable in field. 

Decide on what icon we can use that has a non-restrictive license (heart icon, something that signifies pulse camera, etc).

There should be a toggle for the finger measurement (back-facing camera) and face (forward-facing camera)

The UI/UX will describe how it works with as few words as possible. It should be intuitive to use on the first try. The cleaner the UX/UI the better.

It will have its own view on the app.

See associated issue: https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/677

See: [ROADMAP-TO-MVP](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/ROADMAP-TO-MVP.md)

See this [github repo for an idea of how it work](https://github.com/habom2310/Heart-rate-measurement-using-camera)

Shout out to @habom2310 for creating this way back when.

examples:
See [examples 2020](https://www.lifewire.com/best-heart-rate-apps-4580412) 

see [more example 2015](https://www.livescience.com/49653-best-heart-rate-monitor-apps.html)

### Motivation
**Why are we doing this? **
We need a mock-up of how the pulse capture feature will look like. It is a KEY component to get to MVP status.

**What use cases does it support?**
Supports hitting our specifications to get to MVP status according to [ROADMAP-TO-MVP](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/ROADMAP-TO-MVP.md)

** What is the expected outcome? **
The Front end team knows what the UX/UI will look like for the [Feature](https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/677)

### Possible Alternatives

Just make it up as you go. But this creates a bottleneck and reduces collaboration across team.
This solution allows for collaboration and a clear picture of what to build.

### Additional Context

See: [ROADMAP-TO-MVP](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/ROADMAP-TO-MVP.md)

See this [github repo for an idea of how it work](https://github.com/habom2310/Heart-rate-measurement-using-camera)

See [examples 2020](https://www.lifewire.com/best-heart-rate-apps-4580412) 

see [more example 2015](https://www.livescience.com/49653-best-heart-rate-monitor-apps.html)

**Comment by AdhamAH** [comment]
Something like this?

![Screenshot 2020-05-01 at 11 48 55](https://user-images.githubusercontent.com/55054963/80797288-c0458b00-8ba1-11ea-898e-7ccd0e268fed.png)

**Comment by tesla809** [comment]
Looking AMAZING @AdhamAH !!! Can we have the heart alone instead?

**Comment by SvenVanPoucke** [comment]
Great, looking forward to use it, congrats

Op wo 6 mei 2020 00:12 schreef Anthony Albertorio <notifications@github.com

**Comment by SomeMoosery** [comment]
@BrianHHough when making a PR to add these to the `/design` directory (as I assume this is where wireframes should go still) - this is the issue you'll likely close when making the PR.

I can go ahead and make individual issues for each screen once this is done as we can easily parallelize this work.

**Comment by AdhamAH** [comment]
@SomeMoosery I made the skeleton for this as you can see. If you recall I had to `manully` to style `more.jsx` to fit into the `NavBar`.
When I made `NavBar.jsx` there was no plan for a popup. Using `BottomNavigation` if not the best thing here. So when @BrianHHough upload the design, we can make an issue to add the pulse button and update the `NavBar.jsx` with something more flexible like [this](https://material-ui.com/components/app-bar/#bottom-app-bar)

I think it is safe to close this for now

**Comment by SomeMoosery** [comment]
I saw you made that but it is difficult to track what is being done by who when changes aren't being tracked in issues. I know Brian uploaded I believe 8 new screens somewhere in Discord. I believe the process should be something:

1. @BrianHHough adds the wireframes to the appropriate folder and closes that Issue
2. We write out issues for all 8 new views
3. We parallelize the work and clearly track each

I just want to be sure we don't start relying too much on Discord and not tracking work being done in issues as that's how things can potentially get out of hand - it's a bit difficult to follow changes being made when there's no appropriate issues out / git flow being followed for them is all
