### ISSUE TITLE
Create UI flows for health log functionality

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#7]
In order to develop this application for an IPR smoothly, we should have flows/wireframes for navigating through the health log functionality of the app.

**Comment by BrianHHough** [comment]
Updating these as I go.

LOGIN SCREEN: 
![CORONATRACKER UI - Login Screen](https://user-images.githubusercontent.com/56947075/76705338-b5986a80-66b5-11ea-89c3-a18e0654c7a5.png)

**Comment by BrianHHough** [comment]
![CORONATRACKER UI - Health Log - My Log](https://user-images.githubusercontent.com/56947075/76819841-c8a75980-67df-11ea-9e1c-d0a10883914d.png)
 
![Uploading CORONATRACKER UI - Health Log - Show Me More.png…]()

**Comment by BrianHHough** [comment]
![CORONATRACKER UI - Symptom Screen](https://user-images.githubusercontent.com/56947075/76819886-eeccf980-67df-11ea-9a08-26f47437d536.png)
