### ISSUE TITLE
[FEAT] Add Dialog on Quiz Completion

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#700]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement the feature.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Summary

- [ ] On quiz completion, add a Dialog similar to others in the app saying something like "Here's how you did: score"
- [ ] Dialog should include the score in a format of `correct/total`

### Motivation

Instant gratification

**Comment by pavel-ilin** [comment]
Can take on this one
