### ISSUE TITLE
[FEAT] Enhance gsheet translations pull python script

### ISSUE THREAD

**Issue by ngiangre** [COVID-19-electronic-health-system/Corona-tracker#702]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement the feature.

### Prerequisites

- [ ] check this box if you have completed the following:
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Summary

See this PR for more comments #691.

We needed to merge the PR to move on to integration of translations, but there's more work in enhancing the python script. Broadly, 

- we can provide better docs on how to create a google credentials file, 
- make more modular and distinct functionality such as only doing depunctuating in one method versus duplicating efforts in multiple methods, and
- making the code overall less prone to bugs and errors from small changes in the gsheets

**Comment by SomeMoosery** [comment]
Could you show where there's multiple instances of depunctuation? I haven't touched this code too much, but definitely agree with your second point specifically. I'd be happy to make another issue out of that bullet point especially since that would be a great first issue, but I just want to be sure I have enough context 👍

**Comment by ngiangre** [comment]
<img width="750" alt="Screen Shot 2020-05-12 at 5 29 26 PM" src="https://user-images.githubusercontent.com/7811531/81747473-2968b080-9476-11ea-9e97-7c1b5587fd72.png">

<img width="333" alt="Screen Shot 2020-05-12 at 5 29 12 PM" src="https://user-images.githubusercontent.com/7811531/81747485-2cfc3780-9476-11ea-8d1f-925fcb2d88b2.png">

Atleast in these two instances I have a depunctuate method and then I also include depunctuating functionality in another method

**Comment by SomeMoosery** [comment]
Could we make another issue for updating documentation as well? I could, but I'm not sure of everything that needs to go into the documentation here.

Other than that, I think we can close this issue. While it's definitely worthwhile mentioning that the code should be less prone to bugs, it's hard to quantify that into actionable items 👍

**Comment by ngiangre** [comment]
Yeah I get that. Is there a way to make related issues that are like subissues? Would it just be varying the issue title?

**Comment by SomeMoosery** [comment]
Within the issue you can reference this one just using #702 and it'll reference them in the conversation I believe, although I'm not sure that a new issue would need to be inherently linked just since we're ideally going to be having more discrete action items for the documentation issue

**Comment by ngiangre** [comment]
closing in lieu of issues #713 and #714
