### ISSUE TITLE
[FEAT] Add helpful dialog on low behavioral score

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#707]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement the feature.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Summary

- [ ] When a user fills out a survey and puts a low value for the behavioral section, show a dialog with a national helpline or other resources you see fit to guide the user to help
  - [ ] threshold for what quantifies a "low score" is decided upon by team below

### Motivation

We want our users to have as many resources as possible to help them get through this pandemic.

**Comment by yuriyberezskyy** [comment]
I will work on it !!
