### ISSUE TITLE
Unhandled Rejection (LoginFailedError): Failed to login: Existing user session found

### ISSUE THREAD

**Issue by BrianHHough** [COVID-19-electronic-health-system/Corona-tracker#71]
<img width="1047" alt="Screen Shot 2020-03-17 at 9 20 31 PM" src="https://user-images.githubusercontent.com/56947075/76915933-54c78880-6895-11ea-9ab3-427a4af601f4.png">

Hey @SomeMoosery, i created a blockstack id, it was registered successfully, then i tried login with the login and got this error. Just wanted to flag. Everything else is looking great though!

**Comment by SomeMoosery** [comment]
This is fixed
