### ISSUE TITLE
[FEAT] Update bottom nav to new UI flow

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#716]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement the feature.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Summary

- [x] Bottom nav contains Log, Education, More, Map, and Profile
- [ ] Clicking More opens up the popup as shown below
  - [ ] Links do not navigate anywhere for the sake of this issue, the linking will be captured in other issues

<img width="187" alt="Screen Shot 2020-05-16 at 5 49 10 PM" src="https://user-images.githubusercontent.com/15767602/82130920-ba54ca00-979d-11ea-960d-a8efe969eb68.png">

### Motivation

Moving towards final UI

**Comment by AdhamAH** [comment]
What do you think @BrianHHough ? Becuase the last button is more than profile.
![Screenshot 2020-05-19 at 14 56 24](https://user-images.githubusercontent.com/55054963/82328991-ec09a300-99e0-11ea-9326-b8a88423f827.png)

**Comment by BrianHHough** [comment]
I LOVE the top one with the MORE and SETTINGS @AdhamAH . I think the settings, broadly, can let us include things related to the app/account and the more section lets us expand CoronaTracker to other things when/where we can.

**Comment by AdhamAH** [comment]
@BrianHHough does this look good?
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/55054963/83306786-864cc080-a203-11ea-831e-001275a10560.gif)
