### ISSUE TITLE
[FEAT] Add react-i18next tag to Layout components folder

### ISSUE THREAD

**Issue by AdhamAH** [COVID-19-electronic-health-system/Corona-tracker#725]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement the feature.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Summary
Add `<Trans/>` tag with the related `i18nKey` in `locales` JSON files ***use the EN as it is the default***

### Motivation
Applying the translations 

### Possible Alternatives
no translations

**Comment by pavel-ilin** [comment]
Hey @AdhamAH, if you not start working on that, I can jump in.

**Comment by AdhamAH** [comment]
I am almost done with it @pavel-ilin  😅

**Comment by pavel-ilin** [comment]
Got it, sorry with my delays!
