### ISSUE TITLE
Collecting user data through Progressive Profiling

### ISSUE THREAD

**Issue by nathanboone** [COVID-19-electronic-health-system/Corona-tracker#73]
Hey Team,

In order to elicit users to share information about themselves, I've used Progressive Profiling, a feature for forms, where new questions appear for returning users who've completed the form prior.

As we think about how to garnish data, without overloading the user, let's consider 3 or 4 sets of questions that could be rotated as users engage with the app.

A description can be found here: https://auth0.com/docs/users/concepts/overview-progressive-profiling

**Comment by tesla809** [comment]
Great idea Nathan! This will help engagement over time if we can get the data in pieces over time.

We should add this to our design flow.

**Comment by ngiangre** [comment]
@nathanboone ready to brainstorm this? DM in discord.
