### ISSUE TITLE
Stand Ups suggestions

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#77]
Suggestion:

To track progress, should we do stand-ups, every two days at nights?
What time after 6pm EST work for the team?

Standups are used in software development teams to keep everyone in synch. 
Different teams summerize their progress, questions, comments and concerns.
Each team debriefs on what has gone on during the day or previous day. 
They state any blockers (things that are preventing them from completing a task) and how it can be solved.
Teams also talk about the upcoming tasks they will do.

They usually last 10 to 15 minutes.

Thoughts?

**Comment by ngiangre** [comment]
I agree! Short, simple, but effective. Is the meeting at 630pm tonight happening?

**Comment by ngiangre** [comment]
closing - we'll discuss this at team admin meeting monday
