### ISSUE TITLE
Grant for project 

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#78]
**The due date is 2 days from now.**
**Due:** Friday, March 20 at midnight
**Winner:** Monday, March 23.

**Micro-grant:** $5,000

**About:** The grant is for $5000 and can be spent for just about any activity that helps inform the public.

**Info:**
This Call for Proposals is open to the general public and an affiliation to Columbia or Stanford is not required. Proposals should follow strict CDC guidelines and not suggest activities that put the grantee or the public at greater risk.

See: https://brown.submittable.com/submit

**Grant:**
Recognizing a profound need for accurate information about the COVID-19 virus, the Brown Institute for Media Innovation is offering a “rapid” micro-grant to help support journalists, technologists, health researchers, data scientists, social scientists, and any and all communities involved in covering the virus. The grant is for $5000 and can be spent for just about any activity that helps inform the public. Examples include novel modes of tracking the progress of the virus, the responses by various governmental organizations, and predictions of its impact — the subject is open. Outcomes might include data and data visualizations, tools to spot and combat misinformation about the virus, a documentary or a reported story, a VR/AR experience or an interactive of some kind. 

Applications to the COVID-19 Reporting Micro-grant are due Friday, March 20 at midnight and we will announce a winner on Monday, March 23. The application itself consists of a 1-page PDF description of your project, together with a small budget outlining how you will spend the funds. Contact browninstitute@columbia.edu with any questions.

This Call for Proposals is open to the general public and an affiliation to Columbia or Stanford is not required. Proposals should follow strict CDC guidelines and not suggest activities that put the grantee or the public at greater risk.
https://brown.submittable.com/submit

**Comment by ngiangre** [comment]
@SomeMoosery can you and others get me some UI images to possible include and a description of already implemented and projected features by tonight?

**Comment by ngiangre** [comment]
@nathanboone as well?

**Comment by tesla809** [comment]
@BrianHHough can help with UI images.

**Comment by tesla809** [comment]
**Goal:**
To create a progressive web application that is accessible by the internet. The app will be a registry to help doctors track the symptoms of large amounts of patients real-time with self-reported data using a dashboard. 

We hope to reduce the number of unnecessary visits to hospital emergency rooms and encourage CDC and WHO guidelines.

**Our target population are:**
1.  Cellphone users between the ages of 25- 45. These people will have a high likely hood of being caretakers of younger age groups and older adults. They are also highly engaged with our me

2) High-risk populations with issues related to diabetes, obesity, kidney diseases, and immune system disorder.

**Process:**  
Weekly sprints with the team with distributed teams.

Version 1: 
Educate the population, have translations of CDC and WHO guidelines.

Version 2:
Activate survey data collection more.

Version 3: 
Share data with hospital systems
 Activate data analysis.

Progress made so far: 
We started on Friday, March 13th, 2020.
1. Assembled medical advisory team with three experts.
2. Assembled development team member with x members.
3. Over 130+ commits
4. Blockstack integration for patients to own their own data. 
5. encrypted MongoDB server for privacy. 
6. Deployment to AWS Login Screen.
7. Mockups of UX/UI
8. Assembled translations team with language experience in Italian, French, Chinese Mandarin, Russian, Arabic, Spanish.

Consultations:
We are being advised by medical professionals to create a product that will be useful during the COVID-19 pandemic. 

We have had consultations with Dr. Kristen Kent, emergency room doctor who has helped write guidelines for New York State emergency rooms. 

Consultations with Dr. Jigna Zatakia, former assistant Professor in Pulmonary Critical Care Medicine at Baylor College of Medicine. Now at Mount Sinai Hospital.

Consultations with Systems Architect Ameeruddin Ahmed, CTO and CEO with experience in enterprise workflow automation for large institutions and medical offices.

Consultations from Blockstack PBC, a blockchain company developing technologies to decentralized data ownership and increase privacy.

Team:
Carter Klein, Full-stack Developer working on back end systems. From X company. 

Brian H Hough- Design, UX/UI, Social Media Marketer Guru for X company

Nick Giangreco- Systems Biology PHD candidate at Columbia University. An organizer of the non-profit New York Health Artificial Intelligence Society, with over 4,500 members, including doctors, data scientists, programmers, and more. 

Anthony Albertorio- Full Stack Developer and an organizer the non-profit New York Health Artificial Intelligence Society.

Nathan Boone- Marketer for X Healthcare Marketing Company. 

Team:
Front End Developers:
Add in developer names here.

Back end Team:

Translation Team:

Operations:

UI/UI team:

What else?

**Comment by tesla809** [comment]
please add in more.

**Comment by ngiangre** [comment]
I created an account for submission. I'll draft this locally (so as to add references) but I'll add the draft to this gdoc https://docs.google.com/document/d/15i7vBDCFqGHCf3B-D9Miw0_3I1M6_rn3v4fzA1PAAK4/edit?usp=sharing

**Comment by ngiangre** [comment]
I hope everyone is cool is I tone down language about the app serving doctors and clinics directly per the call yesterday and the suggestion to calm public nerves and give accurate information to also reduce traffic to hospitals and exposure.

**Comment by SomeMoosery** [comment]
Sorry for the late response on this - I've been setting up a simple QA environment so we can all start adding/manipulating/etc the same hosted data and not locally-mocked data. I just opened the doc and it's blank - nothing's weird on my end right? You just haven't posted it there yet?

Just a few quick thoughts I had that I'll add here.
- I've never written a proposal like this before, so maybe this would boost our legitimacy, but I've found that measuring # of commits is oftentimes not a good metric for activity, similar to # of lines of code - you could have a repo with 1000 "update readme" commits that does nothing, and a repo with 100 commits that delivers something crazy cool. I was actually planning to include a guideline around squashing commits so that each PR has only 1 commit (with reasoning included) once this matures and I'm hopefully able to step back from the code at such a granular and, team willing, take on some more higher-level tech responsibilities.
- With this being due in 2 days, we'll almost definitely need to use the wireframes provided by @BrianHHough as opposed to the actual UI of the app, as that's still in the process of coming together. We're parallelizing super well and making each little component very quickly, but we may not have full UI flows crafted within the next 2 days.
- I saw that there's a spot for my credentials - if you want to put those in now I'm a Full Stack Software Engineer at Capital One lol.

Happy to provide more feedback on the technical side of things as we draft this! Fingers crossed!

**Comment by ngiangre** [comment]
Thanks @tesla809 and @SomeMoosery! I finished a draft. I think we need to cut out about 100 words roughly and make our implementation and grant need more succinct. Any comments would be appreciated! https://docs.google.com/document/d/15i7vBDCFqGHCf3B-D9Miw0_3I1M6_rn3v4fzA1PAAK4/edit?usp=sharing

**Comment by friedger** [comment]
The current draft reads more like support for marketing campaign of WHO/CDC pages. The problem is clear, but the solution is too vague, in my opinion. More focus on the survey.

**Comment by givonz** [comment]
Professionally speaking, a grant proposal is supposed to include;

A Problem
Your Solution
What your solution will cost
How effective your solution will be.
    - How it will reduce cost
    - How it will speed up the process
    - How it will make the process better
Who's doing this?
    - What are their credentials.

Reading some of the comments, it's a bit unclear to me, what the problem being addressed is and; what the proposed solution is.  Most of all, I see nothing that tells me HOW you intend to spend the $5K they will give you!

*************
Goal:
To create a progressive web application that is accessible by the internet. The app will be a registry to help doctors track the symptoms of large amounts of patients real-time with self-reported data using a dashboard.

We hope to reduce the number of unnecessary visits to hospital emergency rooms and encourage CDC and WHO guidelines.
**************

I don't see the connection between the 2 stmts.  Even within the stmts.
Who are these doctors who will do the monitoring?
Are these doctors monitoring self-reporting or potentially self-reporting individuals?
To what end?  Are we flagging areas as places to avoid?
Or, does this up risk factor?  Meaning if you are coughing in the middle of the dessert, it may not be COV19 but, if you are coughing in a risk area, you could have COV19, self isolate and get tested.

How are you reducing hopsital visits?  Unstated.
How are you encouraging CDC & WHO guidelines, unless you mean self-isolation and avoiding hotspots.  This needs to be stated.

Perhaps better stated:

*************
Goal:
To create a progressive web application that is accessible by the internet. The app will pre-screen those who think they may be infected and be a registry of those who pre-screen as infected as well as those who choose to anonymously self-identify as affected.  Doctors will be able to separately add information about reported cases.  This will help doctors track the location of hotspots with either an infected or potentially infected population.  Hospitals will be able to access this information to be up-to-date with the size and location of the infected population.

The app is designed to handle large numbers of patients, in real-time and a dashboard.

We hope to reduce the number of unnecessary visits to hospital emergency rooms with pre-screening; as well as promote knowleadgeable self-isolation with accurate, up-to-date information and maps.  This will encourage CDC and WHO guidelines.
The app is designed to be multi-lingual.
Currently, this is a volunteer crowd-sourced project.  Funds would be allocated to...
**************

The team part is fine.

**Comment by givonz** [comment]
Add Hebrew to the list of languages.

Use action words for the goal.  No "hope".  The app "will" do whatever.

**Comment by ngiangre** [comment]
Thanks @givonz and @friedger! Feel free to directly edit - here's an edittable link https://docs.google.com/document/d/15i7vBDCFqGHCf3B-D9Miw0_3I1M6_rn3v4fzA1PAAK4/edit?usp=sharing.

We need to start the CV/resume draft. Here's an edittable link:  https://docs.google.com/document/d/1aXutktBGqYkSSHNQzACXNgop7_EpcewlGfSdBwks_co/edit?usp=sharing. So far we have:

Team:
Front End Developers:
Anthony Albertorio- Full Stack Developer and an organizer the non-profit New York Health Artificial Intelligence Society.

Back end Team:
Carter Klein, Full Stack Software Engineer at Capital One

Translation Team:

Survey/Analytics:
Nick Giangreco- Systems Biology PHD candidate at Columbia University. An organizer of the non-profit New York Health Artificial Intelligence Society, with over 4,500 members, including doctors, data scientists, programmers, and more. My actual CV is here http://nickg.bio/CV/Nicholas_Giangreco_CV.html

UI/UX team:
Brian H Hough- Social Media Marketer  for X company
Nathan Boone- Marketer for X Healthcare Marketing Company.

It's not great but we can make a call for everyone to fill in the necessary credentials. There's no guidelines on how to do the resume especially one for a team...Any suggestions?

**Comment by salvolpe** [comment]
@ngiangre I think that having people fill in as they can is the best we can do as the team keeps growing daily haha

**Comment by ngiangre** [comment]
Yes @salvolpe I agree anyone that can edit/revise go right ahead!

**Comment by friedger** [comment]
Here is a document for resumes: 
https://docs.google.com/document/d/1w6I2T3mscTQjk2KgpeOkXXUC-7hxsfXdABFIaCeYFX4/edit#

**Comment by tesla809** [comment]
Added bio to document.

**Comment by tesla809** [comment]
edited and added information to grant proposal. @BrianHHough we need to add images of mockups to application. Each view needs its own image and to describe the workflow.

@SomeMoosery would we need to add the graphics you created for out database models so far? Thoughts on that?

@ngiangre @givonz @friedger What do ya'll think?

**Comment by ngiangre** [comment]
FYI The proposal is one page (we can have images in a figure be on another page but that's it). And one page for a CV/Resume.

**Comment by tesla809** [comment]
Aaa we might need to edit and shrink down then.

**Comment by SomeMoosery** [comment]
So as it stands now, the backend models are pretty simple as Blockstack abstracts away a lot of the backend/API work we'd otherwise need to handle ourselves - so I'm not sure how much of a use that would be. Plus, our current state is certainly going to change quite a bit as we move towards an end state.

I've been meaning to draft out a production-ready first draft for the architecture I think we'd end up using. This is personally my first time doing something like this, so I assume as we get feedback and more people onboard the design will change as we go along. I could try and have that done by the end of tonight if we want to use it as an additional reference. But, it seems like we may want to shrink it down, anyway.

**Comment by tesla809** [comment]
Sounds good to me! Let's keep it simple for now then. @SomeMoosery

**Comment by ngiangre** [comment]
@tesla809 et al need some input on comments here in the draft https://docs.google.com/document/d/15i7vBDCFqGHCf3B-D9Miw0_3I1M6_rn3v4fzA1PAAK4/edit?usp=sharing and please restrain your bio descriptions to at most 3 sentences about 1) your day job and skills 2) education and 3) your project contribution. https://docs.google.com/document/d/1w6I2T3mscTQjk2KgpeOkXXUC-7hxsfXdABFIaCeYFX4/edit?usp=sharing

**Comment by tesla809** [comment]
Updated!

**Comment by tesla809** [comment]
Due tonight by midnight.

**Comment by ngiangre** [comment]
submitted - great job everyone!
