### ISSUE TITLE
March 26th - Webinars Concerning Coronavirus

### ISSUE THREAD

**Issue by salvolpe** [COVID-19-electronic-health-system/Corona-tracker#81]
**Here is the link to register for the webinar:**
https://ehealthinitiative.zoom.us/webinar/register/WN_Py1oNxobRhqWLoUyP4q2FQ

With wide-scale responses underway by countries to counter the coronavirus’ spread, the use of technologies such as Artificial Intelligence (AI) may prove to be vitally important now and in the future.

The US health system at the brink of operating at above capacity and healthcare organizations need clarity on how to address COVID-19 risk within their population and their community more broadly. AI has the ability to deliver insights that can assist national response to COVID-19 by giving insights into which hospitals will have similar experiences and impacts, insights to help communities plan for when and how healthcare resources will be impacted, insights into highest risk patients, and provide clinicians with point-of-care clinical decision support.

Please join us while we discuss some important developments in AI with real-world examples AI insights and how providers and communities can apply them to drive optimal outcomes during times like these.

Speakers:

- Lori Tremmel Freeman, CEO, NACCHO
- John Frownfelter, MD, CMIO, Jvion
- Priyanka Suiro, Director of Informatics, ASTHO
- John Showalter, MD, Chief Product Officer, Jvion

**Comment by tesla809** [comment]
@ngiangre @akilhylton @SomeMoosery @renegmed @BrianHHough Any interest?

**Comment by ngiangre** [comment]
Honestly I think we have a good idea of what our MVP is based on our zoom call yesterday so I wouldn't attend since I don't think we'll learn anything more. But I can be wrong. Someone should def attend though to be sure!

**Comment by SomeMoosery** [comment]
Unfortunately don't think I'd be able to join as it's during work hours, but I'll see if I can fit it into my schedule and at least listen in!

**Comment by BrianHHough** [comment]
I'm in the same boat as @SomeMoosery but maybe there will be a recording of the webinar that we can listen to later?

**Comment by salvolpe** [comment]
I hope there is a recording ¯\_(ツ)_/¯

**Comment by salvolpe** [comment]
Alternatively, there is a different webinar discussing Italy and Germany's responses: 

http://pages.himss.org/dR0GVnTVMQ0Wg00LK3530Z0

**Comment by SomeMoosery** [comment]
Going to close this as there's no action items to be taken, should add to a Google Calendar
