### ISSUE TITLE
Create Education Collection

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#86]
After the call with Dr Zatakia last evening, we want to initially aim this app primarily at education. A good point made by a few collaborators on the call was that we should generate a few "fun" facts about Coronavirus - that is, facts and suggestions aimed to simply calm and inform users, not aggravate an already highly-stressful situation.

[A list of educational points](https://docs.google.com/spreadsheets/d/1Ji0sxIqFI49EZb7Mz4F0nkSBn1JSNMXiKjFAzJC2Jso/edit?usp=sharing)

I would suggest that, for the time being, we create an array of these facts that we just randomly select when rendering the component the displays the survey to fill out. In `client/models/` (which will be visible when [my last PR](https://github.com/COVID-19-electronic-health-system/Corona-tracker/pull/84) merges in) just create a data object `Facts` (or something like that) that's easily randomly indexable (like associate a numeric id with it).

 A long-term solution to how to architect this could be: 

We would be to store these facts in a MongoDB cluster (or any type of database, I just suggest MongoDB since we are using that with Radiks) and create a backend service to query from UI <--> service <--> database, or just a simple Lambda function, hosted on AWS along with our Radiks server and associated MongoDB cluster. **This would be an additional cost associated with our project.**

**Comment by friedger** [comment]
For performance and for PWA, it would be better to pre-render the questions (isomorphic style)

**Comment by tesla809** [comment]
We will create something in a [google doc](https://docs.google.com/document/d/1GJRYYeV0ZhzTCOXAvRVEGPA6zdFTLu1bEPUTfB04OaY/edit). Then when it's all done, should we push that info t ao .js file with an array that can be queried.

**Comment by ngiangre** [comment]
Use this link instead to log in educational content. See education subsheet https://docs.google.com/spreadsheets/d/1Ji0sxIqFI49EZb7Mz4F0nkSBn1JSNMXiKjFAzJC2Jso/edit?usp=sharing

**Comment by starving-geek** [comment]
I can work on the model for this @SomeMoosery

**Comment by SomeMoosery** [comment]
Closed by #148
