### ISSUE TITLE
Create Checkup/Survey Model

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#88]
In `client/models/`, we need to create a Checkup data model for each checkup or survey associated with a CoronaTracker user.

**Acceptance Critera:**
- There is a new model in `client/models/` outlining what a checkup/survey will look like in the database

**Notes:**
- May require some discovery and finalization with regards to what information we'll be gathering. This can be incremental, though - we just need a general model for now.

**Comment by ngiangre** [comment]
Do you mean like a table format? Each survey question should populate a field and each user should populate a row. Or in json each user is a dictionary and each field is a key and their answer is a value. Is that what you mean?

**Comment by SomeMoosery** [comment]
Yeah, that's what I had in mind. Radiks implements MongoDB to aggregate the user data stored in Gaia (Blockstack's object/file store) in a centralized location so that it's easily queryable and manipulatable (see [here](https://docs.blockstack.org/develop/radiks-intro.html#how-radiks-works-with-application-data) for a better explanation than I can probably provide). 

This was more of a discussion on the specific fields we'll store in the JSON object associated with each checkup/survey taken for each user.

Querying would be something as simple as `Checkup.fetchOwnList()` - an example of something similar is being done in master now with a dummy "Patient" model.

**Comment by ngiangre** [comment]
I c an give you some fields if you want.

**Comment by SomeMoosery** [comment]
That would be great! Yeah I've just been hesitant to add them myself, but just even a first set of things we'd need.

I'm thinking like:
- if you have a fever
- if you are having trouble breathing
- your location
- etc...

I just don't have the medical know-how to designate a set list and wanted to defer to someone with more expertise. If you give me the list, I can create the model and add some dummy data to the QA environment tonight/tomorrow morning if that works for you 🚀 (or if you want to tackle it all let me know!)

**Comment by ngiangre** [comment]
Here's a spread sheet we should use to collate survey questions and align it with 1) the purpose of this data and 2) how we would store it in the backend. 

https://docs.google.com/spreadsheets/d/1Ji0sxIqFI49EZb7Mz4F0nkSBn1JSNMXiKjFAzJC2Jso/edit?usp=sharing

Let's make a call on discord tomorrow for a survey team that is different from the core team getting v1 out.

**Comment by SomeMoosery** [comment]
Good idea, thanks! Yeah, let’s get on it tomorrow for sure
