### ISSUE TITLE
Populate QA environment with mocked checkup data

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#89]
In order to start rendering out UI components with "real" mocked data (data that isn't user-generated, but is being pulled from a distributed database), we need to add some test data to the MongoDB cluster in our QA environment.

The steps to do this would be to create a Blockstack account and simply edit `App.js` (or another file that runs every time the site loads) and add some JavaScript code to create a Checkup (or multiple Checkups) associated with this Blockstack ID, and persist them to the MongoDB cluster.

**Acceptance Criteria:**
- A number of Checkup or Survey (or whatever the assignee of #88 calls it) entries are fetchable in the MongoDB collection
- `App.js`, or whichever file you decided to run your script to create these models, is returned to its original state

**Comment by friedger** [comment]
What is the data model for the stored data? Currently, there is only `Patient`.

**Comment by SomeMoosery** [comment]
So #88 deals with creating a checkup/survey/whatever-you-want-to-name-it model translating to a MongoDB collection of checkups/surveys/etc the user completes. Something like:

**Checkup:**
```
date: Date
temperature: Number
fever: Boolean
...
```

It'll require some discussion and finalization with the group to come up with a kind of "MVP" data model for this as we've been posting a lot of great articles about how to format this survey, but haven't decided on which targeted questions to actually ask the user yet.

I'm thinking that creating data models might be an iterative process, where we create models as we need them. I'm really thinking that, for the time being, the only model we'll need is actually this checkup/survey/etc model, since pretty much everything else will be stored client side temporarily (I think we should store facts/suggestions relating to COVID-19 in an array on the client-side until we have the funds to host these publicly), or will be pulled from a third-party API. 

Also, once we have a data model set up, the legwork for backend stuff is handled by Blockstack/Radiks, no need to write endpoints and a custom server for the time being, all we have to do is call the Radiks API to manipulate data.

What do you think?

**Comment by friedger** [comment]
As we have a model, this could be closed. The data will come as initial state from redux

**Comment by friedger** [comment]
This could be closed.
