### ISSUE TITLE
Map out core models of the health log

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#9]
In order to clearly define the scope of what we're building, the core features of this health log need to be mapped out and some lower-level details need to be defined.

- What data we need from users and how we'll be storing it

**Comment by SomeMoosery** [comment]
So, @ngiangre brings up a good point in [this issue](https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/59) regarding populating charts with mock data. I think as we continue to set up a lot of the scaffolding with the UI, backend, and database, we should consider moving forward with two action items:
1. Piecing together these separate UI components in order to start forming cohesive flows
2. Populating charts with mock user data

I think that piecing together separate UI components will simply come with time as more and more are completed, but dealing with populating charts with mock user data brings up a couple of points.

## Some things we need to discuss
1. We need to finalize what the user flows will look like. For example, I've realized we have wireframes for a doctor viewing a list of patients / patient details, but no tab really associated with that unless I'm missing something.
- Should there be a separate "For Doctors" tab in the bottom nav that only verified doctors can access? 
- If so, I have some ideas on how we could go about doing that. But, this leads into my second point.
2. We need at least a somewhat-finalized data model that is dependent on question 1. I'm going to put my thoughts below:

## Thoughts on data model: 
Blockstack is unique in that user credentials are stored on the blockchain, and are ubiquitous across all apps built on the Blockstack platform. You only need one username/password (or Blockstack ID) for any app built on Blockstack. With each Blockstack ID, you get a certain amount of decentralized file storage through Gaia, Blockstack's decentralized storage system. This is great for privacy and censorship-resistance, as all data on Gaia is off-chain. Radiks is then used as a middleman allowing you to securely query all of these decentralized files as if they were a simple MongoDB database. 

Hopefully that all makes sense, as this is all pretty new to me as well. If you need any clarification, please let me know and I'll do my best to help.

With all that out of the way, here's how I'm suggesting we model the data, and strategies that will get us there. It ends up being pretty simple.

1. Each time anyone, patient or doctor, logs into this application, we update a Location collection associated with their Blockstack ID (or create one if it's their first time logging in). That way, we'll be able to keep track of where users are while using the app for easy and up-to-date location information. 
2. Any user has the ability to complete a checkup based on the survey we create. Each time a survey is completed, we can simply add another Survey associated with this user to a Surveys collection. This is probably the most straightforward database aspect of all of this.
3. This is the diciest part of all of this. I think we should have an additional tab for doctors, where they can see this aggregated wellbeing list of people in their area in order to triage. To do this, I think for the time being we should have at least a phone call with the doctor to verify them and all of their info. Once we do that, we can simply put that info into a `doctor.txt` file and put it in the Gaia storage associated with that Blockstack ID. Then, whenever anyone (patient or doctor) logs into the application, all we have to do is see if they have a `doctor.txt` file associated with their Blockstack ID. If they do, we allow them to access this list of patients. If not, we don't. The Doctor View tab can remain for patients, but will just have an overlay (instead of the aggregated list) with a prompt to set up a consultation if they wish to have access to the list.

I may be missing something, and I don't know the levels of security to which we have to / should go before displaying individuals' information (I assume we'll have some kind of terms & conditions with the app saying "you give doctors in your area the right to view your condition" or something like that. 

I know this was a long writeup, but hopefully you take the time to read it.

I'd be willing to set up a call to discuss this further and finalize some details. @tesla809 - I know you've been reaching out to a bunch of people, so you'd probably be the best one to suggest a time.

**Comment by ngiangre** [comment]
Thanks @SomeMoosery  for the detailed points. One thought: We can't give doctors more on their plate. We can make their normal workflow easier potentially, but we can't add another thing to their workflow. That's why, for any healthcare/MD feature, we need understand healthcare workers potential needs, mock up the suggested needs, and then try to partner with a healthcare system that could use this after extensions are made. It's much easier to have something be used at the community level because ppl will use anything useful. Hospitals/etc. on the other hand, have systems and protocols in place and to follow.

Nevertheless, we need to mock up some things first. Let's have a call after the startup/MD calls.

**Comment by SomeMoosery** [comment]
Very good point - as a software engineer in finance, I'm certainly no expert on the ins and outs of the healthcare space lol. I'm hoping the call tonight will provide some more clarity on how we can best help healthcare professionals (if we can at all, and if not perhaps we take a different route).

I think, if anything, this has helped us defined the scope that our public release should perhaps just include the symptom-tracking functionality to roll out to individuals, and for the time being we would simply internally aggregate/analyze the data collected.

**Comment by SomeMoosery** [comment]
Closing this - for the time being, it seems that there won't be too much to persist to a database - really just information pertinent to each checkup a user completes. Can open up again or create a new issue once we reach V2, V3 - but we should prune this issue list as it's starting to grow pretty large.
