### ISSUE TITLE
Update Temperature subcomponent with user data

### ISSUE THREAD

**Issue by SomeMoosery** [COVID-19-electronic-health-system/Corona-tracker#91]
Edit `Temperature.js` component in order to get the average temperature of all checkups the signed-in user has completed. 

**Acceptance Criteria:**
- Flow should be the user signs in with Blockstack, and is then able to see their average temperature over all their completed checkups
- Data is pulled from QA environment for the logged-in user
- Any addition of `Temperature.js` to another component is cleaned up and returned to original state so as to avoid scope creep. 

**Notes:**
- Until `Temperature.js` is included within `DiagnosticContainer.js` (which a WIP PR is out for in #90 ), then you'll have to probably update `App.js` to just add it in any spot for the time being, but be sure to clean up once PR is made to stay within scope.

**Comment by friedger** [comment]
The data is expected from the container in this solution: https://github.com/friedger/Corona-tracker/commit/c97ca57f2e717a9acff951c94226b80f47b22b30

**Comment by SomeMoosery** [comment]
I like the look of this a lot! I hadn't even thought about `Temperature.js` being class-based when it should be functional. Want to make a PR for it?
