### ISSUE TITLE
Rename ChartJS.js to Chart.js

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#92]
Quick fix to rename ChartJS.js to Chart.js in /components

**Comment by friedger** [comment]
Yes, do it :-)

**Comment by pavel-ilin** [comment]
Pull request: https://github.com/COVID-19-electronic-health-system/Corona-tracker/pull/116

ChartJs component being renamed into Chart. Adjust import statement from 'chart.js' library.
Adjust Chart.test.js'
