### ISSUE TITLE
Draft Email to Full Stack Academy for solicit help- Can be used by others to look for recruits

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/Corona-tracker#97]
Full-stack academy of code email
**Please edit if you like.**
 
Hi David,

Hope all is well with you, your family and your students.
 
Currently, the team from New York Health Artificial Intelligence Society (NYHAIS) and I are creating an application to help with the COVID-19 epidemic.
 
NYHAIS is a New York State non-profit dedicated to the improvement of healthcare with technology. This pandemic has railed the community to try to address the coming swelling of cases in the NYC hospital system and around the country. 
Our app will inform patients, collect their information and allow doctors to monitor large numbers of patients' symptoms over time (daily or less).
 
We have wireframes, backend (encrypted MongoDB database on AWS), and front end in the works. We are being advised by a pulmonary critical care specialist from Mount Sinai, an emergency room doctor, and a system architect for medical institutions. 

Currently, we need MERN stack devs. 

Would any alumni be interested in collaborating? I know that FSA grads are of high calibre and would make a meaningful impact on the effort.

Do you know any alumni or students developers that are interested in contributing?

So far we have students from Flatiron School contributing  to the project. This effort is a community action of a bunch of concerned developers trying to help improve the situation.
 
Repo:
https://github.com/COVID-19-electronic-health-system/Corona-tracker
 
Join Discord server:
https://discord.gg/pPERUuv
 
Design:
https://github.com/COVID-19-electronic-health-system/Corona-tracker/tree/master/design
 
Thanks,
[Your Name Here]

**Comment by ngiangre** [comment]
looks good! Change railed to rallied.  If there's an influx of people, do you have a sufficient contributing document?

**Comment by SomeMoosery** [comment]
Fleshing out a contributing doc is definitely something high on my priority list, at least 👍

**Comment by ngiangre** [comment]
was this sent? If so, please close this issue.
